### ISSUE TITLE
Nullable return from child function

### ISSUE THREAD

**Issue by chenglou** [chenglou/react-motion#101]
```jsx
<Spring endValue={{val: 0}}>
  {({val}) => val === 0 ? null : <div>stuff</div>}
</Spring>
```
Very handy shortcut for animating one child unmounting.

Right now, we have to use an empty `<div />` placeholder.

**Comment by nkbt** [comment]
I use this with 0.1.0. Do you mean it doesn't work anymore?

**Comment by chenglou** [comment]
Really? 0.1.0 enforced the one child return through React onlyChild. This hasn't changed.

**Comment by nkbt** [comment]
Only child works fine with null.

**Comment by chenglou** [comment]
It should throw?

```
Uncaught Error: Invariant Violation: onlyChild must be passed a children with exactly one child.
```

**Comment by nkbt** [comment]
I'll doublecheck, but I am sure 0.1.0 worked well with this.

**Comment by chenglou** [comment]
Just checked, didn't work with 0.1.0 (expected behavior). Worked pre-0.1.0 naturally.
