### ISSUE TITLE
react-native warning

### ISSUE THREAD

**Issue by smussell** [chenglou/react-motion#109]
I started getting this warning when I require react-motion in my web project.

```
WARNING in ./~/react-motion/lib/Spring.js
Module not found: Error: Cannot resolve module 'react-native' in /Users/sam/Dropbox/Development/Projects/Apple/reviz/node_modules/react-motion/lib
 @ ./~/react-motion/lib/Spring.js 35:10-33
```

**Comment by threepointone** [comment]
This warning is a known issue because of the way we do react-native compatibility, and should go away with React 0.14. It shouldn't affect your code/project though. In the meantime, add externals : ['react-native'] to your webpack config to suppress these warning.

**Comment by chenglou** [comment]
It doesn't go away with react 0.14 since react-native still uses `require('react-native')`? Anyways, https://github.com/chenglou/react-motion/issues/29#issuecomment-125900800

**Comment by smussell** [comment]
Thanks, seems like this is being tracked in #29, so I'll close this.

**Comment by threepointone** [comment]
Boo, you're right :/
