### ISSUE TITLE
Publish to npm?

### ISSUE THREAD

**Issue by dariocravero** [chenglou/react-motion#11]
Hi Cheng,

Have you considered publishing to npm (even if its internals are still to change?). The npm package `react-animation` [is already taken](https://www.npmjs.com/package/react-animation). However, that other project [seems like it never kicked off](https://github.com/akiran/react-animation). Perhaps you can claim it or publish to a different name?

Thanks :)
Darío

**Comment by chenglou** [comment]
Man, I totally forgot to check that before I started iterating on this repo... thanks for the heads up. I'll reach out and see what happens!
If it doesn't work out, feel free to brainstorm new names here. React-animation sounds a bit plain.

**Comment by dariocravero** [comment]
Brilliant :) I'll think of something :).

Also, I have a few suggestions regarding the code, off the top of my head:

- use `Array.isArray` instead of [[object Array]](https://github.com/chenglou/react-animation/blob/ccac69e565f7d2c167a1cb7330877be38f0c1062/Spring.jsx#L36).
- [use triple equality](https://github.com/chenglou/react-animation/blob/ccac69e565f7d2c167a1cb7330877be38f0c1062/Spring.jsx#L33).
- put the examples into an examples folder :),
- separate `TransitionSpring` and `Spring` into different files and preferably some of the internals into different files too for easier testability and better code readability,
- move the hacks away from `render` :),
- make strings like `currVals` more explicit, e.g.: `currValues`,
- use `js` (or `.es6`, [we're using that extension to compile js to npm without changing paths](https://github.com/UXtemple/panels-runtime/blob/master/.bin/compile)) instead of `jsx`,
- use classes because you're already on es6 and newer versions of react won't use `createClass` anymore,
- [use ternary operators here and there](https://github.com/chenglou/react-animation/blob/ccac69e565f7d2c167a1cb7330877be38f0c1062/Spring.jsx#L427-L431)

I'm sure you're already aware of many of those. I wouldn't mind tackling some if not all of them.

Thoughts?

**Comment by chenglou** [comment]
You're right on most points but fixing them now is almost a waste of time, because I'm changing them, like, as we speak =). The local version already looks different.

Turned your stuff into check marks.

It'll be more productive for us right now to iterate on the API. I'll write down some more issues. Feel free to check the long-ass #9 meanwhile!

**Comment by dariocravero** [comment]
Also:
- use `.babelrc` instead of a string in the loader,
- probably separate webpack's config for `dev` and `production`?
- either warn about the need for `__DEV__` to be set if you're not using that plugin in your webpack or you aren't using webpack but are linking the package. I'm getting `Uncaught ReferenceError: __DEV__ is not defined` which isn't a big deal to workaround but still :)

**Comment by dariocravero** [comment]
Class :) I'll wait for some changes to land then

**Comment by dariocravero** [comment]
Any chance you can push those to a temp branch or something? :)

**Comment by nkbt** [comment]
@chenglou I was doing recently a lot of packaging work on https://github.com/ericelliott/prod-module-boilerplate https://github.com/ericelliott/universal-react-boilerplate and my personal bunch of react-*  modules (even made one https://github.com/nkbt/react-component-template to keep it lean and clear) . It all works really well, so I can tackle this one if you don't mind. You can assign it to me.

Should not take much time and will be done today (I'm in Sydney)

**Comment by chenglou** [comment]
Thanks for the offer! For the moment (until I write the actual readme, at least) I'll hold this off or otherwise lots of work would be redone =). Might check into your templates when I'm done with the rough API (soon).

**Comment by nkbt** [comment]
@chenglou oh sorry, was on a train and did not catch up with your comment. I've already done all things. Minimal code changes, though. Only infrastructure. Feel free to check it out and try new build/test process.

**Comment by nkbt** [comment]
@chenglou oh and it does not matter if you are going to change API soon, you still can publish 0.0.1 for now. And go 1.0.0 when API is fairly stable.

**Comment by chenglou** [comment]
Published =). Leaving this open to check off the checkboxes gradually

**Comment by chenglou** [comment]
Enough of these have been checked. Closing. We'll work on the rest gradually.
