### ISSUE TITLE
Sort order of keys

### ISSUE THREAD

**Issue by balanceiskey** [chenglou/react-motion#114]
Hey there,

I'm trying to understand how react-motion deals with objects and sorted keys and was hitting a bit of a roadblock. It seems react-motion depends on some combination of Babel's use of the spread operator and loose mode. Unfortunately I can't seem to maintain the expected sort order.

Here's a somewhat contrived example:

https://babeljs.io/repl/#?experimental=true&evaluate=true&loose=true&spec=false&code=let%20vals%20%3D%20{%2213%22%3A%20true%2C%20%2225%22%3A%20true}%3B%0A%0Aconst%20stiffnessAndDamping%20%3D%20[100%20%2C10]%3B%0A%0Alet%20userId%20%3D%20%2212%22%3B%0A%0A%20%20vals%20%3D%20{%0A%20%20%20%20%20%20...vals%2C%0A%20%20%20%20%20%20%0A%20%20%20%20%20%20[userId]%3A%20{%0A%20%20%20%20%20%20%20%20%20%20height%3A%20{%20val%3A%2070%2C%20config%3A%20stiffnessAndDamping%20}%2C%0A%20%20%20%20%20%20%20%20%20%20opacity%3A%20{%20val%3A%201%2C%20config%3A%20stiffnessAndDamping%20}%2C%0A%20%20%20%20%20%20%20%20%20%20padding%3A%20{%20val%3A%2010%2C%20config%3A%20stiffnessAndDamping%20}%0A%20%20%20%20%20%20}%0A%20%20}%3B%0A%20%20%0A%20%20console.log%28vals%29%3B%0A%20%20console.log%28Object.keys%28vals%29%29%3B%0A

Based on how items are added to the object, I expect the '12' key to show up last but that doesn't seem to be the case.

I imagine I'm missing something pretty straightforward, let me know if this might be something better suited for Babel's issues. 

Thanks!

**Comment by bsansouci** [comment]
Hey @balanceiskey! Looking at the [specs](http://www.ecma-international.org/ecma-262/6.0/index.html#sec-ordinary-object-internal-methods-and-internal-slots-ownpropertykeys) `integer` props are in ascending order but `String` props are in creation order. You can just append a letter at the front of your number and it works.

**Comment by balanceiskey** [comment]
WAT. You are totally right and this is absolutely terrifying. @chenglou maybe worth noting in the docs, not sure?

**Comment by chenglou** [comment]
Pretty terrifying for JS, yes. Here's a good answer: http://stackoverflow.com/a/30244410/960178
Fortunately yes, you can just add a letter to your key and it'll be guaranteed creation order. React itself relies on this externally and internally, e.g. http://facebook.github.io/react/docs/create-fragment.html

Sorry for not documenting this! I'll do it now. I had the impression I've put it somewhere. Thanks for reminding.
