### ISSUE TITLE
Actually stop rAF-ing when speeds reach zero

### ISSUE THREAD

**Issue by chenglou** [chenglou/react-motion#12]
Low-hanging fruit. Will write a separate method for traversing the current velocity tree and checking that everything's at zero.

(Future iteration: do transducers help here? A bit tired of reimplementing basic methods for trees).

**Comment by kenwheeler** [comment]
In my own implementations, I've checked if the Math.abs(velocity) is < 0.1 inside of the rAF method and returned if true, canceling the loop. By the time it gets that low, there is very little if any visual feedback that would be shown.

**Comment by chenglou** [comment]
You simply traverse the current velocity tree and check each leaf, right?

**Comment by kenwheeler** [comment]
I haven't done it with trees, so I would normally just check currV, but in a tree scenario, might want to Math.max the values and wait until the largest is below 0.1. This is of course contingent upon starting the frame back up on componentDidReceiveProps.

**Comment by chenglou** [comment]
I see. Btw the spring algorithm (`stepper.js`) already rounds the error to 0.001. We probably don't wanna make it 0.1? Since 0.1 concerns a nicer animation while stepper's 0.001 concerns just the incertitude in the number.

Or maybe we should just bump the error margin to 0.1.

**Comment by bsansouci** [comment]
I wouldn't change the stepper's error margin, I think it should stay broad just in case. But for checking if velocity is 0, I agree with @kenwheeler, <0.1 is good :+1:

**Comment by chenglou** [comment]
@kenwheeler master now fixes this, so closing.

I'm stopping at the exact value of `0`. Fortunately the actual spring algorithm already handles the error margin.

The library itself can't stop raf-ing at a bigger error margin than the algorithm itself. The reason is that the user might be using an `endValue` callback where it checks the current exact final position and start another animation. Related commit: https://github.com/chenglou/react-motion/commit/5a4cfa80f86f52abf5874ac6cbd2b82669d19821#diff-46a726b4ea0347d025bead8637578ac1R214

Of course, the user can decide to stop at a bigger error margin.

Hope that made sense, if not, feel free to ask for more clarification. I'll have to explain a few related bits in the readme soon anyways so I'd be nice to ensure everything's clear.

(And yes, you get chained animation practically for free, soon =))
