### ISSUE TITLE
Transition Question 

### ISSUE THREAD

**Issue by stephenotalora** [chenglou/react-motion#124]
Hi All, 

I want to be able to make an async call when a transition completes. 

Say for example when a react components completes the animation another component will take over the screen, but before then it will wait until the transition completes.

While I can inspect the interpolated value to reach 'endValue' and fire a call back on my own at that point, I was wondering if there is a cleaner way to do this. does the Spring component have any callbacks that I can bind to upon completing the transition?

**Comment by chenglou** [comment]
We don't currently expose a callback on transition end because we're afraid of abuses. What kind of async call is it in your situation? E.g. an ajax request?

**Comment by stephenotalora** [comment]
correct, I was thinking to make an ajax call. Say for example given the animation timeframe it has a beginning middle or end,  callbacks fire at each stage but I only register to one to make a call for the next batch of data.

Another example that came to mind could be as simple as synchronizing animations, say I have component A and component B, while component A is halfway its animation lifecycle component B starts animating (e.g. fading in etc...)

**Comment by chenglou** [comment]
For the first case, I'm still thinking about it. I don't think we'll be able to circumvent callbacks completely, but still thinking.

For the second case, you're talking about staggering/chained animation. Here's my default answer to it: https://github.com/chenglou/react-motion/blob/b1a7889c2a8b73a7456ccaf1973dd1b41d0fc64a/README.md#faq (first point). It's a bit opinionated right now but I do think it achieves better effect and with less hard-coded coordination. Think of it as "component A's animation spring is dragging component B's animation".

**Comment by chenglou** [comment]
Closing in favour of #235 =)

**Comment by stephenotalora** [comment]
Great thanks!
