### ISSUE TITLE
Transition appear

### ISSUE THREAD

**Issue by kristoferjoseph** [chenglou/react-motion#125]
What is the recommended way to add a transition on first render with TransitionSpring?

**Comment by chenglou** [comment]
`defaultValue` does it =).

**Comment by kristoferjoseph** [comment]
nope. :(

**Comment by chenglou** [comment]
Works from here. Yu can post your code here or come to Slack Reactiflux #react-motion channel: https://reactiflux.slack.com/messages/react-motion/.
