### ISSUE TITLE
New Spring API draft

### ISSUE THREAD

**Issue by chenglou** [chenglou/react-motion#129]
This only concerns animating a single spring for now. I need to prototype a bit more on the springs with dependencies (e.g. chat heads, where the destination of the second head is the current position of the first head) and TransitionSpring, but I think this new Spring is cool enough to stay even if the other solutions don't work out.
(props names are temporary. Not important right now)

`<Spring to={{top: 10, left: 20}}>Hi</Spring>`
That's your new basic spring. It renders to a `div` and transfers all the props. `to` is constrained to recognized CSS attributes (will provide injectable defaults for different platforms). Will intelligently _not_ interpolate non-interpolable/unrecognized attributes. A few major advantages:

- Does manual DOM manipulation under the hood and skips React's render (a-la Animated). Better perf and since this spring's a very common use-case, lots of potential perf boost here. Heck, screw all of this, let's just use Velocity.js or something under the hood =).

- Can interpolate from `height: auto;` by reaching into the DOM to set an initial value. #62

- Color interpolation (`color`, `backgroundColor`) comes for free without needing to expose a helper. Same for interpolating `"10%"` strings. #85

- Spring precision/error margin are implicitly configured; e.g. `left` will be rounded to integer and when the spring wobbling distance is around 1 px we'll stop right away because there's no point to keep going. #100. 

- Interpolating many springs: none of our business anymore. `map` through some random arrays and return your `Spring` with the desired configuration each time. This is not true for dependent springs. I'm still thinking of a clean API for that.

- No more vendor prefix, e.g. if you provide `transition`, we'll add `WebkitTransition` for you under the hood.

To configure the spring stiffness and damping:
`<Spring to={{top: config(10, 120, 17), left: 20}}>Hi</Spring>`
120 being stiffness and 17 being damping. Function params format subject to change depending on what's concise and clear. If every attribute has the same config, we could accept a `config` prop on the spring itself for convenience.
What the return value of `config(10, 120, 17)` is doesn't matter. You don't really read into the anyway. This also kills the special `config: []` to signal that you want to jump to the final value straight away. We could provide a clearer `stop(destValue)` instead. Again, name and signature subject to change.

An `initial` prop is exposed (equivalent of `defaultValue` right now).

As you can see, it's not _that_ much of a departure from the current basic Spring API: you were probably already using something similar. I'm having a bit of trouble figuring out how the perf that comes from skipping render will cooperate with dependent springs or TransitionSpring (seems like with a child-function you kind of have to re-render the wrapper every time), brainstorming welcome.

**Comment by borisyankov** [comment]
top: config(10, 120, 17) looks a bit funny. Don't necessarily like the way it looks, and that the main value does gets thrown with the rest.

What about keeping the to={} always pure, and have an optional config={} that contains all the custom configs?

Something like config={{to: [120, 17] }}

**Comment by chenglou** [comment]
It's still pure either way. And yes, I've thought about that. I'm not sure if it has a parallel with TransitionSpring (you can't provide an independent config since you don't know what the current set of keys are... there are ways around this though). I'll consider it.

**Comment by borisyankov** [comment]
I meant pure in some 'new-edgy' way, not the functional programming mean ;)

**Comment by nkbt** [comment]
Everything seems quite reasonable as for me. I'd avoid additional function `config(x,y,z)` and just pass an array instead: `top: [10, 120, 17]`, which makes it somewhat similar to `.eslintrc`

**Comment by chenglou** [comment]
I want to reserve `[10, 120, 17]` for chained animation (there, I've said it). So maybe something else instead?

**Comment by chenglou** [comment]
Here's the draft format for `transform`, which is probably what you'd use 50% of the time:
`<Spring to={transform: {translate3d: [10, 5, 0]}} />`
Feels much better than weird string concatenation/interpolation imo.

**Comment by chenglou** [comment]
There's a slight problem with the new API. In the past, the event handlers could do this:

```jsx
<Spring endValue={{x: {val: 5}}}>{({x}) => <div onClick={this.handleClick.bind(null, x.val)} />} />}</Spring>
```

On click ,it'll call the handler and pass the currently interpolating value. Can't in this new model since you can't get hold of that very value.

Three solutions:

1. The primary case of this is for drag and drop. I use it in lots of demos. So we should just have better drag and drop. I haven't checked into react-dnd yet.

2. We proxy all the related events internally like so: `<div onClick={(...args) => this.props.onClick(...args, this.state.currentValue)}`.

3. For these cases, we still allow children function. We pass you the interpolated `to` and you can get hold of it, do something with it, then pass it along to your `div` (need to turn `transform` back into a string).

Supporting 3 means we won't be able to do the manual style setting perf optimization anymore. Back to raf + render.

**Comment by threepointone** [comment]
alternately, maybe you special case drag and drop? <Div draggable={/* true or options object*/}/> (inspiration from framer, really. might just be pragmatic enough, and actually achieve what the html5 draggable css spec set out to do))

**Comment by chenglou** [comment]
So you're going with option 1? In that case, we'd need to list all the common usages of getting hold of the interpolated value. I don't want to special case drag and drop then realize there this other usage I didn't think of, and then end up with either solution 2 or 3 anyways.

(Btw, just tested 2. Works)

**Comment by threepointone** [comment]
Just exploring/ giving options. But saying that the new api already looks like a special <div/>, and draggable has a spec of sorts. 

No 2. should happen in any case. :+1: No. 3 also should be doable, really.

**Comment by jdeal** [comment]
@chenglou What about controlling the precision on something that isn't pixel-based? For example, an opacity-based animation currently has that fall-off problem where react-motion takes forever to reach 0. The element is basically invisible, but it keeps animating anyway.

FWIW, awesome work though!!! This one tiny edge has been the only rough spot for me.

**Comment by chenglou** [comment]
That example of height with pixel is really just an example. Internally we'll check the property name and do the correct precision rounding. For opacity it's, say, 2 digits.

**Comment by jdeal** [comment]
Ah, cool, thanks!

**Comment by daniel-gustafsson** [comment]
Looks like a very nice simple to use spring API.

May I suggest added support for choosing the element type instead of div inside the spring? Could be something like this for render():

```
  render() {
    const {to, onMouseDown, onTouchStart, factory, ...rest} = this.props;
    return (factory || React.DOM.div)(
    {
      ref: "comp",
      onMouseDown: (...args) => onMouseDown && onMouseDown(...args, this.curr),
      onTouchStart: (...args) => onTouchStart && onTouchStart(...args, this.curr),
      ...rest
    });
  }
```

And then you could optionally pass a factory like for example <Spring factory={React.DOM.tr}</Spring> if you want to say animate the background color of a tr on hover.

Custom element support would require an additional mechanism to get the ref of the actual element to animate.

**Comment by chenglou** [comment]
I was afraid this'd come up. Yeah, it's additional API surface for not much return. `div` can substitute most element (sometimes with a bit of css) and beside e.g. tr background there's nothing much to animate for a tr anyway? I'll think about it.

**Comment by threepointone** [comment]
counter - `<Spring component={View}/>` will mean we can do react-native, -canvas, etc etc.

**Comment by daniel-gustafsson** [comment]
I of course respect if you think it is a bad idea.

I do like the power of the old spring and will miss it if it will go away entirely. Not sure if that is the intention? Maybe I should just wait and see how the new API ends up :)

**Comment by chenglou** [comment]
API's landed since a while now. A few niceties e.g. transform shorthand might be implemented in the future. But for now we're good. Closing!
