### ISSUE TITLE
Unsure of syntax when using CJSX

### ISSUE THREAD

**Issue by marclar** [chenglou/react-motion#135]
I'm trying to copy [Demo 8](https://github.com/chenglou/react-motion/blob/master/demos/demo8/Demo.jsx), but my project uses coffeescript and cjsx.

I think it's close to working, but this bit in particular throws an error:

```
<Spring endValue={endValue}>
   {items =>
        <div className="demo8">
            {items.map(({scale, shadow, y}, n) =>
                <div
                    key={n}
                    className="demo8-item"
                    onMouseDown={@handleMouseDown.bind(null, n, y.val)}
                    onTouchStart={@handleTouchStart.bind(null, n, y.val)}
                    style={{
                        boxShadow: "rgba(0, 0, 0, 0.2) 0px ${shadow.val}px ${2 * shadow.val}px 0px",
                        transform: "translate3d(0, ${y.val}px, 0) scale(${scale.val})",
                        WebkitTransform: "translate3d(0, ${y.val}px, 0) scale(${scale.val})",
                        zIndex: (if n is lastPressed then 99 else n)
                    }}>
                        {order.indexOf(n) + 1}
                </div>
            )}
        </div>
    }
</Spring>
```

I'm not sure how `{items =>` functions; I'm not too familiar with ES6, but I get `items is not defined` when I run this code.

Any ideas? Thanks so much. Beautiful library, btw :)

**Comment by chenglou** [comment]
That's the `children` prop which in this case accepts a callback. The ES5 version would be `<B>{function(items) {return ...}}</B>`. That syntax in CJSX should have worked?

**Comment by marclar** [comment]
Thanks, @chenglou -- I think all I needed to do was to change

`{items =>`

to 

`{(items) =>`

I still don't have it working exactly like the demo, but now the page renders and it seems I can reorder things.

Thanks!

**Comment by chenglou** [comment]
Ah that's right, CoffeeScript has mandatory parens for a single argument... Alright. We're all active on Slack so feel free to post questions there too.

**Comment by marclar** [comment]
Cool -- thank you.
