### ISSUE TITLE
Demo 8 only accommodates 4 items

### ISSUE THREAD

**Issue by marclar** [chenglou/react-motion#136]
After having some difficulty with a dynamic list of items, I cloned the repo and edited Demo 8.

I changed `range(4)` to `range(8)` and I see the same behavior.

If you drag one of the items near the end of the list, it can only be moved to the 4th spot (not the 5th, 6th, 7th or 8th.)

Any ideas?

P.S. I would have asked in the Slack room, but I'm not sure if I need to be invited first. I just tried signing in with my existing account, but no luck.

Thanks!

**Comment by johnamiahford** [comment]
Hey @marclar, you can sign up here <http://www.reactiflux.com/> and find #react-motion in the channels list!

**Comment by chenglou** [comment]
Yeah the "invite" message is super misleading. It's nothing but a sign up page.

@marclar I've pushed a new commit that shows what you had to change: https://github.com/chenglou/react-motion/commit/4bde5cd03a2e03c299fe2d74d02b7410f6273470#diff-a5c97fa5065182ffc820c58359237cd5R60

It works now. Feel free to play around with it =). Thanks for pointing it out!
If you're wondering how this works then ask here or in Slack.
