### ISSUE TITLE
Is it possible to animate the mounting of a component?

### ISSUE THREAD

**Issue by wilfreddenton** [chenglou/react-motion#137]
For example, in this [demo](https://cdn.rawgit.com/chenglou/react-motion/e8f42dcd9678a8cea8648a3cf4f994583a99e7f7/demos/demo3/index.html), is it possible to have the listview animate when it's mounted in the same way that searching "asdf" and then "" animates the view? This would be useful for when a listview is toggleable.

**Comment by threepointone** [comment]
Total guess, but should be possible by starting with 0 items, and then adding them in after a setTimeout(fn, 0)?

**Comment by souporserious** [comment]
Yes, just provide a defaultValue and then whatever you want your endValue to be. You can see a working example here: http://codepen.io/souporserious/pen/dde7064750f523bfa934da2d6e201af4?editors=001

**Comment by chenglou** [comment]
^ Yep!
