### ISSUE TITLE
Question: how to tell when an animation is finished?

### ISSUE THREAD

**Issue by alexreardon** [chenglou/react-motion#139]
Is there any way currently to determine when an animation is completely finished?

**Comment by chenglou** [comment]
Right now if you're using a non-wobbly spring, you can check for the current value passed to you by the children function. In other cases probably have the current velocity passed to you too.

I'm planning to expose such a boolean in the future.

**Comment by alexreardon** [comment]
`willEnter ` or `willLeave`?

**Comment by chenglou** [comment]
Yep, check `currentSpeed`, passed at last in both callbacks.

**Comment by alexreardon** [comment]
I am struggling to figure out how to use the callbacks to let my app know that the animation is finished. Would you mind posting a simple example?

**Comment by chenglou** [comment]
As in, you can do a simple `if` check inside `willLeave` for the currentSpeed value. The structure of currentSpeed is similar to that of endValue you provided. You can console log it and check it.
It's a hacky though. I'll provide hooks in the future.

**Comment by alexcurtis** [comment]
@chenglou is willLeave available on a Spring? -- I couldn't see it in the source. Like you mentioned, it would be great to have a bool / callback to simplify this down.

**Comment by chenglou** [comment]
Nope, `willLeave` doesn't mean what you think it means in this case. There's no component leaving for  Spring.

**Comment by webyak** [comment]
+1 for hooks.

**Comment by chenglou** [comment]
Closing for #235. Will be implemented soon.
