### ISSUE TITLE
Justifications for the current API's implementation

### ISSUE THREAD

**Issue by chenglou** [chenglou/react-motion#14]
In conjunction with #9's point 2.2.2, this issue will explain the current API in detail. `TransitionSpring` (for unmounting) deserves its own issue later. **Warning**: this is the conceptual API for clarity purpose. Actual implementation might slightly differ.

The overall initial API looked like this:
```jsx
<Spring destinationValue={{
  a: {top: 1},
  b: {top: 2},
}}>
  {({a, b}) =>
    <div>
      <div style={a}>a</div>
      <div style={b}>b</div>
    </div>
  )}
</Spring>
```

(This is one of the only few viable solutions I've found that respect the criteria I've listed in #9. Another is @sahrens', which should be 1.2.2. in that issue.)

The object passed to `destinationValue` is an arbitrary data structure (at least for the normal `Spring` and not `TransitionSpring`.

`Spring` will drill down into the data structure and animate each number, from whatever the current value was, at that position of the collection. **This assumes your previous `destinationValue` and the next one have the same shape**. Under the hood, there's also another tree of the same shape: the velocity tree (initialized to all 0 at the beginning). Current position, current velocity, destination position, stiffness and damping together allow you to calculate the next position (which becomes the new current position) and the next velocity.

But it's a bit constraining not able to specify different spring constants (stiffness + damping) for different numbers. Here's the solution we've found:

```jsx
<Spring destinationValue={{
  a: {top: {value: 1, springConfig: {stiffness: 10, damping: 5}}},
  b: {top: {value: 2, springConfig: {stiffness: 20, damping: 4}}}
}}>
  {({a, b}) =>
    <div>
      <div style={{top: a.top.value}}>a</div>
      <div style={{top: b.top.value}}>b</div>
    </div>
  )}
</Spring>
```

Now, `destValue` and `springConfig` become restricted, special key names for this library. When it drills down the collection, it will skip animating `springConfig` subcollection (naturally) and animate each `destValue` according to the `springConfig` constants provided on the side. For declarativity, the constants carries over to the whole subcollection, until another `springConfig` overrides it. **For convenience, a `stiffness` or `damping` of -1 cancels the animation for the subcollection (so overrides the upper level configs)**.

This gets verbose, so a stiffness of 170 and damping of 26 is set. These two constants gives you a non-bouncing spring (similar to an ease-in curve), which gently decelerates to destination without overshooting. For one, it gets annoying if things bounces all the time. For two, for unmounting, it's easier for users to check the destination's reached with `currentPos === destPos` instead of `currentPos === destPos && currentSpeed === 0`.

But the remaining bits still leave things tedious. It would be nice to be able to write:

```jsx
<Spring destinationValue={{
  a: {top: update(1, 10, 5)},
  b: {top: update(2, 20, 4)},
}}>
  {({a, b}) =>
    <div>
      <div style={a}>a</div>
      <div style={b}>b</div>
    </div>
  )}
</Spring>
```

This is actually the current API.

What's happening here? The `update` function is actually nothing but a wrapper:
```jx
function update(val, config) {
  return {
    value: val,
    springConfig: config || {stiffness: 170, damping: 26},
  };
}
```

The received interpolated structure, however, is `{a: {top: someValue}, b: {top: someValue}}`. The wrapper `{val: ..., springConfig: ...}` is gone! Internally, Spring received `destinationValue` and apply the correct interpolation against `currentVlaue`, **stripping away** the `update` wrapper. This gives you the magical feeling of visually marking a collection and letting Spring know what to interpolate, while seemingly receiving a collection with the "same" **visual** (as in, looking at the code) shape back.

Here's how the `update` magic fares vs no magic:

- `update`
  + pros
    * hides boilerplate, a lot of it.
    * `update` only makes sense for marking `destinationValue`. It's not clear why you'd want to expose some wrapping/marking detail to the received interpolated value/velocity (maybe exposed in the future).  restricts usage places to dest (not rly if you use it in default val)
  + cons
    * error-prone. Let's say we want to animate one of the `[x, y]` in a list of `[x, y]`s: `numbers.map(n => someCondition ? [n, n] : update([n, n]))`. We intentionally gave an impression that the `update` marker's an invisible thing, but here you've accidentally returned a non-homogeneous collection: `let x = update([1, 2, 3]); let values = [...x, 4] // throws`. Alternatively, you could have done the less error-prone `numbers.map(n => update([n, n], someCondition ? {stiffness: -1, damping: -1} : null)` (`-1 -1` disables the tweening of values as a handy shorthand). Not sure.
    * kills the assumption that all three trees (current values, current speeds, destination values) are of the same shape. The shape of the latter might vary greatly depending on when you feel like putting the `update` marker.

- Expose `{val: ..., springConfig: ...}` directly
  + pros
    * No magic. In the interpolated values in the children callback, you get back the tree with the above wrapper. The speed tree (when we expose it in the future) also has the same shape.
  + cons
    * boilerplate-y.

We might want to switch to the latter.

**Comment by chenglou** [comment]
@kenwheeler seems like you're already using this, so pinging you in case you're interested.

**Comment by kenwheeler** [comment]
@chenglou A lot of the time I can see people just using the non-function style `endValue` syntax for things like `left` or `opacity`, like in /demo0 , but I can absolutely see the value of the `update` syntax in a multiple-element, multiple-property scenario. As soon as I recognized how the 'children as a function' syntax worked, it all became very clear.

**Comment by kenwheeler** [comment]
That said, in what scenario would you feed non tweenable data, like `importantData` in the demo, through the update function?

**Comment by bsansouci** [comment]
I think it becomes useful in the TransitionSpring which @chenglou said would be discussed in another issue. But basically when you're unmounting, the `TransitionSpring` will keep your data until you decide it can be removed, then it's removed. Looking at demo3, when you delete something from the list you're removing it from your state. If you don't give it to the `TransitionSpring` to keep, you won't have the text of that todo to display.

**Comment by bsansouci** [comment]
Also `update` enables you to have different spring values on different parts of your tree.

**Comment by chenglou** [comment]
> @chenglou A lot of the time I can see people just using the non-function style endValue syntax for things like left or opacity, like in /demo0

Random comment: the current situation is, if you pass an object instead of a callback, I assume you want to animate everything, so I wrap your object with `() => update(object, defaultConfig)` before sending it off. This is handy for scalars too: `<Spring destinationValue={5}>...` which turns into `Spring destinationValue={() => update(5)}>...` With the planned change to use vanilla object, you can no longer use the shorthand: say you have `<Spring destinationValue={{a: {top: {val: 1}, left: 10}}}`. I can't assume you wanted `left` animated too by wrapping the whole thing in another wrapper.

It's slightly more verbose but that's fine?

> That said, in what scenario would you feed non tweenable data, like importantData in the demo, through the update function?

Not sure what you mean here. If you mean that the user should only ever pass tweenable data to `destinationValue`, I feel it's too restrictive and asks too much of you to massage your data before passing it to me. If you mean that someone does `update(nonTweenableData, cancelConfig)`, that's because the upper level might wrap the whole structure in a config, and for this `nonTweenableData` sub collection you want to `un-wrap` by setting a special `cancelConfig`. This is for convenience.

But you touch a good point: right now we assume `update({a: {b: 1}, c: 2}, config)` cascades deeply and updates `1` and `2`. if `update` didn't cascade, you wouldn't need a second API/special config to disable an `update` from the higher level. I made things cascade because it seemed tedious to wrap every single value you want to tween with a non-cascading version of `update`. But maybe that's the way to go? This decision will also affect the second vanilla API.

**Comment by kenwheeler** [comment]
@chenglou on the first part, agreed, slightly more verbose, but consistent and explicit.

on the second part, I definitely see the value in the cascade in regards to keeping things terse.

**Comment by chenglou** [comment]
Right, maybe I worried too much, but it _does_ feel a bit tedious to do this:

```jsx
<Spring destinationValue={{value: [{a: {top: 1, text: {value: 'hi', config: [-1, -1]}}}]}}>
```

Where `[-1, -1]` is the signal to disable tweening `text`. Or maybe this is slightly better:

```jsx
<Spring destinationValue={{value: [{a: {top: 1, text: {staticValue: 'hi'}}}]}}>
```

**Comment by kenwheeler** [comment]
`staticValue` actually cleans that up tremendously

**Comment by chenglou** [comment]
It's less clear that it cascades too, though... Anyways, I'll make sure the `config: [-1, -1]` works first. If necessarily I'll look into `staticValue`.

**Comment by chenglou** [comment]
Closed because not an issue. But will always welcome questioning of the general API here!
