### ISSUE TITLE
Expose some dev-time util for getting a duration estimation

### ISSUE THREAD

**Issue by chenglou** [chenglou/react-motion#142]
I'm still against hard-coded duration, and RM likely won't expose a spring where the user specifies one of `{stiffness, damping}`, and the spring gives the other, given a determined duration. The moment we do that, interruptible animation becomes unsolved again.

For the people who wanted to have a feel of how long a spring lasts, I've directed to https://cdn.rawgit.com/chenglou/react-motion/e8f42dcd9678a8cea8648a3cf4f994583a99e7f7/demos/demo5/index.html
There might be a potential counter-argument (though so far I haven't heard of it; but just in case...) that this is "imprecise". Except the duration is also most of the time very arbitrary and based on a "feel". At least here, it respects the laws of physics.

That being said, I might consider exposing a dev-time only util which accomplishes what I said in the first paragraph, or more (e.g. "what's a faster spring that looks like this one?). A typical workflow would be to `console.log` the output of these... or integrate this into the new React devtools.

@threepointone

**Comment by steida** [comment]
The demo is broken. It's impossible to set any reliable duration, since some easings seems to be broken. I really don't understant what you mean is wrong with animation duration. Duration is ok.

**Comment by chenglou** [comment]
Seems to work fine from here. What's broken?

**Comment by steida** [comment]
I just set some dragger to low value, and first column is invisible a second is animating forever. Anyway, we need duration. There is nothing wrong with initial duration value.

**Comment by chenglou** [comment]
That's the intended behaviour of the demo. First column is invisible because it's wobbling too hard and second column too. You've probably hit a negative configuration. They're a few numbers smaller than whatever you're manipulating (likewise the following columns are a few numbers bigger than your current cell). There's no reason to hide the undefined behaviour when you set e.g. a negative damping.

Duration makes interruptible animation complicated.

**Comment by steida** [comment]
Why? It's just definition how long bare animation should play, and right implementation can hook on any step.

**Comment by steida** [comment]
I am really missing point of something or idk.

**Comment by chenglou** [comment]
It's not about being able to hook into any step/frame. What do you do with an e.g. ease-out animation interrupted halfway? Given whatever info you currently have.

**Comment by steida** [comment]
Play the same animation backward.

**Comment by chenglou** [comment]
It's interrupted because you want to go to a new destination. Are you saying you reverse the equation? That'll become an ease-in (sorta) and only works with ease-out in the case you're talking about.

**Comment by sairion** [comment]
I can understand the argument, but it is still hard to estimate how `{stiffness, damping}` value would work for my own transition/animations. I think demo 5 can be much improved to visualize result if parameters can be customized with some UI provided.

**Comment by chenglou** [comment]
Closing in favor of #265 (new feature coming)
