### ISSUE TITLE
TransitionSpring elements don't leave and enter when replaced, unique keys not working

### ISSUE THREAD

**Issue by yotamDvir** [chenglou/react-motion#151]
I have a TransitionSpring wrapping a list, whose elements get replaced using [redux](http://rackt.github.io/). I gave elements unique keys, and still elements only enter or leave to accommodate for a change in their numbers. That is, if there were two elements before, and now there are three, the third element will enter, but the other two will just get their contents replaced instead of the prior ones leaving and the new ones entering. This is important because I need the animation to trigger.
In chrome's inspector I can actually see the keys change (the `data-reactid` attribute in the contained `li` element) instead of the whole tag being replaced with a new one.
Also, I do get a 
> Warning: Each child in an array or iterator should have a unique "key" prop. Check the render method of TransitionSpring. See https://fb.me/react-warning-keys for more information.

in the console, which I don't understand, since I see the keys.

Below is the problematic render code.
```javascript
render: function () {
	var p = this.props;
	return (
		<TransitionSpring
			endValue={this.getEndValue()}
			willEnter={this.willEnter}
			willLeave={this.willLeave}
		>
		{function (motionVals) {
			return (
				<ol className="potential">
					{Object.keys(motionVals).map(function (ind, garbage) {
						return (
							<Heir
								name={motionVals[ind].text}
								onGo={p.onGo}
								opacity={motionVals[ind].opacity.val}
								leftTrans={motionVals[ind].leftTrans.val}
								key={motionVals[ind].text} // Unique keys.
							/>
						);
					})}
				</ol>
			);
		}}
		</TransitionSpring>
	);
}
```

**Comment by chenglou** [comment]
What does your `getEndValue` look like? Also, see here: https://github.com/chenglou/react-motion#little-extras. Don't use numbers as your keys.

**Comment by yotamDvir** [comment]
```javascript
getEndValue: function () {
		// Have to convert to object for compliance with
		// react-motion. The `heirs` property holds a list of strings.
		var endVals = {};
		this.props.heirs.map(function (str, i) {
			return {
				opacity: {val: 1, config: presets.stiff},
				leftTrans: {val: 0, config: presets.stiff},
				text: str
			};
		}).forEach(function (obj, i) {
			endVals[i] = obj;
		});
		return endVals;
	}
```
Also, I just use the `text` property for the id, which aren't numbers...

**Comment by yotamDvir** [comment]
Somehow works now. Since this post I've made a change in my app to ImmutableJS that broke some functionality, among which was changing all the element keys to `true`. After I fixed it so the id's are back to normal, the problem disappeared. Still don't know why it works though... Will update if I find out - for now I'm closing the issue.
Thanks!
