### ISSUE TITLE
Need a test reporter with visual diffing

### ISSUE THREAD

**Issue by chenglou** [chenglou/react-motion#155]
@nkbt 
Comparing a collection with another one is a bit tedious and looks like this currently:
![screenshot 2015-09-13 17 42 55](https://cloud.githubusercontent.com/assets/1909539/9839155/e0d2d402-5a3e-11e5-8ef8-9b812684dd36.png)
Ideally we'd have a visual diff of the collection. But I kinda don't want to lose the nyan cat (yeah really) lol, is there something we could do here?

**Comment by nkbt** [comment]
Yeah, I found it quite not fun for myself either recently but did not have a chance to look at the solution.

**Comment by nkbt** [comment]
Fixed by #194
