### ISSUE TITLE
Refactor demo1 to use <Motion>

### ISSUE THREAD

**Issue by aputinski** [chenglou/react-motion#156]
I attempted to refactor demo1 (chat heads) to use the new `<Motion />` component, but it looks like interpolating an array of values is no longer supported? Also, couldn't figure out how to get the previous interpolated value.

**Comment by chenglou** [comment]
That's actually what I'm doing next =). Hopefully you didn't miss the warning in the readme? I'll bold it to make sure people don't miss it.

Leaving this open until I finish the refactor!

**Comment by aputinski** [comment]
Thanks! Are you referring to using integers as the object keys? If so, I did in fact miss that part.

**Comment by chenglou** [comment]
Oh no (although I should highlight that part too...), just the warning that the repo's going through refactoring and I temporarily dropped support for the staggered springs that you wanted. I'm putting it back soon.

**Comment by chenglou** [comment]
To be more precise and for future reference: interpolating an array of styles, without accessing the previous value, won't be supported anymore. You can just create an array of `Motion` instead. Same thing.

Interpolating an array of styles, where each style depend on some other (thus requiring the access of previous style), is what I'm working on restoring right now.

**Comment by chenglou** [comment]
Update: it's back =).

**Comment by aputinski** [comment]
Thanks! Really appreciate it. This library is awesome.
