### ISSUE TITLE
Put debug mode in the new react devtools

### ISSUE THREAD

**Issue by chenglou** [chenglou/react-motion#158]
Once it becomes extensible, we can bring the slowmo, [parameters chooser](https://cdn.rawgit.com/chenglou/react-motion/e8f42dcd9678a8cea8648a3cf4f994583a99e7f7/demos/demo5/index.html) and even onion skin into the devtools.

**Comment by gaearon** [comment]
Anywhere I can read on extensibility plans?

**Comment by chenglou** [comment]
Inside @jaredly's head maybe? =)

**Comment by gaearon** [comment]
That's what I thought!

**Comment by jaredly** [comment]
Haha sorry about that. I'll put a gist together w/ my plans. The [relay plugin PR](https://github.com/facebook/react-devtools/pull/200/files) makes some of the changes needed to have a reasonable plugin system.
My current plan is to have any plugins live inside the react-devtools repo, b/c co-versioning multiple chrome extensions sounds like a nightmare :(

**Comment by chenglou** [comment]
Man I wish I was paid to work on this. Closing for now. Will still keep this in mind!
