### ISSUE TITLE
Issues with initialisation 

### ISSUE THREAD

**Issue by rbsmidt** [chenglou/react-motion#159]
Hello
I've been trying to get started with React Motion. I'm having some issues though. I'm hoping someone in here can explain how to init react motion correctly.

I'm using webpack with babel-loader to compile my JS, and installed React and React Motion via npm. I've been trying with different init commands:

1)
```
import React from "react";
import { Motion, spring } from "react-motion";
```
2)
```
import React from "react";
const { Motion, spring } = "react-motion";
```
3)
```
var React = require("react");
var { Motion, spring } = "react-motion";
```

All three methods declare React correctly, but Motion and spring remains "undefined", when trying to use og console.log them. I've tried with Spring instead of spring, but with same result.
I'm quite new to webpack and babel-loader, so my guess is, i'm mixing some syntax or other logic. However i've even tried copying init methods of some of your demos. Still same result.

I'm hoping that someone can guide me in the right direction?

Best regards

**Comment by chenglou** [comment]
Hey, the master's using an experimental API. I've put up a new REAME in the demos folder to clarify that. Thanks!

**Comment by chenglou** [comment]
Convenient link: https://github.com/chenglou/react-motion/tree/f53ec099dca159e23fc4ed1b656bb5555c166da1/demos

So tldr: you've probably installed 0.2.7 and are checking out github's demos

**Comment by rbsmidt** [comment]
Ahh that would explain! Thanks a lot for your fast reply. So just to be sure, v 0.2.7 is the latest stable release, and also the one exposed when running npm install react-motion, right?

Again thank you for assistance, i'm looking forward to get started with the lib!

**Comment by chenglou** [comment]
Yep =). You can check `node_modules/react-motion/package.json` to be sure.

**Comment by skosch** [comment]
Hey, I'd love to make something similar to Demo 8 (the drag&drop list). What's the old equivalent of `scale: spring(1.1, springConfig)`?

**Comment by chenglou** [comment]
New version is releasing in a couple of minutes actually.
https://github.com/chenglou/react-motion/wiki/v0.3.0-examples

**Comment by skosch** [comment]
Sweeeet! :)

**Comment by chenglou** [comment]
(Released and forgot to ping, sry)

**Comment by skosch** [comment]
No worries, I pulled it right away. It's working beautifully, and the example was very helpful. Thanks a ton!
