### ISSUE TITLE
Chinese Support （来个中文的文档呗）

### ISSUE THREAD

**Issue by luqin** [chenglou/react-motion#16]

**Comment by chenglou** [comment]
I'm not even done with the english readme yet. Even when I'm done I'm not sure if I'll ever start and maintain a chinese doc myself. Maybe someone else will do it. Low-pri for now =)

**Comment by gaearon** [comment]
Hehe. https://github.com/gaearon/redux/issues/158

**Comment by chenglou** [comment]
Gonna close this for now since there's not much actionable here =)

**Comment by luqin** [comment]
好的

**Comment by 97Yates05** [comment]
水平不行，要不然真想翻译翻译，挺好的库，本来上手难度就挺高，没有中文就更抓瞎了
