### ISSUE TITLE
Uncaught TypeError: Cannot read property 'scale' of undefined

### ISSUE THREAD

**Issue by APPLLEJN** [chenglou/react-motion#160]
I copy the demo8 code, but he has a mistake.
Uncaught TypeError: Cannot read property 'scale' of undefined
![react-motion](https://cloud.githubusercontent.com/assets/12135227/9895644/6374a6c0-5c64-11e5-9fda-90a8b31028e7.png)

**Comment by chenglou** [comment]
Hi, can you be more precise? With version of react-motion are you using? And which version of the demo code?

**Comment by APPLLEJN** [comment]
the version is  0.2.7, is the defaultValue required?

**Comment by chenglou** [comment]
No it's not. Is it possible to see your code?

**Comment by APPLLEJN** [comment]
thank you, I have fixed this bug...is my mistake

**Comment by APPLLEJN** [comment]
thank you, I have fixed this bug...is my mistake

**Comment by chenglou** [comment]
:+1:
