### ISSUE TITLE
Event handlers within children stop functioning

### ISSUE THREAD

**Issue by mrtnbroder** [chenglou/react-motion#161]
I'm having a weird issue when using `TransitionSpring`, where any event handlers I setup, stop working (e.g. `onClick={this.whatEverFunction}`).

These are my components: https://gist.github.com/mrtnbroder/a21217cd9ddbae6fdfec

Notice that my `onClick={this.handleOverlayClick}` doesn't work, *UNLESS* its transitioning(*!*), which is really weird. So lets say I trigger the modal, the transition kicks in and WHILE its transitioning, when I click on the overlay, the event fires. When the transition is over however, it stops working.

Any ideas?

**Comment by PetrGlad** [comment]
I have possibly related problem: some components inside Spring do not re-render after .setState.
So component state is updated from an event handler but it does not trigger rendering.

Also ReactJS (0.13.3) complains about Spring:
```
Warning: Don't set .props.children of the React component. Instead, specify the correct value when initially creating the element or use React.cloneElement to make a new element with updated props. The element was created by Spring.
```

**Comment by Eptis** [comment]
Don't know if its the same, but on react 0.14 some handlers of mine only fire until the animation has finished + 1. This means the UI is unresponsive during the animation

**Comment by nkbt** [comment]
I have no problem with event handlers, they work pretty good while animating. I am pretty sure there is something to do with the program structure. 

See example at http://nkbt.github.io/react-collapse/example/

**Comment by Eptis** [comment]
My bad, this can be closed. It was a problem with the z-index of the element, it was layed on top but was not visible.

**Comment by chenglou** [comment]
:+1:
