### ISSUE TITLE
Question: why not use x = restX + maxX*sin(sqrt(k/m)+sqrt(k/m)

### ISSUE THREAD

**Issue by jasonHzq** [chenglou/react-motion#163]
why not caculate position using x = restX + maxX*sin(sqrt(k/m)+sqrt(k/m)? It only relate to t,you may not use a fixed frame time.

**Comment by chenglou** [comment]
Didn't have time to look at this. Why is this closed? (Also, we used some logic to make sure we loop the correct amount of times even with a fixed frame time)
