### ISSUE TITLE
`willEnter` and `willLeave` not firing

### ISSUE THREAD

**Issue by kendagriff** [chenglou/react-motion#164]
Am I understanding correctly that `willEnter` should fire upon mount, and `willLeave` will begin firing upon unmount?

I'm testing `TransitionSpring`, and I cannot get either to fire. Here's a short snippet...

```js
  ...
  render: function() {
    return (
      <div className={this.props.className} onClick={this.props._onClick}>
        <TransitionSpring
          endValue={this.endValue()}
          willEnter={this.willEnter}
          willLeave={this.willLeave}>
          {function(currentValue) {
            return ...;
          }.bind(this)}
        </TransitionSpring>
      </div>
    );
```

I'm debugging both the `willEnter` and `willLeave` functions, and neither get kicked off.

**Comment by chenglou** [comment]
What does your `endValue()` look like? Don't forget that `willLeave` fires when the return value from `endValue()` is missing a key that previously existed in the previous `endValue()`. Same for `willEnter`.

**Comment by kendagriff** [comment]
Ah, that must be it. I'll check that out stat. Thank you!!!

**Comment by chenglou** [comment]
Which part of the README wasn't clear enough? I need to improve it.

**Comment by kendagriff** [comment]
From my perspective – having come from React's TransitionGroup – it wasn't immediately clear to me that Spring was not also responsible for unmounting. After digging through Issues on the Github repo, I indirectly discovered that wasn't the case – that the interpolations didn't simply work backwards (duh).

So, I turned to `TransitionSpring` assuming I'd find the answer. The docs dive right into an example (and a complicated one, at that) of how to use the component, but have little to say about _why_ or _what_ it's used for.

Other than that, it's a nicely done example with plenty of explanations on the handlers.

**Comment by chenglou** [comment]
By complicated example, you mean the TodoMVC one?

**Comment by kendagriff** [comment]
This part struck me as dense for a minimum viable TransitionSpring implementation. After reading it about six or seven times, it began coming together ;)

```
let Demo = React.createClass({
  getInitialState() {
    return {
      blocks: {
        a: 'I am a',
        b: 'I am b',
        c: 'I am c',
      },
    };
  },

  getEndValue() {
    let blocks = this.state.blocks;
    let configs = {};
    Object.keys(blocks).forEach(key => {
      configs[key] = {
        height: {val: 50},
        opacity: {val: 1},
        text: blocks[key], // interpolate the above 2 fields only
      };
    });
    return configs;
  },

  willEnter(key) {
    return {
      height: {val: 50},
      opacity: {val: 1},
      text: this.state.blocks[key],
    };
  },

  willLeave(key, value, endValue, currentValue, currentSpeed) {
    // the key with this value is truly killed when the values reaches destination
    return {
      height: {val: 0},
      opacity: {val: 0},
      text: currentValue[key].text,
    };
  },

  handleClick(key) {
    let {...newBlocks} = this.state.blocks;
    delete newBlocks[key];
    this.setState({blocks: newBlocks});
  },

  render() {
    return (
      <TransitionSpring
        endValue={this.getEndValue()}
        willEnter={this.willEnter}
        willLeave={this.willLeave}>
        {currentValue =>
          <div>
            {Object.keys(currentValue).map(key => {
              let style = {
                height: currentValue[key].height.val,
                opacity: currentValue[key].opacity.val,
              };
              return (
                <div onClick={this.handleClick.bind(null, key)} style={style}>
                  {currentValue[key].text}
                </div>
              );
            })}
          </div>
        }
      </TransitionSpring>
    );
  }
});
```

Thanks for opening up the docs to critique!

**Comment by chenglou** [comment]
Hey, the API got a revamp. Can you check if the new docs are clearer now? I'll revamp the demo itself when I have the time.

**Comment by kendagriff** [comment]
Yes, `TransitionMotion` is much clearer now!
