### ISSUE TITLE
Cannot read property '_id' of undefined (via UpdateTree // MongoDB)

### ISSUE THREAD

**Issue by boyswan** [chenglou/react-motion#165]
I'm getting an error when using the RouteTransition component found here:

https://gist.github.com/maisano/8faf4bd123fa9842f4ea

When trying to access a route (react-router) which is loading data from a server via MongoDB, updateTree doesn't seem to like Mongo's ObjectID BSON type for the _id that is auto generated.

Hopefully there is a fix for this, React Motion is the best animation library :)

**Comment by chenglou** [comment]
Thanks! You mean it recurses down that data structure when it shouldn't? In that case you should cancel the recursion down that tree through the spacial config `[]`. Do you know what I'm talking about?

**Comment by boyswan** [comment]
Afraid I'm not familiar with spacial configs! But preventing it from going down the data structure makes sense

**Comment by chenglou** [comment]
You wrap whatever you don't want RM to traverse down with `{val: yourCollection, config: []}`. So in your case, it's possible that in the upper level there was a `{val: stuffThatContainsYourCollection, config: [120, 16]}`. Once RM sees `val` without a special `config` it'll recursively animate every number in the collection.

(This behaviour is powerful, convenient but very confusing. I'm getting rid of this in the next version.)

**Comment by boyswan** [comment]
I kind of understand-ish... ? haha

So in the RouteTransition gist, this.props.children is used in getEndValue via handler. 

`````javascript
  getEndValue() {
    const { children, pathname } = this.props;

    return {
      [pathname]: {
        handler: children,
        opacity: { val: 1 }
      }
    };
  },
`````
Am I right in thinking thats what I need to prevent RM from traversing down?  It's a little tricky to wrap my head around!

**Comment by boyswan** [comment]
Oh I think I understand a bit more now, I wrap my collection with the val object in order to prevent it from being 'checked' when RM gets down to it. Is that correct?

**Comment by chenglou** [comment]
Yes. Example:
`{val: {a: 1, b: [1,2]}, config: [120, 16]}` <- this animates both `a` and the items inside `b`.
So when you have e.g. `{val: {a: 1, b: mongoCollection}, config: [120, 16]}`, it animates that whole thing "accidentally". To cancel it out you do: `{val: {a: 1, b: {val: mongoCollection, config: []}}, config: [120, 17]}`.

**Comment by chenglou** [comment]
Over time I've found that there's not much benefit in animation a whole collection for you. I'm removing that capacity in the next version, and for the edge cases where you do actually want to animate a collection, there will be a clear, obvious API.

**Comment by boyswan** [comment]
Perfect, thanks for your help!  In the meantime i'll try to get it working, if not then i'll wait for the next version. Thanks again for RM :smile:

**Comment by chenglou** [comment]
New API out! Should side-step your problem completely. If you have any more question on this, feel free to ask here or on Slack!
