### ISSUE TITLE
What is the default value of config?

### ISSUE THREAD

**Issue by oliviertassinari** [chenglou/react-motion#166]
The default `config` almost fit my needs but I need to change it a little bit.

**Comment by threepointone** [comment]
[170, 26]. https://github.com/chenglou/react-motion/blob/master/src/presets.js

**Comment by oliviertassinari** [comment]
Thanks, could be great to have it in the README.

**Comment by chenglou** [comment]
It's there actually: https://github.com/chenglou/react-motion#presets
=)

**Comment by oliviertassinari** [comment]
My bad. Thanks!
