### ISSUE TITLE
Transition precision

### ISSUE THREAD

**Issue by azproduction** [chenglou/react-motion#167]
I have an opacity transition from 0 to 1 when I am adding an item and from 1 to 0 on item removing.

When having transition from 0 to 1, a few last animation frames are trembling near 1 (0.9981, 0.9991 and so on), which is completely unnoticeable.

The other way around has issues. When animating from 1 to 0, a few last animation frames are also trembling near 0, but it takes something like third of animation time, so I see a blank placeholder for a some time.

Is there any way I can specify a stepping precision for a TransitionSpring?

**Comment by chenglou** [comment]
The stepping precision will be configured for you in the next next release. We'll recognize opacity and round it to the correct number of decimals (2 in this case). Closing this in favour of #100! =)

**Comment by azproduction** [comment]
Thanks!
