### ISSUE TITLE
Replay animation

### ISSUE THREAD

**Issue by nlhkh** [chenglou/react-motion#168]
I have a use case where I need the animation to replay on rerender. Does react-motion support such thing?
The way I see it is that a Spring will hold on to the current `value`, and then spring to the new `value`, whereas I wish to replay from `defaultValue` to `endValue` again.

**Comment by chenglou** [comment]
Not currently, since the starting position of your animation is the currently interpolated position (a good default of course).
I might expose hooks to override the current position in the future.

**Comment by nlhkh** [comment]
Sounds like a good plan :+1:

**Comment by rayshan** [comment]
Hi, I assume this will also apply if we want to implement a looping animation, such as a loading spinner?

**Comment by chenglou** [comment]
Yeah. Though the rotational loading spinner isn't a spring.

**Comment by nlhkh** [comment]
Just for fun, if you project the motion of an object on a circular path at constant speed on a diameter, that motion is of a spring.

**Comment by chenglou** [comment]
Isn't that just a regular sine/cosine wave? It approximates a spring of a certain configuration (and vice-versa) but isn't really one?

**Comment by nlhkh** [comment]
I don't remember, but I will look it up when I have a chance. I think it represents the spring in perfect condition (swing forever). Of course in real life there will be damping effect, which you can also simulate by having the magnitude of the oscillation varies over time.

**Comment by chenglou** [comment]
Closing this for now as it's low-pri and RM is a transition library, not an animation sequencing library. But if the API allows, we'll create something that caters to sequence/replay in the future.
