### ISSUE TITLE
Create WebJar

### ISSUE THREAD

**Issue by jclyons** [chenglou/react-motion#169]
Can you publish react-motion as a WebJar in org.webjars for simple inclusion in projects for JVM-based languages?

**Comment by chenglou** [comment]
Humm, frankly I have never heard of web jars before. I won't be supporting something I know I don't understand in the future, so I'll have to pass on this one, sorry.

That being said, it should be just a step in the build process (that I nonetheless am not familiar with) right? You're welcome to fork this and keep a built version for yourself =)

Sorry again!

**Comment by sgrove** [comment]
@jclyons What would it take to make publishing RM as a WebJar an optional, seamless one-command task?

**Comment by jclyons** [comment]
Typically people use Maven along with a pom.xml. So you'd have to add a pom.xml file to your directory root. It's worth looking at the WebJar repository for React itself:

https://github.com/webjars/react 

Then you'd use the Maven CLI to publish it to the WebJars repository (or another, possibly private repository.)

Another option would be to use sbt which is what I do since I'm more familiar with it than maven (I mostly work in Scala.). The sbt-web plugin for sbt mostly handles packaging the relevant assets in the correct path inside the jar artifact that gets created when run 'sbt publish.'

I haven't explored creating WebJars with npm, and don't know if it is currently possible, but theoretically it should be possible, especially since there is a 'build-jar' module:  

https://www.npmjs.com/package/build-jar

**Comment by jclyons** [comment]
The most relevant things to know are on this page:

http://www.webjars.org/contributing

It's pretty simple - the most important thing is that the assets are in the correct directory inside the WebJar: META-INF/resources/webjars/${name}/${version}

**Comment by nkbt** [comment]
I believe this is something that should live in a separate repository/fork

**Comment by nkbt** [comment]
Oh, you said M-word here! :trollface:

**Comment by jclyons** [comment]
Ok - since I seem to be using react-motion more and more I will perhaps be able to get to this someday soon.

**Comment by nkbt** [comment]
@jclyons :+1:

**Comment by jclyons** [comment]
Here is a repository for the webjar: http://github.com/jaroop/react-motion-webjar 

The repository has yet to be incorporated into the webjars repository, though I have created an issue on the main webjar repository for it: https://github.com/webjars/webjars/issues/1230

**Comment by jclyons** [comment]
I'm also writing a bridge between ScalaJS <=> React-Motion so that this component can be used in ScalaJS projects.

**Comment by nkbt** [comment]
Thank you!

> I'm also writing a bridge between ScalaJS React <=> React-Motion

This is pretty awesome!
