### ISSUE TITLE
Unminified example code

### ISSUE THREAD

**Issue by bstro** [chenglou/react-motion#170]
It'd be awesome if the examples linked to from the `readme.md` were unminified so one could easily see how such examples were accomplished.

**Comment by chenglou** [comment]
True. Though you should be checking the actual source in demos/

I'm a bit busy right now but this is a non-brainer. PR welcome!

**Comment by chenglou** [comment]
Eh, note that dev-specific paths should be stripped for perf. Right now it's bundled within uglify. I don't know if you can take this step out of it or if there's a Babel plugin for just this

**Comment by chenglou** [comment]
cc @nkbt @gaearon who probably knows something about this?

**Comment by nkbt** [comment]
It should be really simple to skip uglify (not sure why it was used in the first place)

**Comment by nkbt** [comment]
Give me 5 min =)
