### ISSUE TITLE
Integrate flow

### ISSUE THREAD

**Issue by chenglou** [chenglou/react-motion#172]

**Comment by ludovicofischer** [comment]
Do you mean to just add Flow type annotations to the react-motion codebase or something more sophisticated?

**Comment by chenglou** [comment]
Adding flow annotations, yes. Especially the trickier parts like passing Motion's `style` object around.

**Comment by ludovicofischer** [comment]
I want to give Flow another chance, so I could see how it fares on this codebase. Is the codebase more or less stable?

**Comment by chenglou** [comment]
Yes, but I will be in the process of moving some code around and rewriting some logic, which is exactly why I wanted this

**Comment by chenglou** [comment]
Why wasn't flow good enough for you?

**Comment by ludovicofischer** [comment]
The first problem was that the flow server would crash because a project dependency included a malformed package.json. The error messages were cryptic and the last straw was that it did not support `let` and `const` at the time.

**Comment by chenglou** [comment]
Well, RM doesn't have many dependencies and now that `let` and `const` are supported, we should be fine?

**Comment by ludovicofischer** [comment]
Right off the bat, we’ve hit this Flow bug https://github.com/facebook/flow/issues/830 with destructuring assignments with `const`, in `components.js` for example: 
```javascript
const {PropTypes} = React;
```
 as well as https://github.com/facebook/flow/issues/828 in the animationLoop.js imports. We can either
1. change coding style
2. wait for the next Flow release.

**Comment by ludovicofischer** [comment]
Also flow does not accept this syntax in `animationLoop.js`, line 6:

```javascript
let {
    timeStep = 1 / 60 * 1000,
    timeScale = 1,
    maxSteps = 10,
    raf = defaultRaf,
    now = defaultNow,
  } = config;
```
I guess you’re overriding the defaults you set within the curly braces with the contents of `config`, but I can’t find a reference for this syntax either: where did you learn it?

**Comment by ludovicofischer** [comment]
Flow does not support computed propery keys either: https://github.com/facebook/flow/issues/252, which we use in `components.js`, line 373:
```javascript
          currentStyles = {
            ...currentStyles,
            [key]: enterStyle,
          };
          currentVelocities = {
            ...currentVelocities,
            [key]: mapObject(zero, enterStyle),
          };
```

**Comment by ludovicofischer** [comment]
My work so far: https://github.com/ludovicofischer/react-motion/tree/flow

**Comment by chenglou** [comment]
> I guess you’re overriding the defaults you set within the curly braces with the contents of config, but I can’t find a reference for this syntax either: where did you learn it?

It's just destructuring + default assignment

I guess we could rewrite the const bit.

For computed properties, at least `newClonedStyle[key] = enterStyle` works, right?

**Comment by samwgoldman** [comment]
Hey, found this issue through the link to facebook/flow#252. Wanted to add a few thoughts:

1. `const` destructuring support has landed in master
2. destructuring with defaults is definitely sorely missing, but I hope to get to it in the coming weeks
3. computed properties are tricker to grok statically, but would it satisfy your use case if the dynamic key was a single const binding? i.e., `key` in `{ [key]: value }` were declared as `const key = "some string"`

**Comment by ludovicofischer** [comment]
Wow, a flow committer! (thanks for your work on `const` and `let` BTW). 
Interestingly, I managed to replace a few of the problematic constructs and removed a lot of flow warnings, but now the tests do not pass any more because of an `undefined` property. There are some warnings about `null` and `undefined`, so let’s hope it is an error that flow *does* catch.

**Comment by nkbt** [comment]
Webstorm just landed EAP with basic Flow support. Looks like great timing http://blog.jetbrains.com/webstorm/2015/09/webstorm-11-eap-142-5255/

**Comment by chenglou** [comment]
I was half expecting some nullable stuff to get caught by Flow. Hopefully Flow's right!

@samwgoldman the `key` isn't a constant. It's passed as a parameter.

**Comment by samwgoldman** [comment]
If we're talking about an object-as-map types, e.g., `{ [key: any]: any }`, computed property keys should be straightforward, since Flow will not attempt to track the set of keys. Computed properties get complicated when we try to build an object type with a known set of keys, e.g., `{ foo: string, bar: number }`.

If you have an object-as-map scenario, using multiple statements to build up the object is the best workaround until we support this pattern in Flow.

**Comment by chenglou** [comment]
So `newClonedStyle[key] = enterStyle` right? That's fine then!

**Comment by ludovicofischer** [comment]
@samwgoldman Are you planning a Flow release soon with the const destructuring fixes?

**Comment by ludovicofischer** [comment]
Now that Flow 0.17 has been released, we’re still hitting https://github.com/facebook/flow/issues/183 in `animationLoop.js`, also a Flow problem I did not find a previous report for https://github.com/facebook/flow/issues/940, in `react-motions.js`.

**Comment by chenglou** [comment]
Good enough! We can gradually do the rest. Thanks again for the push @ludovicofischer! =)
