### ISSUE TITLE
Uncaught TypeError: Cannot read property 'config' of undefined

### ISSUE THREAD

**Issue by lencioni** [chenglou/react-motion#180]
I am upgrading from 0.2.7 to 0.3.0 and I ran into an error:

> Uncaught TypeError: Cannot read property 'config' of undefined

This happens when I am using a `TransitionMotion` with a style object that has a key who's value is `undefined`, e.g.:

```js
{
  opacity: spring(0),
  extraText: undefined,
}
```

This is happening on https://github.com/chenglou/react-motion/blob/d478fe6ba1a5ba74ab364747f063e16fa8c3185f/src/updateTree.js#L38

I can side-step the issue by setting that value to something other than `undefined` or `null`, but it would be nice if I didn't have to. I believe this could be avoided by adding a couple of checks here and there, for example:

```js
if (!style[key].config) {
```

could be changed to

```js
if (!style[key] || !style[key].config) {
```

**Comment by chenglou** [comment]
Damn it, we need a type system...
@ludovicofischer if you want, feel free to submit small flow PRs gradually!

**Comment by lencioni** [comment]
Flow would be sweet. In the meantime, I'll submit a PR that addresses this issue.

**Comment by chenglou** [comment]
Oh it's fine, I'm working on it right now!

**Comment by lencioni** [comment]
I just need to write commit message. ;)
