### ISSUE TITLE
StaggeredMotion: Dynamic styles not supported

### ISSUE THREAD

**Issue by twobit** [chenglou/react-motion#185]
It doesn't look like it's possible to change the amount of styles fed to a `StaggeredMotion` component.

I [modified the demo](https://github.com/twobit/react-motion/commit/231307594790c2d4ac1e90d6aa60f8ce655edb25) to grow the array of items when `enter` is clicked but `StaggeredMotion` is ignoring any additional items.

**Comment by chenglou** [comment]
That's expected. Only TransitionMotion supports diffing.

**Comment by twobit** [comment]
Ok great to know, thanks :)

**Comment by chenglou** [comment]
Np. Closing this. But does it cause any inconvenience?

**Comment by twobit** [comment]
No, I can easily convert to `TransitionMotion`
