### ISSUE TITLE
Help a noob out

### ISSUE THREAD

**Issue by fbm-static** [chenglou/react-motion#186]
Hi,

```
import {Motion, spring} from 'react-motion';
// In your render...
<Motion defaultStyle={{x: 0}} style={{x: spring(10)}}>
  {value => <div>{value.x}</div>}
</Motion>
```

What does translate to  in JSX pre-es6?

**Comment by chenglou** [comment]
[Here's](http://babeljs.io/repl/#?experimental=false&evaluate=true&loose=false&spec=false&code=import%20%7BMotion%2C%20spring%7D%20from%20'react-motion'%3B%0A%2F%2F%20In%20your%20render...%0A%3CMotion%20defaultStyle%3D%7B%7Bx%3A%200%7D%7D%20style%3D%7B%7Bx%3A%20spring(10)%7D%7D%3E%0A%20%20%7Bvalue%20%3D%3E%20%3Cdiv%3E%7Bvalue.x%7D%3C%2Fdiv%3E%7D%0A%3C%2FMotion%3E) the literal transpiled version.

But in handwritten es5:

```jsx
var ReactMotion = require('react-motion');
var Motion = ReactMotion.Motion;
var spring = ReactMotion.spring;
/// In your render...
<Motion defaultStyle={{x: 0}} style={{x: spring(10)}}>
  {function(value) {return <div>{value.x}</div>}}
</Motion>
```
Hope that helps!
