### ISSUE TITLE
Best way to animate an array of values with new api?

### ISSUE THREAD

**Issue by adrienhobbs** [chenglou/react-motion#189]
With 0.2.7, I could animate an array of values like this: spring([100,300,500,600]);  The use case is for animating a set of points for an svg polygon path.

What's the best way to go about doing this with the new API?  Thanks!

**Comment by chenglou** [comment]
Right, currently it's a temporary regression. You'll have to animate each value individually. The rationale is that supporting animation nested collections had a huge cost (confusions with `val` and all).

The good part is, animating an array like is mostly for what you're trying to achieve: SVG path. I was thinking of either:

1. Exposing a (mandatory) helper similar to `spring`, e.g. `springSVG([1,2,3], myConfig)`, or
2. Make some properties special, e.g. `height` will animate differently (round to integer), `transform` can take a array `{transform: [spring(10), spring(10), spring(20)]}`, svg path (what's the property? ...) can take an array.

Advantage of 2 is that it's more convenient and declarative. Disadvantage would be it's platform-dependent.

**Comment by adrienhobbs** [comment]
Got it.  Number 1 sounds like a good solution, especially if that seems to be the most common use-case.  For transforms and such, ES6's string interpolation has made animating transforms rather quick and easy, but I definitely see the advantages of having a more versatile way of animating specific properties.

**Comment by nkbt** [comment]
@adrienhobbs you can animate a single value and recalculate all others accordingly.

```
const myVals = [100,300,500,600];

<Motion defaultStyle={{something: 0}} style={{something: 1}}>
  {({something}) => <Component shape={myVals.map(v => v * something)}}
</Motion>
```

**Comment by crossman** [comment]
For what it's worth, @nkbt solution works perfectly for my needs and has the added bonus of not adding any bloat to the library. It's beautifully simple.

**Comment by kuanslove** [comment]
@nkbt  really brillant idea. But one question: how do u handle transit consistence? Like from one array to another one rather than from 0 to anther ?

**Comment by nkbt** [comment]
@kuanslove I am not sure what you mean, can you give some code example?

**Comment by kuanslove** [comment]
@nkbt  One example is to build a component which contains a <path d="" />, this component has prop called data which accept a data array, and when I switch to another data array, this component can interpolate between two arrays and draw the line with transition animation effect

**Comment by nkbt** [comment]
@kuanslove I was talking more about some code example, I can kind of understand what you want, but do not have much time writing full example myself. Please, share some code and I would be able to help you with more concrete formula!

So far I cannot see the ptoblem why it does not work for your case

```
const from = [10, 20, 30, 40];
const to = [110, 120, 130, 140];

const calculatePath = value => {
  return to.map((toValue, i) => (toValue - from[i]) * value)
}

<Motion defaultStyle={{value: 0}} style={{value: 1}}>
  {({value}) => <path d={calculatePath(value)} />}
</Motion>
```

It is up to you how you do your proportional calculations in `calculatePath(value)`, considering that `value` is being smoothly changed from `0` to `1`. Pure math from here
