### ISSUE TITLE
npm start (Windows 7 0.0.0): Executed 55 of 59 

### ISSUE THREAD

**Issue by zanjs** [chenglou/react-motion#191]
PhantomJS 1.9.8 (Windows 7 0.0.0): Executed 55 of 59 (4 FAILED) (skipped 2) (0 sPhantomJS 1.9.8 (Windows 7 0.0.0): Executed 56 of 59 (4 FAILED) (skipped 2) (0 sPhantomJS 1.9.8 (Windows 7 0.0.0): Executed 57 of 59 (4 FAILED) (skipped 2) (0 sPhantomJS 1.9.8 (Windows 7 0.0.0): Executed 57 of 59 (4 FAILED) (skipped 2) (0.118 secs / 0.333 secs)

npm ERR! Windows_NT 6.1.7601
npm ERR! argv "D:\\nodejs\\node.exe" "D:\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "karma"
npm ERR! node v4.0.0
npm ERR! npm  v2.14.2
npm ERR! code ELIFECYCLE
npm ERR! react-motion@0.3.0 karma: `set NODE_ENV=development && karma start ./karma.conf.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the react-motion@0.3.0 karma script 'set NODE_ENV=development && karma start ./karma.conf.js'.
npm ERR! This is most likely a problem with the react-motion package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     set NODE_ENV=development && karma start ./karma.conf.js
npm ERR! You can get their info via:
npm ERR!     npm owner ls react-motion
npm ERR! There is likely additional logging output above.

**Comment by nkbt** [comment]
I don't think we ever tested build/tests on Win. Though I can have a look at is since I do dev on both osx and win.

**Comment by nkbt** [comment]
See #193, that definitely fixes tests. Issue was with `NODE_ENV` not being equal to `"development"`.

I fixed all scripts (pretty minor fixes, tbh) and now it is possible to do development/testing on Windows too.
