### ISSUE TITLE
ES2015 Map instead of using Objects?

### ISSUE THREAD

**Issue by ducky427** [chenglou/react-motion#192]
As a new user to the library and the "modern" javascript ecosystem, now that we have a proper [`Map`](https://babeljs.io/docs/learn-es2015/#map-set-weak-map-weak-set) in ES2015 and babel, does it make sense to use that instead of using Objects throughout the API?

For instance, in `Motion` component, `defaultStyle`/`style` could return a Map and `children` would return `Map -> ?ReactElement`

Using an Object when you meant to use a Map in Javascript has always felt unclean to me but this is my personal preference.

I don't know much about this project. So I apologize if this has been considered and rejected or its a change not worth it.

**Comment by chenglou** [comment]
For a few reasons!
1. Object super optimized and comes with the whole ecosystem of function that manipulate/transform it (e,g. lodash, and some css-in-js libraries). Splat and destructuring work on it and those are some pretty important sugar, along with a visually clean literal to begin with.
2. I'd argue it's actually a Record, which maps to an object in JS, not a Map. Theoretically, your keys are finite and each field is type checked (relevant: https://github.com/chenglou/react-motion/pull/187#discussion_r41101959)
e.g. 
```jsx
type style = {
  height: number | styleConfig,
  // ... an exhaustive list of valid style attributes
}
```
Motion informally dictates you to keep your record fields the same from one render to another.
TransitionMotion's `styles` is actually a Map<string, style>. But at this point it's probably more pragmatic to use object all the way through (again, destructuring, etc.)

Hope that answers your question? Closing, but feel free to reply more!

**Comment by ducky427** [comment]
Thanks a lot! All valid points.
