### ISSUE TITLE
unmount threshold

### ISSUE THREAD

**Issue by Aaike** [chenglou/react-motion#196]
Is there a way to define the threshold for when a component should unmount when using the TransitionMotion component ? 

I assume the component unmounts when all animated properties have reached their target value.

It would be great is we can specify that the component should unmount when the target value is close to being finished.

For example: When animating from opacity 1 to 0 with a threshold of `10%`, the component could unmount as soon as the opacity reaches `0.1` , instead of going all the way to 0.

**Comment by nkbt** [comment]
I reckon that might be a #100 duplicate

**Comment by zimok** [comment]
any news about this?

**Comment by chenglou** [comment]
Yes. Going in soon. Closing in favour of #100

**Comment by zimok** [comment]
Thanks
