### ISSUE TITLE
Update webpack config to support new Demo folders

### ISSUE THREAD

**Issue by nkbt** [chenglou/react-motion#197]
After  #195 webpack build is not working correctly since it puts `all.js` into `demoX` folder.
Also all links in the README are going to be broken.

Ping @stevoland, @chenglou

**Comment by chenglou** [comment]
Ahhh I remember now!...
What's the solution? Webpack's string templates are pretty limited

**Comment by nkbt** [comment]
Manually type in new folders in config and use proper placeholders in output. I could give it a shot today, unless @stevoland wants to fix it by himself.

**Comment by nkbt** [comment]
I am going to fix it alongside with #24

**Comment by stevoland** [comment]
Whoops, sorry. Let me know if you want me to fix.

Readme links point to a previous commit so don't need changing yet.

**Comment by nkbt** [comment]
yeah, README is ok for now.
