### ISSUE TITLE
Question: Any possibility to create motion fadeout-changeContent-fadein?

### ISSUE THREAD

**Issue by ALF-er** [chenglou/react-motion#202]
Hello, I try to implement simple motion. I have `<div>Some text</div>` I want to fade it to `opacity: 0`, change it's content to `Some another text` and then bring it back to `opacity: 1`. And... I'm failed =| It seems to be an to complex task for current Motions. Maybe I missed something?

**Comment by chenglou** [comment]
It's not very straightforward to assign a callback when the animation completes. This will be implemented next. After that you should be fine, right?

Currently, you can check the interpolated style object to see whether it's reached a value

**Comment by ALF-er** [comment]
Yeah, some hook will solve my problem. But I think is it declarative. Up on you =)

About
>  you can check the interpolated style object to see whether it's reached a value

Yes I can, but how I can run reverse opacity-motion when It already complete?

**Comment by chenglou** [comment]
Set a state, and use that state to set a new destination style value

**Comment by ALF-er** [comment]
Set state from `render() {}` O.o I don't get arrested for that?

**Comment by chenglou** [comment]
They'll detain you for a few days but I promise I'll pay the fees to get you out

**Comment by ALF-er** [comment]
You the best! 

Thank you for advice =)

**Comment by ALF-er** [comment]
You know... I tried to do this.setState from render() and get
```
Error: Invariant Violation: setState(...): Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.
```
Maybe you mean something different?

**Comment by chenglou** [comment]
Oops sorry, dumb mistake... Yeah that's not possible.
Right now you could use StaggerMotion with an array of a single style. You have access to the previous style array in the `styles` callback.

**Comment by chenglou** [comment]
Closing in favour of #224 =)
