### ISSUE TITLE
Fix ESLint errors

### ISSUE THREAD

**Issue by ludovicofischer** [chenglou/react-motion#211]
Updating to ESLint 1.6.0 and `eslint-airbnb-config` 0.1.0 and executing `npm run lint` gives 169 errors. Some of it are variable names that are too short,  but some others should probably be fixed.

**Comment by nkbt** [comment]
I think `too short` vars are ok and we just need to override that rule to `0`

**Comment by chenglou** [comment]
Fixed by #215
