### ISSUE TITLE
TypeError: this.stopAnimation is not a function

### ISSUE THREAD

**Issue by lencioni** [chenglou/react-motion#212]
I'm seeing the following error logged occasionally:

```
~/react-motion/lib/components in componentWillUnmount
TypeError: this.stopAnimation is not a function
```

After looking through the code, I don't see how this would happen. Is it possible for a component to call `componentWillUnmount` before it calls `componentDidMount`? I'd prefer to understand why this is happening, but we could guard against it by doing something like:

```js
if (typeof this.stopAnimation === 'function') {
  this.stopAnimation();
}
```

Or by making sure that `stopAnimation` is always defined as a noop. If you like one of these solutions, I'd be happy to submit a PR.

**Comment by chenglou** [comment]
No that shouldn't happen, you're right.
And I don't think we should guard it like that. Better get to the root of the problem, humm...

**Comment by chenglou** [comment]
Can you provide a small repro?

**Comment by nkbt** [comment]
I immediately have 2 suggestions, but we do need some more info on how to reproduce it.

1. If there is anything async then component could be unmounted before we get to run stopAnimation.
2. We lost context somewhere along the way and `this` is not the one we expect here.

Maybe something else, but I can't see for now.

**Comment by lencioni** [comment]
A small repro would be nice. I can look into that soon, but I believe I might have some difficulty consistently reproducing it. We are seeing this error logged in Sentry, which we use for error tracking, and it doesn't seem to be happening consistently.

I can see that it is happening on line 418 of components.js, which puts it in the `TransitionMotion` component. It could be happening for other components as well (we are only otherwise using `Motion`), but I'm not seeing it logged on other lines.

I also see the following logged from Safari, which I think is the same problem:

> TypeError: 'null' is not a function (evaluating 'this.stopAnimation()')

And this has been logged on the same line in an unknown Windows browser:

> TypeError: Object expected

I also don't recall seeing anything like this logged before upgrading to 0.3.0, so perhaps there is a clue there?

**Comment by lencioni** [comment]
I haven't been able to build a small repro yet, but here's the stack trace with some context in case that helps:

```
this.stopAnimation is not a function

~/react-motion/lib/components.js?fbcc in componentWillUnmount at line 418:0
  this.stopAnimation();

~/react/lib/ReactCompositeComponent.js?cd59** in unmountComponent at line 243:0
  inst.componentWillUnmount();

~/react/lib/ReactReconciler.js?6bfa** in unmountComponent at line 52:0
  internalInstance.unmountComponent();

~/react/lib/ReactCompositeComponent.js?cd59** in unmountComponent at line 246:0
  ReactReconciler.unmountComponent(this._renderedComponent);

~/react/lib/ReactReconciler.js?6bfa** in unmountComponent at line 52:0
  internalInstance.unmountComponent();

~/react/lib/ReactCompositeComponent.js?cd59** in unmountComponent at line 246:0
  ReactReconciler.unmountComponent(this._renderedComponent);

~/react/lib/ReactReconciler.js?6bfa** in unmountComponent at line 52:0
  internalInstance.unmountComponent();

~/react/lib/ReactChildReconciler.js?ff46** in unmountChildren at line 115:0
  ReactReconciler.unmountComponent(renderedChild);

~/react/lib/ReactMultiChild.js?c87d** in unmountChildren at line 398:0
  ReactChildReconciler.unmountChildren(renderedChildren);

~/react/lib/ReactDOMComponent.js?1302** in unmountComponent at line 911:0
  this.unmountChildren();

~/react/lib/ReactReconciler.js?6bfa** in unmountComponent at line 52:0
  internalInstance.unmountComponent();
```

**Comment by chenglou** [comment]
what's `this`?

**Comment by lencioni** [comment]
Unfortunately, the stack trace I sent you is just in our logs which don't have that information. I haven't been able to reproduce this in my browser yet.

**Comment by chenglou** [comment]
The newest release 0.4.1 does away with `stopAnimation`. This shouldn't happen anymore. Sorry for the wait!
