### ISSUE TITLE
Make readme demo links point to commit hash urls and not latest

### ISSUE THREAD

**Issue by chenglou** [chenglou/react-motion#218]
This way, when someone `checkout` an older commit the correct, dated demo links will be shown.

**Comment by nkbt** [comment]
Ouch, accidentally clicked.

**Comment by nkbt** [comment]
Makes sense, but why would you check out older commit in the first place? Are we going LTS or something, supporting multiple API versions, etc?

**Comment by chenglou** [comment]
Makes debugger and referring much easier, that's all. Just like how I usually post the commit hash URL to a file rather than master in issues

**Comment by chenglou** [comment]
You know what, meh =).
