### ISSUE TITLE
Motion isn't interpolating between 0 and 48

### ISSUE THREAD

**Issue by appsforartists** [chenglou/react-motion#225]
[Here's a reduction](http://codepen.io/appsforartists/pen/avYZrZ?editors=001).

It looks like I got my spring numbers backwards.  With any damping above 120, it generates a bunch of asymptotically smaller numbers until it bottoms out at NaN.  

Perhaps there should be a warning for improbable (or impossible) spring values.

**Comment by nkbt** [comment]
I guess it might be also related to #100? I mean we can get this fixed by simply having some sane precision.

**Comment by chenglou** [comment]
Fixed for v0.4.1, as `spring` now takes the unambiguous format `spring(value, {stiffness: ..., damping: ...})`.

I'll close this for now, because it seems weird constraining the physics numbers. But maybe this is the reasonable thing to do. Feel free to contest this!

**Comment by appsforartists** [comment]
Nothing to contest for me.  If it's harder to accidentally transpose the values, the surface area for this issue gets a lot smaller.
