### ISSUE TITLE
React warnings

### ISSUE THREAD

**Issue by salzhrani** [chenglou/react-motion#227]
I keep getting the following warning
`Warning: setState(...): Cannot update during an existing state transition (such as within `render`). Render methods should be a pure function of props and state.` and usually it is `springEnd` that is calling `setState` not sure what could be causing this.

**Comment by nkbt** [comment]
Somehow you are calling setState within a render call. It is really hard to tell without looking at your code.

**Comment by salzhrani** [comment]
I thought springEnd was part of RM, but it is not.

thank you.
