### ISSUE TITLE
Handle long pauses gracefully

### ISSUE THREAD

**Issue by brigand** [chenglou/react-motion#233]
Example: http://jsbin.com/nimujewiju/1/edit?js,output

In chrome if you drag it to e.g. 50% and quickly tab to another window (tested on osx yosemite), the animation pauses and then it goes to ~100% and stays there. The problem is bad because it goes beyond the target by far. 

I imagine the solution is something like clamping the elapsed time to 50ms or so and ensuring that another update occurs if it's overshot.

**Comment by chenglou** [comment]
That's... a bug? @bsansouci

**Comment by chenglou** [comment]
Ahahaha, fuck JavaScript =)

Got it. It has nothing to do with switching tab. You forgot to use `parseInt` on `e.target.value` and RM let that pass through by doing some `+` operation on string, which results in a nonsensical value in the end. Adding `parseInt` fixes this.

That was funny. Closing! =)

**Comment by sompylasar** [comment]
@chenglou Fuck DOM for returning `string` as the `value` of `input type="range"` :see_no_evil:

**Comment by chenglou** [comment]
It's the DOM alright =P
