### ISSUE TITLE
Tell when animation is finished

### ISSUE THREAD

**Issue by nkbt** [chenglou/react-motion#235]
Sort of related to #100

It is OK now to check current value if you are using default spring preset. But if I am using something like `wobbly` and animate `height`, I can easily get zero height while animation is far from being finished (then it goes to negative height, but that is a different story).

So if I think that my animation is done when height equals 0 and want to unmount element, that is not actually true and on next RAF component is shown again but with a very little height. And again and again.

![animation-end](https://cloud.githubusercontent.com/assets/175264/10896978/80f220d8-8211-11e5-8bca-e33809e44b75.gif)

I am pretty sure we had this discussion somewhere else, but could not find a separate issue for this.

I would like to see API in this way:

```
<Motion>
  {(style, {isFinished}) => console.log(isFinished)}
</Motion>
```

Passing another object to `render` function will not break current API, and will potentially allow us to pass more fields, not only `isFinished` but exposing some RM internal state (maybe related to #219)

**Comment by bsansouci** [comment]
What's the advantage of this over adding a prop `onEnd` which would call a callback? I'm a little scared of this `isFinished` inside the render function because it sounds like you'll have to mutate some state in the parent component to register that the animation is done. Ultimately you want the parent to know that the animation is done, not necessarily the children.

**Comment by nkbt** [comment]
Callback would work for some cases, but in my case having `isFinished` passed to render itself would work better, since I do not want to manipulate state, based on callbacks and I want only change what is rendered inside function without re-rendering whole component. I thing both should be added. Though this one probably should not be added to the main README (and added to a separate Advanced usage WIKI page)

**Comment by chenglou** [comment]
`end` callback and `isFinished` here would need to be per number btw, not per style

**Comment by sompylasar** [comment]
@chenglou @nkbt The #219 velocities are a better way to go than a single `isFinished` flag. There could be a helper to which you pass the object with velocities so it calculates whether all / any / some of them have reached certain threshold.

**Comment by nkbt** [comment]
@sompylasar I mentioned that issue in my first message =).
That could be an additional thing passed to `render` callback alongside with `isFinished` flag, which is simple and straightforward and does not require any extra logic around it.

**Comment by sompylasar** [comment]
@nkbt, yes, I saw this. Just missed the "alongside" thing, sorry.

**Comment by yanivtal** [comment]
Is anyone working on this?

**Comment by bsansouci** [comment]
@chenglou I don't think anyone's working on it as of right now. PRs are very welcome though :D

**Comment by chenglou** [comment]
I will be working on this.

**Comment by nkbt** [comment]
I though I will, but had a pretty crazy last month

**Comment by yanivtal** [comment]
Sweet thanks Cheng! We're using this in several projects. Absolutely love it!

**Comment by clayne11** [comment]
+1 - this would be super helpful. I use this library for animations such as animating in a modal from the bottom of the screen, and I want to animate it out then unmount it when the animation is finished, and I currently don't have any way to do that.

**Comment by dozoisch** [comment]
That would be really useful! Particularly for route transition (eg: poping modal/changingfield focus when the animation finished!)

**Comment by ReDrUm** [comment]
:+1: Adding an 'on animation complete' callback prop would be very useful.

**Comment by appsforartists** [comment]
Does it simplify anything to call it `onRest` instead of `onEnd/Finished`?  You don't know if it will ever animate again, just that it isn't currently moving.

I realize this is bikeshedding, but I wonder if it will avoid future confusion or edge cases to present it as a temporary stop (not necc. a permanent one).

**Comment by appsforartists** [comment]
@chenglou you asked for an example of when somebody might want to use this.  Take a look at [this API proposal](https://gist.github.com/appsforartists/b199c6d79044f8e8abaf).

There are many times that I find myself wanting to have an object spring to a user's touch, but then track it perfectly once it gets there.  In a world without an `onRest` callback, this is much more cumbersome than it should be.

**Comment by appsforartists** [comment]
@threepointone, @chenglou, and I just chatted about this for a bit.

While we see the potential usefulness of a per-value onRest (e.g. in springParams), the simple/common case is per Motion instance (you want to know when the child is completely done moving).  Perhaps Motion (and StaggeredMotion) should gain an onRest attribute for now, and we can worry about per-value onRest in the future if it becomes an acute need.  For now, you can fake it by composing Motions together.

Per-value onRest seems like a more advanced usage that would suit a timeline-based API better than what Motion currently provides.

**Comment by nkbt** [comment]
`onRest` === `onSomethingLeft` or something. See http://underscorejs.org/#rest for example.

I don't get the naming, sorry.

**Comment by chenglou** [comment]
I personally don't mind. But I'm opening a new issue to debate about the name so that we don't diverge this one: #274

**Comment by sompylasar** [comment]
It's like equilibrium, but easier to type.
http://www.ask.com/science/rest-position-wave-ec11b00c6b5ff960

**Comment by chenglou** [comment]
Alright so end callback is in for `Motion` (react-motion v0.4.3). If there's request for such cb for `StaggeredMotion` and `TransitionMotion` we should reopen this issue or create a new one.

Sorry for the wait everyone! And thank you again @appsforartists for actually implementing it =].

**Comment by ReDrUm** [comment]
Awesome, thanks!

**Comment by p4bloch** [comment]
@chenglou any news on when/if this will be implemented in `TransitionMotion`? I think that would keep consistency in the API and allow to have an easy, clean way to use that functionality (all I tried to use this with current implementation feels hacky).

> If there's request for such cb for StaggeredMotion and TransitionMotion we should reopen this issue or create a new one.

Not sure if this is the proper way to make a formal request, but I think this could be pushed forward. Any thoughts?

Thanks!

**Comment by appsforartists** [comment]
@p4bloch Are you gonna own `TransitionMotion.@onRest`?  You should start an issue to track your progress against, and submit a PR when it's ready.  😃

**Comment by SkateFreak** [comment]
+1 for the need to know when animation is finished (and/or fires)

**Comment by souporserious** [comment]
@SkateFreak you should be able to do this now with `didLeave` it was merged [here](https://github.com/chenglou/react-motion/pull/399) and documented [here](https://github.com/chenglou/react-motion#--didleave-stylethatleft-key-string-data-any--void).

**Comment by SkateFreak** [comment]
@souporserious thank you

no ```didEnter``` though, right?
