### ISSUE TITLE
GitHub Pages for demos

### ISSUE THREAD

**Issue by aseemk** [chenglou/react-motion#24]
It'd be slick if the demos were available over GH Pages. Then people wouldn't need to clone the repo just to see the demos. =)

Should be as easy as pushing to a `gh-pages` branch, but I might be overlooking something.

Nice work!

**Comment by nkbt** [comment]
This needs some updates in the build config.

**Comment by chenglou** [comment]
Yes that was what I was thinking. It's on my list of things to do =)

**Comment by nkbt** [comment]
@chenglou delegate it =)
I'm happy to do that asap. Assign to me if you are ok

**Comment by chenglou** [comment]
Maybe I should? I have no idea what I want the page to look like yet

**Comment by nkbt** [comment]
It's ok, I can handle it =). Then you/all will add any relevant changes to it

**Comment by chenglou** [comment]
Alright cool. I was thinking of also putting the few hacks I've put in my talk in it, but that can wait. Right now it'd be nice to just have the demos in the repo. Maybe a live editor in the future or soon

**Comment by nkbt** [comment]
I am a little rushing on these things since I am using it in our project. Not much fun to copy-paste changes instead of using proper npm dependency

**Comment by nkbt** [comment]
I reckon I am not alone with this =)

**Comment by chenglou** [comment]
That's nice to hear =)
Somewhat related: I'll put up an issue a-la #14 for TransitionGroup. I want to be confident that the first API doesn't overlook some major flaws (personal experience, heh) before releasing it. At the latest, I'll release this officially when my talk's video comes out.

**Comment by nkbt** [comment]
@chenglou could you please create a `gh-pages` branch so it is possible to make PR there?

**Comment by nkbt** [comment]
I'm going to pick this up
