### ISSUE TITLE
CDN seems broken.

### ISSUE THREAD

**Issue by colus001** [chenglou/react-motion#243]
https://npmcdn.com/react-motion/build/react-motion.js

shows

```
Not found: file "/build/react-motion.js" in package react-motion@0.3.1
```

**Comment by nkbt** [comment]
It is not yet published to npm with build folder in it =)

**Comment by chenglou** [comment]
Humm we should stop pushing readme changes to master, or put a notice, or something else. Not the first time people check master readme and get confused about unreleased stuff.

**Comment by nkbt** [comment]
Yeah, README updates should probably go in a separate PR and merged right before the next release.

**Comment by chenglou** [comment]
Related: #262 and #266.

Sorry for the delay. CDN now works for React-motion v0.4.1.
