### ISSUE TITLE
animationLoop firing while no animation is happening

### ISSUE THREAD

**Issue by timuric** [chenglou/react-motion#246]
After adding few `Motion` components to a project my JS timeline is full of renders even without having any animations triggered http://d.pr/i/1eaJU 

Is there a way to avoid it? Otherwise while profiling it is hard read timeline records, as well as it is consuming CPU

**Comment by chenglou** [comment]
Really? cc @bsansouci

**Comment by timuric** [comment]
@chenglou fortunately I can't recreate it again. I think it might have been a bug with the hot reloading. I would keep my eye one it, and will let you know if it happens again. Sorry for the false alarm.
