### ISSUE TITLE
Remove react-native build

### ISSUE THREAD

**Issue by chenglou** [chenglou/react-motion#249]
https://twitter.com/soprano/status/682402356147826688

Woohoo!

@nkbt @bsansouci

**Comment by nkbt** [comment]
Hell yeah \m/

**Comment by nkbt** [comment]
And #250 too ;)

**Comment by bsansouci** [comment]
ftw :D

**Comment by chenglou** [comment]
https://github.com/facebook/react-native/commit/5bf1f4c05ef0f3ee1cbf6e38164d58dbeee6637d

Released as 0.18. We're good. Bye-bye extra build steps!
