### ISSUE TITLE
Repeating animation

### ISSUE THREAD

**Issue by thunderkid** [chenglou/react-motion#256]
Is there a simple way to specifiy that an animation keeps repeating forever (or maybe just 30 times)? I can't seem to find it in the docs.

**Comment by threepointone** [comment]
Currently, react-motion leaves details of state management with regards to timing etc to the developer (and there are plans for an `atRest` callback). Could you share more details of your animation?

**Comment by chenglou** [comment]
`Motion` now has `onRest`, in the release v0.4.3! Sorry for the wait.
