### ISSUE TITLE
Motion does not work inside TouchableWithoutFeedback

### ISSUE THREAD

**Issue by jasonkuhrt** [chenglou/react-motion#258]
![](http://g.recordit.co/AMpIjygYZd.gif)

Hi @chenglou I found a possible issue with React Native. I am going to describe what the issue looks like but I don't have good insight about _why_ yet.

The setup is simple enough. Below is a render body that will create _three_ switches, each with slightly differing structure.

1. The first case where `<Touchable>` _contains_ `<Motion>`, which I thought should work (that ~exact code works on Web) did not!

1. The second case where `<Motion>` _contains_ `<Touchable>` ***does work***!

1. The third case is what I had before I introducing animation so of course it works ...because it isn't using `<Motion>`.

The question/bug is ***why isn't the first case working***?

```js
  render () {
    const {
      value,
      onValueChange,
      style,
    } = this.props
    const springValue = value ? 0 : stylePropsDefault.height
    return (
      <View>

        <Touchable onPress={onValueChange}>
          <Motion style={{ x: spring(springValue) }}>{({ x }) =>
            <View style={style.track}>
              <View style={{
                ...style.handle,
                transform: [{ translateX: x }],
                // transform: `translateX(${x}px)`,
              }}/>
            </View>
          }</Motion>
        </Touchable>

        <Motion style={{ x: spring(springValue) }}>{({ x }) =>
          <Touchable onPress={onValueChange}>
            <View style={style.track}>
              <View style={{
                ...style.handle,
                transform: [{ translateX: x }],
                // transform: `translateX(${x}px)`,
              }}/>
            </View>
          </Touchable>
        }</Motion>

        <Touchable onPress={onValueChange}>
          <View style={style.track}>
            <View style={style.handle}/>
          </View>
        </Touchable>
      </View>

    )
  }
```

**Comment by jasonkuhrt** [comment]
Hm! Interesting. If I use `TouchableOpacity` then everything works as expected! The problem really does seem specific to `TouchableWithoutFeedback`. Screen Recording:


![](http://g.recordit.co/6opDp9CfNe.gif)

**Comment by chenglou** [comment]
Can you try the new release? Don't think it'll fix this, but who knows.

**Comment by chenglou** [comment]
Seems like outside of the scope of React-motion now. If not, feel free to reopen!

**Comment by jasonkuhrt** [comment]
Thanks, I'm not longer working at littleBits so this issue isn't mine anymore heh. Thanks for following up.
