### ISSUE TITLE
Justification for the TransitionSpring API

### ISSUE THREAD

**Issue by chenglou** [chenglou/react-motion#26]
Aside from a (very) nice-to-have declarative animation API, we need to solve the problem of animation on unmounting. This is a React-specific problem.

### `TransitionGroup`

It has many problems: race conditions, re-mounting while unmounting, lack of control over animation/children tree shape (flat list), etc. `TransitionSpring` addresses, I think, every single one of the pain points I could come up with from `TransitionGroup`. I'm not claiming it's a strictly superior solution: for the basic use-cases `TransitionGroup` can be terser.

### `TransitionSpring`

The normal `Spring` dictates that your interpolated data structure's shape stays the same from one render to another. In practice, it's very rare to have the shape of your interpolated data change; even if it does, it's probably not a good idea and supporting this use-case complicates this library's API.

The notable exception is when new components appear/disappear/move (since you generated these components through the interpolated data, your data shape naturally changes too). `TransitionSpring` builds on top of the normal `Spring` but allows diffing the data structure in a controlled way. Specifically, currently, it asks you to provide an object of `key => yourConfig`, where `yourConfig` is the normal data structure you'd use with `Spring`, with the `{val: ..., config: [...]}` and all. This means several things:

- Your components are keyed (you already need a key for your list of React components anyway). This is how `TransitionSpring` recognizes a missing item and shallow merges in new value and removes old ones (when you instruct it to actually remove it in `willLeave` by returning `null`).

- If your previous render had keys `abc`, and the next one has `cb`, and assuming you've asked in `willLeave` to keep `a` around for animation, the final, diffed, merged order will be `acb`. It could have been `cba` but the current merging algorithm's execution order produces the former. If you really care that much, we can make it pluggable in the future.

- To use the previous example, that means the merging algorithm gives you this new interpolated structure: `{a: ..., c: ..., b: ...}`. Since you most likely will iterate on it through `Object.keys(myInterpolatedStructure).map` for a simple `for-in`, object key iteration order is crucial. But aren't object keys unordered? Fortunately, [they **are** ordered in JS](http://stackoverflow.com/questions/30076219/does-es6-introduce-a-well-defined-order-of-enumeration-for-object-properties).

- Still, why objects and not arrays? Because if it's an array, you'd be forced to provide a key anyways, and your final structure would look so: `[{key: 'a', moreStuff: ...}, {key: 'b', ...}]`. Which isn't much better than the object format. But yes, it _is_ easier to do order-rearrangement with an array than object. Fortunately, your common use-cases are covered:

  + Insert at the beginning: `{newKeyName: myConfig, ...oldObj}`.
  + Insert at the end: `{...oldObj, newKeyName: myConfig}`.
  + Sort/reverse/etc.: lodash and others got you covered. I will also expose a very convenient helper:

```jsx
Spring.utils.orderKeys(myObj, arrayOfKeysFromMyObj => {
  // manipulate the order
  return manipulatedKeysArray;
});
```

Which will return you a new object whose keys have `manipulatedKeysArray`'s order =).

There are other considerations I'll skip over there. But since some people might still find arrays to be neater, we can make this work in the future. It's not a conceptual obstacle. Plus, as an alternative, an array of components makes a lot of sense:

```jsx
<TransitionSpring endValue={[<div key="a"/ >, <div key="b"/>]}>...</TransitionSpring>
```

Imagine receiving the component itself in your `willLeave`... Ahhh the possibilities =D.

### `willEnter/Leave`

Intuitive enough? `willEnter` is called **once** and passed the newly entered key. `willLeave` will be called at **every tick** where `key` is absent from the new data structure, and ask you to either return `null` (kill component for real) or that earlier `yourConfig` part of you data structure so that you can use it to interpolate. Hopefully at this point, the format `key => yourConfig` makes sense.

The implication of this API are important. For one, you're not bound to rendering a flat list (you can use your data structure in any way). For two, you're not restricted by a timer (unlike `TransitionGroup`) that warns you when you don't unmount within `x` seconds (remember what I said in my talk/readme, timer for animation = bad). For three, it enables whole new use-cases for the very concept of transitioning in/out: https://github.com/chenglou/react-motion/commit/8eefb94e98934abfe706dd4202c13906da9fe252#diff-7d11bd20d8f177c821173db584397090R29.

### Closing thought

I dislike operating on an intermediate data structure that's a step before you rendering the actual components. Ideally, the whole React philosophy is that you do the data "tracking" only at the very end, on components themselves rather than the data that generated them. But for the case of unmounting animation, we have to admit that it triggers a bad-case scenario for React's render paradigm (as `TransitionGroup` has shown. But someone please prove us wrong), and that we need to go back a level higher to diff on intermediate data. It's not _that_ much more tedious though. I think this library strikes a good balance.

**Comment by bsansouci** [comment]
I think `config` works nicely for the `Spring`, but is a little annoying for `TransitionSpring` because you can't have it at the top level. This is because the top level object should be a simple mapping key => values. I wrote a little test thing and had this problem immediately. I used a simple array as a value, that I transformed into an object

```js
let arr = ["a", "b", "c"];
// Becomes
let obj = {
  "1": "a",
  "2": "b",
  "3": "c",
}
```

I used that in development mode because I wanted to test out how many items I actually wanted to see, and so I needed to add or remove to my array and have my app not crash. This works very nicely when the order's not that important, but where you're going to want to the things to transition in and out.

Right now the only solution is to wrap every item in `{config: [k, b], val: ...}` which sucks. I really want my spring to be just one way, and I know it won't need to change. I couldn't come up with a better way to express than `<TransitionSpring k={120} b={16} ...rest/>`. 

I know we might not be concerned with perf at the exact moment, but having k and b as constants might enable some internal optimizations. 

Thoughts?

**Comment by chenglou** [comment]
I think your example is misleading. Like we talked about before, writing things out in a scalar manner does have its values, but in practice whatever you pass to `TransitionGroup` will most likely be `map`ped over, in which case adding the `{val: ...}` wrapper is trivial. Hardcoding your array and object isn't very indicative of the common use-case. Plus, you could have used `zipmap(range(), arr)` right? Sure, not available natively, but I think we'll draw the line here: we won't be bloating this library up by providing unrelated things the language is missing and which can be provided by better solutions like lodash (cc @jedwatson who had his share of problems with the classnames repo, lol). We do provide the `reorderKeys(object, newKeyOrderFunction)` helper because otherwise it actually gets ridiculous to manipulate the object key order.

Adding `k` and `b` as props to TransitionSpring will require us to justify 1. Why we didn't add it to `Spring`, or 2. Why we added to `Spring` even though it can wrap the `endValue` with `{val: ...}` just fine. Not sure what your `...rest` is?

The user will do weirder stuff than just providing an extra wrapper around each cell in the object/array in the future. I'm not too worried about the small perf impact.

**Comment by bsansouci** [comment]
Good points. I agree with keeping both springs similar in terms of API. Also having multiple ways of achieve the same thing can be confusing.

**Comment by chenglou** [comment]
Closed because not an issue. But will always welcome questioning of the general API here!

**Comment by Xananax** [comment]
I'm confused.

> But aren't object keys unordered? Fortunately, [they are ordered in JS](http://stackoverflow.com/questions/30076219/does-es6-introduce-a-well-defined-order-of-enumeration-for-object-properties).

However, the link you provide proceeds to demonstrate *the exact opposite*:

> Not as of ES6 / ES2015's final specification. While ES2015 adds property order, it does not require for-in or Object.keys to follow that order, due to legacy compatibility concerns. Other operations, like getOwnPropertyNames, do follow the order, but not for-in or Object.keys.

Though [this conversation](https://esdiscuss.org/topic/nailing-object-property-order) at esdiscuss seems to imply object keys should be ordered in ES6.

Furthermore, even if it constant ordering was to be adopted in ES6, it would still mean our object wouldn't have guaranteed ordering on all platforms where our js is transpiled to ES5, so what good does it do?

Objects are simply not the place to hold ordered data. I'll admit that in practice, all environments seem to effectively keep the order, so it might be more of an academic point...(On a side note, if you are transforming the data anyway, Map keys [do guarantee order](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map#Objects_and_maps_compared)).

On a personal level, the obligation to use objects is a bit of a sore point. I understand the practical reasons, but it pains me to have to have to transform the data I receive from the database, and use as-is throughout my app in dumb components, just for animations. I operate quite a bunch on my data through reusable functions...for arrays. Which means that from `<TransitionMotion>` onward, I can't use them.  
What is even more of a sore point is that most of elements that do enter or leave, not only in my particular use case, but in everyone's (if I am not mistaken), whether todo items, users, or whatever, usually *already have a unique id* that could be used.

This comment is in no way a criticism of your work, that I appreciate, as well as the thinking. I just don't think the use case of having an object that already has a key is so rare as to warrant the transformation and transformation of indexes to keys (and back from keys to indexes when an event bubbles up) of every array that needs animating. I actually think the typical use case would have an id, and even if it doesn't, it's less of a burden to create a `key` property on object creation once, than to transform an array on every render.

**Comment by chenglou** [comment]
@Xananax Thanks for the feedback! And sorry for the late reply. Haven't gotten around this until now.

Due to some newer constraints that I'll be putting onto the style object (can only contain data you need to interpolate, and not random properties such as `todoItemText` that you stuff in there for the sake of piggy backing on the diffing algorithm), I need to reconsider this API and switch to array.

Here's the potential new format:

```js
[{key: 'id1', style: {x: spring(0)}, whateverExtraProps: 'foo'}, {key: 'id2', ...}]
```

Is this more in line with what you have in mind?
(If that's relevant: I can't allow directly storing an array of ReactElements, because `willEnter/willLeave` and others need to be able to read into the style property.)

**Comment by Xananax** [comment]
Yeah, indeed, that's much closer to what I would expect; it allows the API to consume most database objects (which already have an ID) almost directly, and more to the point, do not require to transform from array to object.

I think the new API is much clearer too. It was not very logical to keep those extra properties in `style` anyway.

Thanks for replying!
