### ISSUE TITLE
prettyMatcher recursion detection is inaccurate

### ISSUE THREAD

**Issue by chenglou** [chenglou/react-motion#260]
cc @nkbt 
Not really important but if you have `[a, a]` where a is a reference, it'll mistakenly label the second as `[*RECURSION*]`, since we check the cache but never check whether that reference is embedded inside itself.
We can use a json serializer that supports recursion. I've seen at least one.
Filing this as really low-pri, also to remind us to  check if we can use a pre-made reporter now. I refuse to believe there isn't a pre-made reporter that fits our simple needs so far =).

**Comment by nkbt** [comment]
I see. As far as I know one of matchers I was checking out that time is now actually working fine (was broken). I'll give it a shot
