### ISSUE TITLE
Bower zip option gives 500

### ISSUE THREAD

**Issue by soswow** [chenglou/react-motion#262]
`bower install --save https://npmcdn.com/react-motion/bower.zip` gives 500.
`https://npmcdn.com/react-motion/bower.zip` redirects to `https://npmcdn.com/react-motion@0.3.1/bower.zip` which gives 500

**Comment by soswow** [comment]
`bower install react-motion` worked just fine

**Comment by nkbt** [comment]
The problem is that README is updated, but new version of react-motion is not published =(. So there is not bower.json inside the latest published 0.3.1 version of react motion

**Comment by chenglou** [comment]
New thing's published, but somewhere along the commits the build/ directory is gone. The new release still doesn't work with the CDN.

**Comment by chenglou** [comment]
Nvm, I failed hard trying to publish. Sorry for all the troubles; this has now been fixed for React-motion v0.4.1.

**Comment by NdYAG** [comment]
Sorry for bring this up.
After run `bower install react-motion`, I just got:
```
$ tree bower_components/react-motion
bower_components/react-motion
├── HISTORY.md
├── LICENSE
├── README.md
└── bower.json

0 directories, 4 files
```
version in `bower.json` is 0.4.1

**Comment by chenglou** [comment]
The readme has instructions on how to install from bower. The direct `bower install react-motion` doesn't work anymore.

**Comment by NdYAG** [comment]
Oh, my bad. Thanks, chenglou!
