### ISSUE TITLE
setState when Motion is not mounted

### ISSUE THREAD

**Issue by bbenezech** [chenglou/react-motion#272]
I have a regression 0.3.1 -> 0.4.1

When my Motion component is unmounted while animating, https://github.com/chenglou/react-motion/blob/master/src/Motion.js#L178 triggers setState (it wasn't the case with 0.3.1) with the infamous warning from React in dev mode.

This wouldn't be an issue in itself, but for some reason the code loops like hell, never stops, with 100% CPU and setState warnings keeping coming per the dozen.

I am confident I am in a supported common use case. I just animate a collapse component that can be removed from the DOM at any time.

How can I help?

**Comment by chenglou** [comment]
Eh wow, really? Can you give a small repro? Because we're testing against setting state after the component's unmounted

**Comment by bbenezech** [comment]
Can you show me where the test is so I can troubleshoot a bit myself?

I use a Collapse component forked from react-collapse, maybe you'll see smtg stupid:

```javascript
import React, { Component } from 'react';
import { Motion, spring } from 'react-motion';
import HeightReporter from 'react-height';

class Collapse extends Component {
  constructor(...params) {
    super(...params);
    this.state = {
      height: -1,
      staticRendering: true,
      startsOpen: this.props.isOpened,
    };
  }

  componentWillMount() {
    this.height = '0.0';
  }

  onHeightReady = height => {
    this.setState({ height, staticRendering: false });
  };

  render() {
    const { isOpened, style, children, springConfig, ...props } = this.props;

    const { height, staticRendering, startsOpen } = this.state;
    const stringHeight = parseFloat(height).toFixed(1);

    // Cache Content so it is not re-rendered on each animation step
    const content = (
      <HeightReporter onHeightReady={this.onHeightReady}>
        {children}
      </HeightReporter>
    );

    if (staticRendering && isOpened) {
      return <div style={style} {...props}>{content}</div>;
    }

    return (
      <Motion
        defaultStyle={{ height: startsOpen ? height : 0 }}
        style={{ height: spring(isOpened ? height : 0, springConfig) }}
      >
        {st => {
          this.height = Math.max(0, parseFloat(st.height)).toFixed(1);

          // TODO: this should be done using onEnd from ReactMotion, which is not yet implemented
          // See https://github.com/chenglou/react-motion/issues/235
          if (!isOpened && this.height === '0.0') {
            return null;
          }

          const newStyle = (isOpened && this.height === stringHeight) ? { height: 'auto' } : {
            height: st.height, overflow: 'hidden',
          };

          return <div style={{ ...style, ...newStyle }} {...props}>{content}</div>;
        }}
      </Motion>
    );
  }
}

Collapse.propTypes = {
  isOpened: React.PropTypes.bool.isRequired,
  children: React.PropTypes.node.isRequired,
  style: React.PropTypes.object, // eslint-disable-line react/forbid-prop-types
  springConfig: React.PropTypes.arrayOf(React.PropTypes.number),
};

Collapse.defaultProps = {
  style: {},
};

export default Collapse;
```

What is the easiest way nowadays to build a repro online? Do we have templates?

**Comment by chenglou** [comment]
Codepen is fine. Try this template: http://codepen.io/anon/pen/EPLyLW?editors=0010
Relevant test here: https://github.com/chenglou/react-motion/blob/ffb0628fbea1f4d83a69ea0f6ed910ee64383c76/test/Motion-test.js#L149

(I'll check into this this afternoon)

**Comment by bbenezech** [comment]
- [x] You are awesome

Do not waste any of your free time on this until I find what's what with the test and come up with a repro.
I would feel stupid if I'm the culprit.

**Comment by bbenezech** [comment]
Just tried 0.4.2, no pb. 
I tried again with 0.4.1 to be sure, it failed. 
Look like we had a lucky shoot in the interval!

**Comment by chenglou** [comment]
Weird... there's been no change to `Motion` in the latest release beside an obscure new feature.
