### ISSUE TITLE
disable animations if battery life is low

### ISSUE THREAD

**Issue by jlc467** [chenglou/react-motion#277]
Is there a best practice around disabling animations if battery life is low? I was just testing my app in Safari with 5% battery on Macbook Air and animations were crawling. I suspect Safari has some aggressive battery saving techniques.

**Comment by threepointone** [comment]
not just safari, os x as a whole throttles cpus when it's low on battery (< 10% iirc)

**Comment by jlc467** [comment]
think you are right. 
Animated SVG icons ended up being the culprit, not battery life. Closing this.
