### ISSUE TITLE
fail to add new child to StaggeredMotion collection

### ISSUE THREAD

**Issue by hkjpotato** [chenglou/react-motion#284]
hi. I make this waterfall design template based on the react-motion (staggeredmotion). However, some how I fail to add new child to the original StaggeredMotion collection. Is this a default setting or am I making some mistakes.

The template is like this:
http://kjhuang.com/react/demo/default

The code is like this
https://github.com/hkjpotato/react-waterfall/blob/master/app/components/Main.js

Thank you!

**Comment by hkjpotato** [comment]
I am pretty sure what's the problem now. For StaggeredMotion, the styles props is a function. 
The parameters of that function has a fixed length same as the initial defaultStyles length. Even the defaultStyles array increase its length, the input array length for styles remains unchanged.

**Comment by chenglou** [comment]
Ah, seems like I've accidentally removed that line from the old readme. Yes, StaggeredMotion only works with fixed-length things. To have mount and unmount behaviour you'll need TransitionMotion.

I've pushed a tiny change to readme that says this. This will be auto closed upon push to master. Hope that helps!

**Comment by hkjpotato** [comment]
Thank you. I really like your react-motion module and I just develop a simple app based on it at http://52.24.114.125:3000/
I am not sure if I can add it to the react example demo somewhere online.

**Comment by chenglou** [comment]
Yes you can! https://github.com/chenglou/react-motion/wiki/Gallery-of-third-party-React-Motion-demos

**Comment by hkjpotato** [comment]
Thank you. Also let me know if your team or the other fb teams are looking
for UI developer cause I am going to graduate from Gatech in May. :)

2016-02-23 1:20 GMT-05:00 Cheng Lou <notifications@github.com>:

**Comment by chenglou** [comment]
:+1:

**Comment by chenglou** [comment]
Closing this! Thanks for the question.
