### ISSUE TITLE
willLeave docs seems off

### ISSUE THREAD

**Issue by dozoisch** [chenglou/react-motion#288]
Hi,

[The doc for willLeave](https://github.com/chenglou/react-motion#--willleave-stylethatleft-transitionstyle--style)  specifies

```
- willLeave?: (styleThatLeft: TransitionStyle) => ?Style

Optional. Defaults to () => null. The magic sauce property.

styleThatLeft: the e.g. {key: ..., data: ..., value: ...} object from the styles array, identified by key, that was present during a previous render, and that is now absent, thus triggering the call to willLeave.

Return: null to indicate you want the TransitionStyle gone immediately. A Style object to indicate you want to reach transition to the specified value(s) before killing the TransitionStyle.
```

Is the parameter "value" an outdated param? Or is that supposed to be present. Only thing I seem to get is style, where style represents the full spring

for example
```
{ style: width: { stiffness: 120, damping: 14, precision: 0.01, val: 100 }
```
Val represent the wanted value, not the current, and I can't seem to get the current computed val. Before we could have access to val & velocity.

If it's an outdated param, I can make a PR to update that part of the doc! Just let me know

**Comment by chenglou** [comment]
Oops sorry, yeah it's indeed style, not value.
Please submit the PR against the development branch!
How did you access velocity before?

**Comment by dozoisch** [comment]
Here is an example:

```
  willLeave(key, valueThatJustLeft, endValue, currValue, velocity) {
    const veloTween = velocity[key].tweening;
    const velo = veloTween.config && veloTween.config[0] && Math.abs(veloTween) < 15
```

I don't mind that much about being able to access velocity, but being able to access the value could be useful! Though the new precision param helps.
