### ISSUE TITLE
Make this work on React-Native

### ISSUE THREAD

**Issue by chenglou** [chenglou/react-motion#29]
Should Just Work ™ if we import the correct React.

**Comment by grabbou** [comment]
Any updates? I would love to see it working :) Can help as well as I am currently `into` animations in my app.

**Comment by chenglou** [comment]
I think it's literally just a try catch of require?

@threepointone your spring worked on react-native without changes right

**Comment by grabbou** [comment]
```js
var React;
try{ React = require('react-native'); }
catch(e){ React = require('react'); }
```
from react-springs, will give it a go

**Comment by threepointone** [comment]
Sorry for missing this. The try/catch should work. I didn't try any other workarounds, assuming that react 0.14 will remove this problem.

**Comment by chenglou** [comment]
0.14 React web will remove this problem. It's not clear when react-native will do it.

**Comment by threepointone** [comment]
Redux has a separate module altogether. Problem with both these approaches is that it doesn't solve it for people upstream. Another approach is to `import {SpringFactory} from react-motion; let Spring = SpringFactory(React);` but that's just gross.

**Comment by rt2zz** [comment]
@chenglou is there any way to use the spring interpolation outside of a react component, or at least outside of the render method? In my tests I am getting much better animation performance calling `myRef.setNativeProps({})` rather than modifying component styles. 

I realize this violates the basic declarative principles of the library but something like:

```js
componentDidMount(){
  this.mySpring = ReactMotion.createSpring({val: 0, config: [100, 10]}, (interpolated) => {
    this.refs.someRef.setNativeProps({top: interpolated.val})
  })
}

render(){
  return <Button onPress={() => { this.mySpring({val: 1}) } />
}
```
 Thoughts?

With my current implementation I am getting unpredicable spring action, often indeterminate oscilating. I assume this is because the react-native timer is less reliable. I will try it out with your latest updates and see if that helps.

**Comment by threepointone** [comment]
You could just use rebound-js, or the other new react native animation library http://youtu.be/xDlfrcM6YBk

**Comment by rt2zz** [comment]
ya, if I have to :) FWIW react-motion 0.2.0 greatly improved performance. Looking fast enough for my animations.

**Comment by chenglou** [comment]
@rt2zz react-motion's still in early phase so there's still a lot of perf improvement to be had. If you can profile your app and tell us where the bottleneck is, we can target them better.

(Don't forget to use the prod build of react that strips out the dev conditional blocks correctly.)

**Comment by mrfr0g** [comment]
FWIW changing the require from `require('react')` to `require('react-native')` works on my project.

**Comment by chenglou** [comment]
Works now =).

Building react-motion with webpack currently gives a warning about either `react` or `react-native`. Will be improved in the next version. Leaving this open until then.

**Comment by chenglou** [comment]
Oh yeah, this is solved.

See README: `require('react-motion/native')`

**Comment by phaistonian** [comment]
@chenglou Is there a comparison, performance-wise, between Motion and Animated?

(I am sure there is, I am just a bit lazy to look for any atm :)

**Comment by bsansouci** [comment]
@phaistonian Not officially, I should give it a try. Any ideas how we could accurately benchmark an animation framework?
My guess is that Animated will win because most of it is implemented natively, and they only pay the cost of the communication between JS and native. RM is utterly unoptimized.

**Comment by phaistonian** [comment]
@bsansouci Funny thing, the RN team actually suggested RM (when asked about animation in a recent AMA on Reddit) and not Animated.

Then again, @chenglou is an FBoy as well ;)

**Comment by grabbou** [comment]
Yes, but on the other hand, there was a discussion quite a few months ago about possibilities of offloading Animated animations onto separate thread to make it unaffected by other JS computations going at the time of animation (avoids frame drops).

**Comment by bsansouci** [comment]
@phaistonian because RM is just <3

**Comment by phaistonian** [comment]
Animation is the one that thing that affects RN the negative way.

I am sure it's high in their to-do list getting this done "properly" so that the performance is not affected.

Not sure if Animate is the solution, but (and I am repeating myself here), the API has to be super simple and clear (and Animate's is not).

**Comment by sairion** [comment]
I'm in pain with Animated's API as well (It is too low-level for any practical application, not documented properly, examples are rare, etc). So came here to see any solutions react-motion is providing as the alternative of Animated. But I can see most of the RM examples are not working for RN as well.

I'm not trying to rant, I feel like there needs more works to be done for RN, and just want to make note for anybody looks for similar stuffs. If I make a few RM examples to work on RN, I will post a repo link here afterwards.

**Comment by chenglou** [comment]
> But I can see most of the RM examples are not working for RN as well

The examples should all conceptually work on RN. The differences are in the trivial `ReactDOM.render`, imports, div vs View, etc.

**Comment by bishopZ** [comment]
Yes, I second that. Can you let us know what examples you tried and where
they stopped working?

On Mon, Dec 28, 2015 at 3:30 PM, Cheng Lou <notifications@github.com> wrote:

> But I can see most of the RM examples are not working for RN as well
>
> The examples should all conceptually work on RN. The differences are in
> the trivial ReactDOM.render, imports, div vs View, etc.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/chenglou/react-motion/issues/29#issuecomment-167669857>
> .
>



-- 
________________________________________________________________
================================================================
=--------------------------------------------------------=-===-=-=-====--
+_+~_=_~--+__+=-^=-+_+_=^-+__+-=+_+~__=__~-_-____-=++=_--^-===-=-==-=-=--
=--------------------------------------------------------=-===-=-=-====--

http://bishopZ.com
_______________________________________________________________________

**Comment by sairion** [comment]
@chenglou @bishopZ To elaborate, I may have misstated it as "not working" (I was extremely frustrated to RN when I was commenting so it could be a bit excessive). I did not try to port every demo though, it absolutely works after those changes (`div` to `View`, `button` to `TouchableHighlight`, etc.)! And they are very pleasant to use, compared to Animated. 

However, I have seen some native app folks (who are not really familiar with web techs or React for web) get interested by React Native and get confused by these rather 'trivial' differences after using a few React libs. I thought 'just working' examples can help those kind of people.

**Comment by ahmad2smile** [comment]
@sairion I'm coming from React to React Native but still a working example or just a code snippet for React Native would be a really good thing. As just 1 line in Readme me about that it works with RN 0.18+ isn't really good enough.
