### ISSUE TITLE
changing svg color with spring

### ISSUE THREAD

**Issue by pavel1860** [chenglou/react-motion#291]
is there a way to animate svg fill to change colors with spring?
i tried to do this but the color is only changing at the end of the spring animation and not in a smooth way. just suddenly changing from color A to color B.

**Comment by borkxs** [comment]
Without seeing the code I'm guessing you're trying to transition between to string representations of color?

What you want to do is transition between numeric values and interpolate that into a string `rgba(255,255,${your_value})`

**Comment by pavel1860** [comment]
`<linearGradient id={"grad"+id}x1="0%" y1="0%" x2="0%" y2="100%" >
                             <stop offset="0%" style={{stopColor:"rgba(255,"+g+",0,1)",stopOpacity:1}} />
                             <stop offset="100%" style={{stopColor:"rgba(255,0,0,1)",stopOpacity:1}} />
 </linearGradient>`
where g is the the variable bound to the spring.

**Comment by akre54** [comment]
See also #85 and #153 (particularly @herrstucki's http://bl.ocks.org/herrstucki/27dc76b6f8411b4725bb)

**Comment by bloodyowl** [comment]
`rgba(255, ${ parseInt(g) }, 0, 1)` should work

**Comment by nkbt** [comment]
Please look at https://github.com/chenglou/react-motion/issues/304#issuecomment-331750756 comment.

**Comment by nkbt** [comment]
Also https://github.com/chenglou/react-motion/issues/394#issuecomment-262631976

**Comment by nkbt** [comment]
Added generic issue to cover this case in README: https://github.com/chenglou/react-motion/issues/494
