### ISSUE TITLE
Super laggy performance using Motion and spring

### ISSUE THREAD

**Issue by ffxsam** [chenglou/react-motion#297]
![licecap2](https://cloud.githubusercontent.com/assets/12532733/13545122/8d4b2bf6-e236-11e5-87c3-812d4a6b1a66.gif)

Surely I'm doing something wrong. After I click the stop button, it takes between 2-3 seconds for it to snap back in. Code below:

```
          <Motion style={{y: spring(this.state.playing ? 16 : -46)}}>
            {({y}) =>
              <div style={{zIndex: 2, transform: `translate3d(0, ${y}px, 0)`}}>
                <FloatingActionButton
                  mini
                  onTouchTap={this.stop.bind(this)}
                >
                  <Stop />
                </FloatingActionButton>
              </div>
            }
          </Motion>
```

I also tried just `translateY` instead. No difference.

**Comment by istarkov** [comment]
This is your problem `onTouchTap={this.stop.bind(this)}`
It causes full rerender of `FloatingActionButton`

**Comment by ffxsam** [comment]
Simply having 'onTouchTap' causes re-renders? I don't quite understand. Maybe I shouldn't use this library to animate the button?

**Comment by sompylasar** [comment]
You create a new function object via bind each time the parent component
renders, so onTouchTap value is different from the previous one, and this
causes a re-render.

https://medium.com/@esamatti/react-js-pure-render-performance-anti-pattern-fb88c101332f

**Comment by ffxsam** [comment]
Wow. Had no idea! Thanks for pointing out that really valuable article.
