### ISSUE TITLE
Wasted time in React Perf Tools normal?

### ISSUE THREAD

**Issue by ffxsam** [chenglou/react-motion#299]
![example](https://cloud.githubusercontent.com/assets/12532733/13594292/feeae002-e4b7-11e5-89e6-f898fcefcf57.png)

This is a simple button being animated via CSS transform. Is this normal for `Perf.printWasted()` to show this? It's about 500ms of time wasted each time the button slides.

**Comment by dozoisch** [comment]
You probably have an issue with your FloatingActionButton render method that causes a lot of expansive rerenders.

**Comment by ffxsam** [comment]
Ah yes, it's the Material UI button, not my own code. Thanks.
