### ISSUE TITLE
TypeScript definitions

### ISSUE THREAD

**Issue by mjohnsonengr** [chenglou/react-motion#300]
Do you have any plans of supporting a TypeScript definitions file, or does one exist that is not registered on [typings](http://www.github.com/typings/typings) or not on [DefinitelyTyped](https://github.com/DefinitelyTyped/DefinitelyTyped)?

I found the Flow Types in [Types.js](https://github.com/chenglou/react-motion/blob/026f4d18d3246e14abbf17bef0a9eda536934193/src/Types.js).  This file is very easily converted into a TypeScript definition file, although I understand the pain of maintaining typing information in two separate places.  Maybe a tool could do this automatically.

**Comment by nkbt** [comment]
If you are keen to PR - that would be great. 

I reckon none of maintainers use TypeScript, so it would be near to impossible to validate if everything is good =)

**Comment by mjohnsonengr** [comment]
I opened a repository for this here: https://github.com/mjohnsonengr/typed-react-motion

I'll fill in the d.ts file and put it in the typings registry after work tonight.

**Comment by nkbt** [comment]
Sounds awesome, thanks, @mjohnsonengr!

**Comment by PhilipDavis** [comment]
I wrote one a few days ago. However, I don't have a lot of experience writing d.ts files yet... so go easy if you find errors :).  https://github.com/PhilipDavis/react-redux/blob/master/typings/react-motion/react-motion.d.ts

**Comment by aspirisen** [comment]
+1 TypeScript Defenition would be nice

**Comment by stepancar** [comment]
Hello, i created [defitions](https://github.com/DefinitelyTyped/DefinitelyTyped/pull/8838) 
(shameless copy from flow Types fixed for typescript)
In the future i will add docs to props

**Comment by stepancar** [comment]
@nkbt my PR merged. Now we can use defitnitions, just call tsd
```
tsd install react-motion
```
I think, this issue should be closed

**Comment by chenglou** [comment]
This is great =D, thanks!

I'll add a note in the README. Closing!

**Comment by saberking** [comment]
if typings install react-motion does not work, you have to use typings install --name react-motion
