### ISSUE TITLE
New item does not appear in TransitionMotion when used in staggered mode

### ISSUE THREAD

**Issue by PhilipDavis** [chenglou/react-motion#303]
Thanks for this really cool library! I'm having a lot of fun playing with it.

Now... I'm just learning React-Motion and it's super late at night... but I'm quite sure that items added to my list are not appearing in the TrasitionMotion when I pass styles={ (prevInterpolatedStyles) => ... }

Is this by design (it appears that StaggeredMotion has the same limitation -- #284)?

I'd be willing to accept the restriction that items can't be inserted/removed until after the initial animation has completed.

**Comment by PhilipDavis** [comment]
I was doing it incorrectly.

**Comment by epiqueras** [comment]
How did you resolve this? I am running into the same issue.

**Comment by PhilipDavis** [comment]
@epiqueras Sorry, this was over a year ago and I didn't end up using the code in production. I don't recall. However, I do remember something about getting a null array from react-motion... I coalesced it with a valid array and that got me past the issue. Good luck.
