### ISSUE TITLE
Preventing initial animations

### ISSUE THREAD

**Issue by brigand** [chenglou/react-motion#306]
I have a simple slide-in animation for a menu. The catch is that I need to measure the menu size to be able to animate it in.

Is there a way to make it not animate until after I have the height and `isOpen` is true for the first time?

If there isn't, maybe a prop should be added that allows me to prevent animation. Then I'd be able to set a flag in state from `componentWillReceiveProps`.

```js
export class TopBarDropdown extends React.Component {
  // default it to some high number
  state = {height: 1000};

  handleRef = (ref) => {
    if (!ref) return;
    var el = ReactDOM.findDOMNode(ref);
    this.setState({height: el.offsetHeight});
  };

  render() {
    var {isOpen} = this.props;

    var top = !isOpen ? -this.state.height : 5;
    return (
      <Motion
        defaultStyle={{top: -this.state.height}}
        style={{top: spring(top, presets.gentle)}}
        children={({top}) => {
          return (
            <Box
              ref={this.handleRef}
              style={{top: Math.floor(top) + 'px'}}
            >
              {this.renderItems()}
            </Box>
          )
        }}
      />
    );
  }
```

**Comment by sompylasar** [comment]
@brigand Have a look at this module: https://github.com/nkbt/react-collapse -- it does exactly what you need (measures and then animates).

**Comment by brigand** [comment]
It works there because it always animates from 0. In this case I need to animate from -height.

**Comment by sompylasar** [comment]
@brigand You could start with `visibility: hidden` and only switch to `inherit` when the height is ready. Also, the default `top` value could be very far away (like `-999999px` -- you'll never have such height of your content).

**Comment by brigand** [comment]
That'd only set it to be hidden for part of a frame. But along that line, I could set it to be `visibility: hidden` until the first time it's set to open. It's still going to waste a lot of performance running the animation pointlessly though. It's a good enough solution for now, thanks :-)

If I use an extreme value like that it's going to bounce around for a long time (using presets.gentle which has some bounce). That's why I figured stopping the animation, or forcing it to immediately settle, would be a decent solution. Maybe I can do that with some high value for stiffness or damping. I'll play around with it some more.

**Comment by sompylasar** [comment]
@brigand Measuring the height has more impact on performance than switching visibility (layout vs paint). By the way, CSS `top` also triggers layout, which is a performance impact.
https://csstriggers.com/

**Comment by sompylasar** [comment]
When you use the extreme value, you should not perform animation. First, reset the extreme value to `-height` and `visibility` to `inherit` (when the height is ready), then start the animation.

**Comment by brigand** [comment]
I don't know how to "not perform animation". If I can do that, it'd solve the issue entirely.

**Comment by sompylasar** [comment]
@brigand Put a number instead of a `spring()` in `style`, it should jump to that value immediately.
https://github.com/nkbt/react-collapse/blob/master/src/Collapse.js#L62-L65

**Comment by sompylasar** [comment]
@brigand Interesting article on animation performance [in a neighboring thread](https://github.com/chenglou/react-motion/issues/263#issuecomment-200297509): https://aerotwist.com/blog/flip-your-animations/ -- you might be interested.

**Comment by brigand** [comment]
@sompylasar passing a value without the spring works perfectly. Thank you so much!
