### ISSUE TITLE
TransitionMotion + Redux + React-Motion

### ISSUE THREAD

**Issue by compoundpaths** [chenglou/react-motion#307]
```
Error: Objects are not valid as a React child (found: object with keys {AGR}). If you meant to render a collection of children, use an array instead or wrap the object using createFragment(object) from the React add-ons. Check the render method of `TransitionMotion`.
```
Collections rehydrated through redux seem to be causing this error with the TransitionMotion component.  Strangest thing, when mapped - still causes error.  But when spliced, when not the length of the array, it seems to render properly.  Any insight here? ES6 setup.

**Comment by sompylasar** [comment]
@compoundpaths Could you also provide your piece of code that uses TransitionMotion?
And Redux does not do rehydration, it's something else in your code that does it.

**Comment by compoundpaths** [comment]
@sompylasar rehydrate was a poor choice of words, meant just updating the collection.  turns out one of my collection items had an outdated key that was mucking everything up.  False alarm.

Thanks for the quick response though, closing this issue.
