### ISSUE TITLE
Switching between browser tabs

### ISSUE THREAD

**Issue by chtefi** [chenglou/react-motion#31]
Hi,

Thanks for this awesome lib.

I stumbled upon something suspect when switching between browser tabs while an animation is on.
The following code simply renders an interpolated value (0 at first, then 300 after 1s) and use it in a  `transformX` as well.
Everything works fine.

Until you switch your browser tab, come back to it, switch, come back etc. The value keep changing/bouncing a lot at each switch (due to the low damping it seems? 5 in this example)
Is that expected?

![](http://i.gyazo.com/cf5489de99ba953fb22d5ea81efa8d4e.gif)

```javascript
export default class App extends React.Component {
	constructor() {
		super();
		this.state = { value: 0 };
		setTimeout(() => this.setState({ value: 300 }), 1000);
	}
	render() {
		return (
			<Spring endValue={{val: this.state.value, config: [ 100, 5 ] }}>
		  		{interpolated => <div style={{
              		 	  transform: `translateX(${interpolated.val}px)`,              
           	 	}}>{~~interpolated.val}</div>}
			</Spring>
		);
	}
}

```

PS: I'm running on Chrome 44 Windows.

**Comment by KyleAMathews** [comment]
Browsers throttle requestAnimationFrame (what react-motion uses to power its animations) significantly when a tab is inactive ([this thread](http://greensock.com/forums/topic/9887-tween-paused-when-switch-to-other-tabs/) says ~2 frames/second).

I think the normal thing to do here is to pause the animation when you detect the user leaves the tab and restart it when they return.

**Comment by KyleAMathews** [comment]
Though it'd be cool if react-motion could handle this somehow automatically.

**Comment by nkbt** [comment]
It is fairly easy to check if tab is in foreground or background. I'll have a look today (after work) what could be done if no one fixes it before that

**Comment by chenglou** [comment]
What's really the desired behavior here? Slow down or stay at the same speed?

**Comment by nkbt** [comment]
I am pretty sure animation should freeze and resume when we are back.

>

**Comment by chenglou** [comment]
Well maybe this is a bad analogy, but we don't do the same with sound right? And what's really "going away", does losing focus by switching to another app (while the screen is still partially visible) count? Because if so it seems that continuing the animation's the way to go? Not talking about technical details here.

**Comment by nkbt** [comment]
Analogy with sound is not that straight. You cannot see animation when tab
is not visible. Background tab is an issue though. Visible **and**
inactive.

If animation is very long, it makes sense not to burn cpu, but they are
actually quite short, so the idea of animating in background seems ok to me.

You can check Date.now() inside raf to align animation. If it is more then
finish, then just set the last value.

**Comment by nkbt** [comment]
This could be optional. For some cases you want to stop animations completely when in background and for most cases - keep going.

Since I don't like configuration and prefer composition, maybe it could be some component-wrapper like ```js
<StopInBackground>
  <ReactMotion>{}</ReactMotion>
</StopInBackground>
```

**Comment by iclanzan** [comment]
@nkbt We don’t know the duration of animations ahead of time so as to “align” it or set the last value. Each step is computed from the values of the previous one. Best we can do is try to compute multiple steps to catch up the lost time. If the time lost is too great and would take too many steps to catch up then we have two options: **pause** or **end** the animation.

If down the road we want to support physics models other then just springs we might not even know the end value. Think of something like momentum scrolling where you don’t know beforehand what the end position is. As such I would suggest we go with pausing.

I am working on decoupling the stepping function from rendering and it will among other things solve this problem.

**Comment by chenglou** [comment]
> If down the road we want to support physics models other then just springs we might not even know the end value. Think of something like momentum scrolling where you don’t know beforehand what the end position is. As such I would suggest we go with pausing.

@iclanzan I want the Decay component actually, so yes, that makes sense. Pausing it is.
(Also, looking forward to decoupling the stepping function!)

**Comment by bsansouci** [comment]
:+1:

**Comment by chenglou** [comment]
@chtefi to clarify: tldr yes this is a bug, because the time delta gets screwed up. This will be fixed hopefully soon.

**Comment by chenglou** [comment]
#57 =)
