### ISSUE TITLE
Integer as key

### ISSUE THREAD

**Issue by martolini** [chenglou/react-motion#315]
Style is requiring a string to be the key. Is this really necessary? Sounds better performance wise to be able to use numbers as well.

**Comment by chenglou** [comment]
The numbers will be cast into strings anyway; I'm not too sure about the current impact of using number-casted-to-string keys in objects on modern engines. Also, see this: https://github.com/chenglou/react-motion/pull/309#issuecomment-212152473

I'll close this issue favor of keeping track of this in that PR. Might reconsider things in the future =].
Thanks!
