### ISSUE TITLE
React 15.0 support?

### ISSUE THREAD

**Issue by sompylasar** [chenglou/react-motion#317]
It's already RC2: https://facebook.github.io/react/blog/2016/03/16/react-v15-rc2.html

**Comment by nkbt** [comment]
Should not be a problem I am pretty sure, since there are no deprecated APIs being used...

PR to peerDependencies if you are keen (well, with good amount of testing of course) and we should be good then.

```
    "react": ">=0.13.2 || ^0.14 || ^15.0.0-rc",
```

**Comment by nkbt** [comment]
If not, I am going to update it in next days (when I will actually work on UI animation on my current project)

**Comment by sompylasar** [comment]
@nkbt Thanks! For now I have to delay the upgrade to React 15.0 on my project because a lot of modules haven't updated their dependencies yet, so it would be nice if you have such opportunity with `react-motion` earlier.

**Comment by nkbt** [comment]
@sompylasar We updated to 15-rc1 as soon as it came out. Had no issues at all. All other modules simply throw `PEERINVALID` error on npm install but work totally fine. 

I reckon it must depend on what sort of 3rd party modules you rely on, and if some declare React as `dependency` or rely on deprecated features - then 😿

**Comment by sompylasar** [comment]
@nkbt I see, well, I tend to avoid the warnings, they are there for a reason, even if they can be tolerated and everything looks fine at first sight.

I'll give it some time to settle, and get back to it, probably there will be RC3 at that moment, or even a release version -- who knows. `react-redux`, for example, has strictly specified `15.0.0-rc.1`, so I can't use the `15.0.0-rc.2` without the warning, although the latter has several major bugs fixed.

**Comment by nkbt** [comment]
We should just PR to every lib we use hehe ;)

**Comment by nkbt** [comment]
Reopen until new version published

@chenglou can you please release new `patch` version (since it is `0.x.x` now)?

**Comment by chenglou** [comment]
Will do it this weekend. Time to come back to this.

**Comment by nkbt** [comment]
Maybe worth going full semver and publish 1.0.0? ;)

**Comment by chenglou** [comment]
1.0.0 will have to wait because I want to get static, single component unmounting in (unmount for `Motion`, which is a large use-case of people doing unmounting animation). Tracked in #311

**Comment by chenglou** [comment]
Published as v0.4.3. Also I have no idea how semver works but hey, no breaking changes!

Sorry for the long wait everyone!

**Comment by nkbt** [comment]
Awesome, thanks!
