### ISSUE TITLE
Random key in TransitionMotion or StaggeredMotion causes memory leak

### ISSUE THREAD

**Issue by julienvincent** [chenglou/react-motion#321]
If the `key` option in `TransitionMotion` or `StaggeredMotion`'s styles prop is randomized, a memory leak will freeze the application. This is understandable, however might be a good idea to mention this in the docs

**Comment by chenglou** [comment]
Hmm, what's the use-case for this? The `style` object should be treated as an record, not a hash map. I guess we could mention that? Most people probably use RM the way they use `style` prop in React though.

**Comment by julienvincent** [comment]
For instance:

```javascript
TransitionMotion({
    styles: [{style: {opacity: spring(1)}, data: {}, key: Math.random()}]
},
    styles => (
        ...
    )
)
```

I'm assuming what's going on here is every time `styles` is fetched/called, it gets back an array with a different id and so so attempts to mount a new DOM node and unmount the old. Seeing as `styles` gets called multiple times - this quickly escalates and crashes the browser.

Just something I found by accident while fiddling with RM - this isn't a very serious issue at all, just thought I'd let you know.

**Comment by chenglou** [comment]
Oh, then this respects what React does. If you generate a random `key` prop each time then your component _will_ be thrashed. In our case here we have a few edge-case usage for this semantics that I'd rather not mention. If your `key` changes then the component will unmount and that's probably what you're trying to do (I'm assuming that this `key` is transferred as the actual React `key` prop onto your component).

Thanks for clarifying this. I think this is rare enough (and sometimes has legit use-cases) not to warrant a mention in the README =].

(Closing!)
