### ISSUE TITLE
Cannot download via bower (instructions)

### ISSUE THREAD

**Issue by garrettmaring** [chenglou/react-motion#329]
When running 'bower install --save https://npmcdn.com/react-motion/bower.zip' bower shows these messages:

```
bower bower#*               not-cached https://npmcdn.com/react-motion/bower.zip#*
bower bower#*                  resolve https://npmcdn.com/react-motion/bower.zip#*
bower bower#*                 download https://npmcdn.com/react-motion/bower.zip
bower bower#*                    EHTTP Status code of 500
```

Then when visiting the URL `https://npmcdn.com/react-motion/bower.zip` I see the following:

"Server error: ENOENT: no such file or directory, lstat '/tmp/npm-http-server-react-motion@0.4.3/tmp/npm-http-server-react-motion@0.4.3/bower.zip'"

**Comment by nkbt** [comment]
NPMCDN has broken `bower.zip` recently: https://github.com/mjackson/npm-http-server/issues/37

**Comment by nkbt** [comment]
Fixed now.
