### ISSUE TITLE
Animate between 2 differents components

### ISSUE THREAD

**Issue by moimael** [chenglou/react-motion#337]
Hi,

Do you have some example to show how to do a simple fadeout / fadein when unmounting a react component and replacing it with another (different) one ?
From the demos and documentation I cannot understand how to do it, items are always similar.

Thanks !

**Comment by mvoloz** [comment]
@moimael you can use the RouteTransition guides, its essentially the same thing, just pass your component in as a child of RouteTransition.  The examples at https://github.com/chenglou/react-motion/issues/130 were very helpful.
