### ISSUE TITLE
Test the perf of CSS keyframes

### ISSUE THREAD

**Issue by chenglou** [chenglou/react-motion#34]
The idea is to maybe have a constrained API in the future that allows compiling to CSS keyframes instead of using rAF + render. cc @sahrens who'll probably find this relevant.

I've decided to stop theorizing about CSS keyframes' perf vs manipulating DOM + setting style properties vs React + render + setting inline style. Latter will most probably be slower but hey, 1. always need real data to talk about perf, 2. if it's really slower, I want to see how much slower and whether it's worth orienting the API toward the former 2. Relevant post: https://css-tricks.com/myth-busting-css-animations-vs-javascript/

I'll try the perf of React render vs CSS keyframes first. The second method of manipulating DOM and setting style is less worth the trouble of testing, because React-Motion's bottleneck is also there anyway.

I'm actually not sure what'd be an accurate way of testing this. @sahrens did you measure the perf gain from using Core Animation instead of render?

**Comment by sahrens** [comment]
It's not so much about microbenchmark a comparing the approaches head-to-head as it is about the macro system. If you're relying on react render to animate (say, a custom spinner) and want to also do something expensive in JS (say, render a large network response), then your animation is going to stop while that's happening (unless you do a bunch of work to time-slice the expensive operations).

That said, it would be interesting/valuable to push the limits of pure animations with both systems. A good way to do that is to increase the complexity (e.g. number of elements being animated simultaneously) until you start dropping frames, and compare that maximum complexity between the two approaches.

**Comment by chenglou** [comment]
:+1: Closing for now =).

**Comment by mattvague** [comment]
> If you're relying on react render to animate (say, a custom spinner) and want to also do something expensive in JS (say, render a large network response), then your animation is going to stop while that's happening

I've definitely run into this with my react-motion implementations (not ragging on react-motion at all though, it's amazing!)

@chenglou I might have some time coming up to play around with this CSS keyframe as a way to prevent the blocking of animation frames. Any advice on how to get started?
