### ISSUE TITLE
Conditional Animation

### ISSUE THREAD

**Issue by kujon** [chenglou/react-motion#355]
Hello,

I'm using https://github.com/uber/react-map-gl, which in short is a fully stateless map component. On each scroll, drag, etc, it will flood you with calls to the callback indicating viewport change and you have to handle map updates yourself. That works super nicely and super smoothly. However, I sometimes need an external component to provide the map with, let's say a new centre point, and I would like to transition to it nicely (I can determine when to do it based on checks in `componentWillReceiveProps` and I can determine when to disable this functionality, by using `onRest`.

Is there a way of conditionally disabling an animation? (see below for a crap solution describing what I'm after):
```javascript
const {viewport} = this.props;

const renderMap = viewport => <Map {...viewport} />;

if (shouldAnimate) {
  return <Motion style={createMotion(viewport)}>{renderMap}</Motion>
} else {
  return renderMap(viewport); 
}
```

The problem with the above is that Map gets recreated whenever I enable/disable animation.

**Comment by nkbt** [comment]
I usually do something like:

```jsx
import {spring, Motion} from 'react-motion`;

// somewhere in component
maybeSpring() {
  return this.state.shouldAnimate ? spring : (x => x);
}

render() {
  return <Motion style={{top: this.maybeSpring(100)}}>
  // ....
}

**Comment by kujon** [comment]
That is one brilliant solution, thx!
