### ISSUE TITLE
Warning: Failed propType: Invalid prop 'styles' supplied to 'TransitionMotion'.

### ISSUE THREAD

**Issue by shruti-prasad** [chenglou/react-motion#359]
I am getting the following warning while using InterpolatedStyles Warning: Failed propType: Invalid prop 'styles' supplied to 'TransitionMotion'.

**Comment by sanpojoe** [comment]
I was getting the same until I figured out what I was doing, it needs to be an array of objects

**Comment by chenglou** [comment]
Yep. https://github.com/chenglou/react-motion#--styles-arraytransitionstyle--previousinterpolatedstyles-arraytransitionplainstyle--arraytransitionstyle

Sorry for the confusion!

**Comment by shruti-prasad** [comment]
I am still getting the warning despite using an array of objects. I tried replicating the styles format as given in the example in the above link.

**Comment by quangbuule** [comment]
Getting this warning and I don't have any clue:
![image](https://cloud.githubusercontent.com/assets/5992964/22228756/c44c853a-e205-11e6-8766-7b67844fbe00.png)
My styles prop seems satisfy this validation https://github.com/chenglou/react-motion/blob/master/src/TransitionMotion.js#L195

**Comment by cavaloni** [comment]
I am having the same problem. Did you find a fix?

**Comment by pangpond** [comment]
I fix this warning by add string to key name. eg.

```
key: `k${index}`
```

<img width="252" alt="screen shot 2560-03-11 at 7 37 40 pm" src="https://cloud.githubusercontent.com/assets/943742/23823301/3c265d6e-0692-11e7-9ffd-e4d520071370.png">

**Comment by smoliver** [comment]
@pangpond Thanks.  switching from an integer key to a string key did the trick for me.  @chenglou is there any particular reason for not allowing integer based keys?

**Comment by willmeierart** [comment]
I struggled with this for awhile, turns out passing a property that can't be interpolated (overflow: 'hidden') will throw the error too.

**Comment by babarali581** [comment]
@pangpond  Thank you so much. I had same issue I solve this by adding my value in between `k${}`
