### ISSUE TITLE
Animation not smooth on React Native - Android

### ISSUE THREAD

**Issue by shoumma** [chenglou/react-motion#360]
Hi, I'm using react-native 0.30 with android API 23. I have facing issue with smoothing animations. The library works very well with ReactJS in browser. But on react-native, it looks like some noticeable frame drops occurs. In other word, the animation is not very smooth as it is in browser. Am I missing something here? Is there anything need to be added to make animations smooth with react native?

I have also test it on devices to make sure that it's not my emulator causing the problem.

**Comment by chenglou** [comment]
Android probably has a rough time. Have you tried Animated on native?
Also, it helps to freeze subtrees while the animation's happening.

**Comment by shoumma** [comment]
Yes, I did get the job done with Animated library. But your library is also awesome.

**Comment by chenglou** [comment]
Thanks! =)
Well, I'll mark this as solved and close this then. Sorry for giving you a hard time with perf.
