### ISSUE TITLE
Translate Y Animation Doesn't Work Transition Motion

### ISSUE THREAD

**Issue by realseanp** [chenglou/react-motion#363]
Can't figure out how to animate translateY. When replacing the value with top it works fine. 

```
    willEnter = () => {
        return {
            translateY: 100
        };
    }
    render() {
        const boxAttrs = {
            className: 'col-xs-12 col-md-4 intro-box',
        };
        return (
            <div className="intro">
                    <TransitionMotion
                        willEnter={this.willEnter}
                        styles={this.props.items.map(item => ({
                            key: item.key,
                            style: { translateY: spring(0) }
                        }))}>
                        {interpolatedStyles =>
                        <div className="row">
                            {interpolatedStyles.map(config => {
                                return <div {...boxAttrs} key={config.key} style={{...config.style}} />
                            })}
                        </div>
                        }
                    </TransitionMotion>
            </div>
        );
    }
```

**Comment by chenglou** [comment]
Check the value in the DOM. translateY, for a react style, needs to be a string, right? `{transform: 'translateY(' + config.translateY + 'px)'}`

Hope that solves it!

**Comment by ticruz38** [comment]
I do have the same problem, none of the transform property are supported
`style: { transform: `translateX( ${spring(0)}px )` }`
this give me an invalid styles supplied to TransitionMotion, though it's valid react style props

**Comment by mhaagens** [comment]
In case anyone else didn't really get it the first time you need to declare the styles explicitly;

```
 <div className="page"
 key={config.key}
 style={{opacity: `${config.style.opacity}`, transform: `translateY(${config.style.translateY}px)`}}>
```

**Comment by ticruz38** [comment]
Sure! but still the transform property doesn't apply, I had to use a left property and positioning my element absolutely in order to get the animation I wanted...

**Comment by mhaagens** [comment]
Here's how I use it for route transitions with translateX;
https://gist.github.com/mhaagens/61f88e3fbfddbe2c00708f3ebd099be4

**Comment by eemebarbe** [comment]
You have to use their transforms method:

[](https://facebook.github.io/react-native/docs/transforms.html)
