### ISSUE TITLE
Possible npm publish issue

### ISSUE THREAD

**Issue by JEGardner** [chenglou/react-motion#369]
Hey,

I'm still getting a mounting setstate bug which was fixed in commit https://github.com/chenglou/react-motion/commit/49ea396041b0031b95f4941cc7efce200fcca454

Inspecting my node modules, it looks as if these changes appear in src/ but not in lib/

Is there a chance this was published to npm without running prerelease?

**Comment by chenglou** [comment]
Just published a new patch version 0.4.5. Hope this works!
