### ISSUE TITLE
Possibility of elastic animation with boundaries?

### ISSUE THREAD

**Issue by webondevices** [chenglou/react-motion#402]
I was wondering if it was possible to create an element dragging animation/interaction with react-motion to simulate a pinned down state with elastic boundaries.

Imagine you have an element in the middle that is pinned to a fixed position. You can start dragging it but the further away you try to drag it from the pin position the least it moves: like if it was tied to a rubber band. When you release it goes back to the pin position with the spring animation.

**Comment by sompylasar** [comment]
Yes, I would implement the motion you described in two parts:
1) the dragging motion when the item follows the pointer with a certain friction;
2) the release motion when it gets back;

On component mount I would store the initial coordinates of the item, and set the component state to be "returning" (a plain string for the current part of the animation).

On pointer down I would set the state to "dragging", and set the current desired coordinates to the pointer coordinates in the component state. If you'd like to animate the initial transition from the rendered coordinates to the current effective coordinates, you'd need an additional flag to fade out such animation when the dragging takes over.

On pointer move, if the state is "dragging", I would update the current desired coordinates with the pointer coordinates. In render, if the state is "dragging", the 1) would be a direct mapping of the current desired coordinates to the item coordinates with an euclidean-distance-based friction coefficient, no spring required unless you'd like to animate the initial move to the pointer coordinates.

On pointer release I would update the state to be "returning" and the current desired coordinates to equal the initial coordinates. In render, if state is "returning", the 2) would be a regular spring motion to the initial item coordinates.

**Comment by webondevices** [comment]
Thank you @sompylasar, that's really helpful.

I managed to get most of this done:
http://codepen.io/mares0909/pen/jVYrye

The only thing I'm not sure how to implement is the euclidian distance-based friction. Would you be able to fork that pen and add it to the example? Or push me into the the right direction with that?

**Comment by sompylasar** [comment]
Sort of:
```
dx = (pointerX - initialX);
dy = (pointerY - initialY);
distance = Math.sqrt(dx*dx + dy*dy);  // https://en.wikipedia.org/wiki/Euclidean_distance
angle = Math.atan2(dy, dx);
decay = 0.05;
actualX = Math.cos(angle) * distance * decay;
actualY = Math.sin(angle) * distance * decay;
```

**Comment by sompylasar** [comment]
Yes, it works (slightly edited [my comment](https://github.com/chenglou/react-motion/issues/402#issuecomment-264336836)): http://codepen.io/anon/pen/zopWGQ

**Comment by webondevices** [comment]
@sompylasar , that is perfect, thank you!!
