### ISSUE TITLE
Transform translate style property, do not render properly in the dom

### ISSUE THREAD

**Issue by ticruz38** [chenglou/react-motion#406]
I am struggling to use any transform property in my style object. I would like to know if there is a specific notation inside react motion to support it.
here is my code:
```
    willLeave(args) {
        return {
            transform: `translate3d(${this.props.translation}px, 0, 0)`
        };
    };

    willEnter() {
        return {
             transform: `translate3d(${-this.props.translation}px, 0, 0)`
        };
    };

    getStyles(children) {
        return [ {
            data: children,
            key: children.type.motionKey,
            style: { transform: `translate3d(${spring(0)}, 0, 0)` }
        } ];
    };
```

Using the same thing with the left property is working fine, but the performance are too bad. So I would really like to use transform instead.
In my Dom I get the transform property rendered like this:

> transform:translate3d(-280px, 0, 0)NaNNaN;

**Comment by souporserious** [comment]
React Motion can only interpolate a number. So instead of passing
```js
transform: `translate3d(${-this.props.translation}px, 0, 0)`
```
you should pass
```js
transform: this.props.translation
```
then in your render method you can apply it using `translate3d`.
