### ISSUE TITLE
Is it possible to specify unit of measurement in TransitionMotion?

### ISSUE THREAD

**Issue by mocheng** [chenglou/react-motion#418]
In the TransitionMotion example https://github.com/chenglou/react-motion/#transitionmotion- , both `willLeave` and `styles` prop initialization in <TransitionMotion> has `height` value as number. There is no unit of measurement. It looks `react-motion` treat it as px. Is there any possibility to choose "em" or other units?

**Comment by souporserious** [comment]
Yes, you can provide whatever you want. For example:

```
<Motion defaultStyle={{ height: 0 }} style={{ height: spring(10) }}>
  { value => <div style={{ height: value.height + 'em' }}>Content</div> }
</Motion>
```
