### ISSUE TITLE
Curly braces in callback

### ISSUE THREAD

**Issue by averykimball** [chenglou/react-motion#427]
Forgive me, since the answer to this question will be about general Javascript knowledge, but I had not run into this problem before using react-motion.

In the simplest example:

```javascript
import {Motion, spring} from 'react-motion';
// In your render...
<Motion defaultStyle={{x: 0}} style={{x: spring(10)}}>
  {value => <div>{value.x}</div>}
</Motion>
```
Which works for me, if I put _curly braces_ around the body of the callback thus:

```javascript
import {Motion, spring} from 'react-motion';
// In your render...
<Motion defaultStyle={{x: 0}} style={{x: spring(10)}}>
  { 
     (value) => { <div>{value.x}</div> }
  }
</Motion>
```

I get an invariant violation. Am I misunderstanding what is happening here? If I explicitly return the element, I don't get the invariant violation, but the animation doesn't work.

Thank you for your patience, but some of the nuances of es2015 must be escaping me!

**Comment by averykimball** [comment]
Never mind, I'll hit up SO.

**Comment by nkbt** [comment]
@averykimball you forgot `return`. Curly braces mean that you declare function body that does not have implicit return, so you must add one.

```
import {Motion, spring} from 'react-motion';
// In your render...
<Motion defaultStyle={{x: 0}} style={{x: spring(10)}}>
  { 
     (value) => { return <div>{value.x}</div> }
  }
</Motion>
```
