### ISSUE TITLE
ESLint react/forbid-component-props rule fails 

### ISSUE THREAD

**Issue by eladmoshe** [chenglou/react-motion#431]
react-motion requires using `style` property on the `Motion` element. 
Due to this name selection, ESLint rule [react/forbid-component-props](https://github.com/yannickcr/eslint-plugin-react/blob/master/docs/rules/forbid-component-props.md) fails. Since this is a highly useful rule, it would be great to have a way of working with react-motion without disabling this rule.

I understand that this is impossible to change the current API without breaking existing applications. One possible workaround is adding another prop name with the same functionality (e.g. styleProps). For example:
```javascript
<Motion styleProps={{x: spring(10)}}>
  {value => <div>{value.x}</div>}
</Motion>
```
Would be equivalent to
```javascript
<Motion style={{x: spring(10)}}>
  {value => <div>{value.x}</div>}
</Motion>
```

**Comment by nkbt** [comment]
I think you should disable thus rule. I don't believe anyone would change component's API because of absolutely arbitrary lint rule.

**Comment by nkbt** [comment]
Alternatively, wrap motion into your own component with renamed prop and use it in your project. So you will need to disable rule only in that component.
