### ISSUE TITLE
Simulate scrolling effect with Motion

### ISSUE THREAD

**Issue by petromoldovan** [chenglou/react-motion#438]
hello guys!

first of all, thank you for your work! amazing package!

I am looking for a way to simulate scrolling behavior by passing starting and end locations to child element. Inside of child element I update the scrollTop property of that child element to simulate scrolling effect.

```
<Motion
  defaultStyle={{y: START}}
  style={{y: spring(END, transitionOptions)}} >
  { interpolatedStyle => {
    return (
      <ContentLayout scrollTo={interpolatedStyle.y} />
    );
  }}
</Motion>
```

The problem is that I cannot pass the starting point(var `START`) of the animation. Per documentation `defaultStyle` works only once and afterwords the previous interpolated value is taken as starting point. 

Could anyone suggest a workaround? Would really appreciate it.

thank you!

**Comment by wgoto** [comment]
I think you're thinking about this implementation slightly wrong. You should just be passing one value at which your component should be scrolling to at any given point. Your parent component should be handling the `START` vs `END` logic. It could be as simple as sending the motion component a start value, then creating a timeout to send the motion component your end value.

**Comment by petromoldovan** [comment]
@wgoto thanks for the answer!

could you elaborate a bit on it? maybe you have some old snippets that you did already? would really appreciate it.

**Comment by sompylasar** [comment]
Look here: https://gist.github.com/sompylasar/8b787c3fcfe0e14bba869a4e9a883135#file-viewport-js-L284-L320

**Comment by petromoldovan** [comment]
@sompylasar thank you!
