### ISSUE TITLE
Apply changes to the Spring component itself

### ISSUE THREAD

**Issue by salzhrani** [chenglou/react-motion#44]
Is it possible to apply the animation on the Spring component itself (eg: setting the style on the Spring component), the reason is to make use of the component dom node.

**Comment by nkbt** [comment]
@salzhrani yes, all props passed to Spring are applied to rendered div.

```js
    return (
      <div {...this.props}>
        {this.props.children(currVals)}
      </div>
    );
```

**Comment by salzhrani** [comment]
I wanted to say that I wanted to apply the spring value to the generated div. currently the calculated spring value is passed to the child function which I am not sure how apply it to the div generated by `<Spring>`

```
<Spring {...props} endVal={{ val: /* some value */}}>
    { ({val}) =>
        // Like to apply style={{opacity: val}} to the div generated by spring
        // setState ?
    }
</Spring>
```
Sorry If I am not making any sense

**Comment by chenglou** [comment]
I'm not sure why you'd want to do that? The `div` used by spring is really just something used to circumvent the fact that React can currently only return one child. It's invisible anyway. You could apply it on the inner div you provide if you want: `<Spring ...>{val => <div style={...} />}</Spring>}`.

**Comment by salzhrani** [comment]
I might be stingy with divs ... but I guess one more wouldn't hurt ...
Thanks.

**Comment by gaearon** [comment]
Why does `Spring` *always* have a `div`?

I'd rather go the opposite route: enforce `React.Children.only` on the `children` result. If people want a `<div>`, they'll pass it, otherwise they may pass something else.

**Comment by chenglou** [comment]
Hah, good point!

**Comment by salzhrani** [comment]
Whoa ... thanks
