### ISSUE TITLE
Migrate from React.createClass

### ISSUE THREAD

**Issue by sjogren** [chenglou/react-motion#448]
If [React v15.5.0](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html) is used you get the following warning:

`Warning: Motion: React.createClass is deprecated and will be removed in version 16. Use plain JavaScript classes instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement.`

See [Migrating from React.createClass](https://facebook.github.io/react/blog/2017/04/07/react-v15.5.0.html#migrating-from-react.createclass).

**Comment by olegkogan** [comment]
The same thing.

**Comment by MichaelDeBoey** [comment]
Dupe of #445
