### ISSUE TITLE
willEnter spring fails to happen after focusing a new tab or window

### ISSUE THREAD

**Issue by eriklharper** [chenglou/react-motion#469]
I have a working implementation of `TransitionMotion` for animating an `Aside` component, where there is a width/opacity transition when the Aside is open/closed.  I'm noticing an issue where when the Aside is collapsed and I focus on a different browser tab and then refocus on the tab running my example, that when I click the button to open the Aside again, the transition does not occur.

![hjiznhckpg](https://cloud.githubusercontent.com/assets/821864/25910927/e57db620-3566-11e7-991e-acc82fdc4c62.gif)
http://recordit.co/hjiZnHckpG

In the recording above ☝️  I'm demonstrating that the animation works fine when I keep the Aside open, focus a new tab, come back to the original tab and click the button to collapse, but it fails when the Aside is closed, focus a new tab, then come back.

The transition is working great in all other cases, but just in this particular case its not firing.  Anyone know why?  Here's the code:

```
import {TransitionMotion, spring} from 'react-motion';


class AnimateableAsideContent extends Component {
  constructor(props) {
    super(props);
    this.state = {
      items: [{ key: 'aside' }],
    }
  }

  toggleAside = () => {
    if (this.state.items.length > 0) {
      this.setState({
        items: [],
      });
    } else {
      this.setState({
        items: [{ key: 'aside' }],
      });
    }
  }

  renderAside = (config) => {
    return (
      <div key={config.key} style={{...config.style}}>
        <Aside>Aside goes here.</Aside>
      </div>
    );
  }

  getStyles() {
    return this.state.items.map(item => ({
      key: item.key,
      style: {
        width: item.key ? spring(400) : spring(0),
        opacity: item.key ? spring(1) : spring(0),
      },
    }));
  }

  willEnter() {
    return {
      width: 400,
      opacity: 1,
    };
  }

  willLeave() {
    return {
      width: spring(0),
      opacity: spring(0),
    };
  }

  renderContent = (interpolatedStyles) => {
    return (
      <div>
        {interpolatedStyles.map(this.renderAside)}
      </div>
    );
  }

  render() {
    return (
      <Main>
        <Content style={{ background: 'rgba(159, 212, 201, 1.0)'}}>
          <Button onClick={this.toggleAside}>Toggle Aside</Button>
        </Content>

        <TransitionMotion
          styles={this.getStyles()}
          willEnter={this.willEnter}
          willLeave={this.willLeave}
        >
          {this.renderContent}
        </TransitionMotion>

      </Main>
    );
  }
}
```
Also, when I reproduce the issue, I notice that the toggle sometimes simply stops working!  The state still changes in the React component when I click it in this situation, so this must be an issue with TransitionMotion failing to trigger the transition and subsequent unmounting.

UPDATE: I also see the `willEnter` transition failing when I hit the button to collapse the aside, and then wait until the animation and subsequent unmounting finish completely before clicking the button again.  `willEnter` seems to only work when its interrupting the `willLeave`.

Upon further investigation, it appears that `willEnter` is not called at all when I abort the `willLeave` before it has a chance to complete its unmounting cycle.  The only time `willEnter` gets called is when I wait until the unmounting is completely finished then click the button to open it again.  I placed some console.log statements in both `willEnter` and `willLeave` and this is what I see:

![image](https://cloud.githubusercontent.com/assets/821864/25924940/67cdadaa-359a-11e7-90cf-a1a039b421c7.png)

There are several more `willLeave` calls before the pictured ones, but there's only a single `willEnter` log, meaning its only called once.  I don't know how `willEnter` is supposed to work, but I can only assume at this point, that it should do the exact same thing as `willLeave` is doing, just in reverse.  Can @chenglou help me understand how this is supposed to work?

I also don't get why `willLeave` needs to call `spring()` on the style values it exports whereas `willEnter` does not?

**Comment by eriklharper** [comment]
I figured out what I was doing wrong.  The docs on `willEnter` say `Return: a defaultStyle-like PlainStyle configuration, e.g. {x: 0, y: 0}, that serves as the **starting values** of the animation.`.  I was putting the ending values instead of the starting values.  🤦‍♂️ 

After changing my `willEnter` to this, it now works perfectly!

```
  willEnter() {
    return {
      width: 0,
      opacity: 0,
    };
  }
```
👍 

Suggestion: the docs should be updated to include a full example using both `willEnter` and `willLeave`.

**Comment by nkbt** [comment]
Thanks!

Do you mind filing a pr with docs update? That should be helpful for everyone else who might hit the issue
