### ISSUE TITLE
Deploy demos to github pages?

### ISSUE THREAD

**Issue by therewillbecode** [chenglou/react-motion#482]
Should we deploy the demos to Github pages in order to make them more accessible? Could make a small SPA using create-react-app?

**Comment by nkbt** [comment]
What do you mean? They are on github pages already https://github.com/chenglou/react-motion#demos

**Comment by therewillbecode** [comment]
I was referring to [github pages](https://pages.github.com/) as a way of deploying the demos.

**Comment by nkbt** [comment]
This is exactly what we do.

for example http://chenglou.github.io/react-motion/demos/demo2-draggable-balls/

or any other demo link from readme
