### ISSUE TITLE
Ability to use a different property than 'style'?

### ISSUE THREAD

**Issue by laggingreflex** [chenglou/react-motion#483]
I'm trying to use this with [preact-hyperscript](https://github.com/queckezz/preact-hyperscript) which doesn't seem to play well with the 'style' property:

```js

import { h as defaultH } from 'preact';
import { createElement as hyperscriptH } from 'preact-hyperscript';
import { Motion, spring } from 'react-motion';

class App extends Component {
  render() {
    // return defaultH(Motion, { // < works
    return hyperscriptH(Motion, { // < doesn't work
      defaultStyle: { x: 0 },
      style: { x: spring(10) }
    }, [value => hyperscriptH('div', value.x)]);
  }
}
```
Using the `hyperscriptH`, it gives the error: 

> Failed prop type: Invalid prop `style` of type `string` supplied to `Motion`, expected an object.

I think it's because `preact-hyperscript` converts the `style` property into string. 

Could this be resolved by somehow telling `react-motion` to use a different property than `style`?

Repro: https://github.com/laggingreflex/react-motion-preact-hyperscript-test

PS: Awesome lib!

**Comment by nkbt** [comment]
react-motion is agnostic to this, just use the value in a way you like, it is not `style` or smth, it is just an object, that is passed to children

If you want to make style a string, do it like:
```js
class App extends Component {
  render() {
    // return defaultH(Motion, { // < works
    return hyperscriptH(Motion, { // < doesn't work
      defaultStyle: { x: 0 },
      style: { x: spring(10) }
    }, [({x}) => hyperscriptH('div', {style: `x: ${x}px`})]);
  }
}
```
