### ISSUE TITLE
Animate image everytime src changes?

### ISSUE THREAD

**Issue by Tsury** [chenglou/react-motion#488]
I want an image to do a pulse animation whenever its src is changed. I've created the animation but it only happens once, upon creation, and I don't know how to hook it to the img src.

**Comment by Inlesco** [comment]
Can you share the code you've got now? Then we can work on improving it.

**Comment by Tsury** [comment]
Let's say I'm asking for the best practice approach. Say that I have a generic animation, such as:

```
<Motion defaultStyle={{x: 0}} style={{x: spring(10)}}>
  {interpolatingStyle => <img src={props.mySrc} style={interpolatingStyle} />}
</Motion>
```
props.mySrc comes from the redux state, which is changed by some action. With this code, the animation will happen when the img is firstly mounted, and that's it. What's the best way to make it 'redo' the animation any time the src changes?

**Comment by umidbekkarimov** [comment]
You can hack around react and set `<Motion key={props.mySrc}` so this will force rerender of the `Motion` component by react.

**Comment by Tsury** [comment]
Interesting. I'll check it out, thanks.
