### ISSUE TITLE
Do not check with React.Children.only

### ISSUE THREAD

**Issue by umidbekkarimov** [chenglou/react-motion#499]
`react@0.16` allows us to render strings, numbers, and arrays. But [this](https://github.com/chenglou/react-motion/blob/master/src/Motion.js#L235) line kills it.

Isn't `return this.props.children(this.state.currentStyle);` enough? React pre `0.16` already throws error about invalid children types

**Comment by nkbt** [comment]
ReactMotion expects only one child element that should be a function, so check is still completely legit
