### ISSUE TITLE
Not returning a React Element

### ISSUE THREAD

**Issue by Craques** [chenglou/react-motion#502]
I was following a tutorial on a [simple react motion transition](url) however I am getting the following error

**bundle.js:4882 Warning: Transition(...): A valid React element (or null) must be returned. You may have returned undefined, an array or some other invalid object.**

Here is the code for the Transition component
`export default function Transition (props) {
    let defaultStyles = [], styles = [];
    const {children} = props;
    React.Children.map(children, (child)=>{

        if(child){
            defaultStyles.push({
                key: child.key,
                data: child,
                style: {opacity: 0}
            });

            styles.push({
                key: child.key,
                data: child,
                style: {opacity: spring(1)}
            })
        }
    });

    function willEnter() {
        return {opacity: 0}
    }

    function willLeave() {
        return {opacity: spring(0, {stiffness: 90, damping: 11})}
    }

    console.log(styles, defaultStyles);

    <TransitionMotion styles={styles} defaultStyles={defaultStyles} willEnter={willEnter} willLeave={willLeave} children={props.children}>
        {
            (styles)=>{
                return(
                    <div>
                        {
                            styles.map((child)=>{
                                if(child){
                                    const {key, data, style} = child;
                                    return React.cloneElement(
                                        data,
                                        {key, style}
                                    )
                                }else{
                                    return null
                                }

                            })
                        }
                    </div>
                )
            }
        }
    </TransitionMotion>
}`

and here is how I am trying to implement it

`class GroupItem extends Component{

    render(){
        return(
            <Transition>
                {<div key="1">Hello there</div>}
            </Transition>
        )
    }
}

Any help would be great `

**Comment by bloodyowl** [comment]
Hi 👋 Can you file a working repro of the behaviour you experience? https://jsfiddle.net/69z2wepo/89288/

**Comment by Craques** [comment]
I mannaged  to recreate the error in the fiddle, my first time using it but you can check the updated fiddle https://jsfiddle.net/69z2wepo/89538/

**Comment by bloodyowl** [comment]
https://jsfiddle.net/69z2wepo/89552/ there were some errors here, but the main one was that you didn't return the `TransitionMotion` component

**Comment by Craques** [comment]
Got it thanks was just missing a return statement I updated the fiddle its working now https://jsfiddle.net/69z2wepo/89560/

**Comment by takahiro-saeki** [comment]
@Craques if you could resolve this problem, you might have better close this issue.
