### ISSUE TITLE
React v16 support

### ISSUE THREAD

**Issue by zvxayr** [chenglou/react-motion#503]
A new feature of react is to return strings and arrays on render, not just react components. I tried returning a string on a Motion child but i got this error `React.Children.only expected to receive a single React element child.`

**Comment by zvxayr** [comment]
this is basically issue [#499](https://github.com/chenglou/react-motion/issues/499).

**Comment by nkbt** [comment]
Replied in #499
> ReactMotion expects only one child element that should be a function, so check is still completely legit
