### ISSUE TITLE
Is there anything that allows for custom interpolators? How do you treat non-binary animations?

### ISSUE THREAD

**Issue by drcmda** [chenglou/react-motion#526]
I am trying to tween from one color to another, as well as gradients and svg paths. I am using work-arounds for now, like dozens of springs, storing theme colors in bytes, as well as helper functions everywhere.

This is how i currently go from one color to another: 

    const initialState = {
        colors: {
            BOOTING: [0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00],
            EMPTY: [0x1a, 0x1e, 0x2d, 0x1a, 0x1e, 0x2d, 0x0d, 0x0d, 0x15],
            DROP: [0xd4, 0xb6, 0xa1, 0xb4, 0x46, 0x46, 0x12, 0x38, 0x4a],
            ACTIVE: [0x24, 0x2a, 0x42, 0x24, 0x2a, 0x42, 0x1b, 0x1c, 0x2d],
            SELECT: [0xa9, 0x43, 0xe4, 0xf5, 0x59, 0x89, 0xff, 0xaf, 0x84],
            ...

    const style = colors[appState].reduce((acc, col, i) => ({ ...acc, [i]: spring(col) }), {})
    const defaultStyle = colors['BOOTING'].reduce((acc, col, i) => ({ ...acc, [i]: col }), {})
        return (
        <Motion defaultStyle={defaultStyle} style={style}>
             {bytes => <Gradient {...bytes} children={children} />}
        </Motion>

    const c = (p, i) => `rgb(${Math.round(p[i])},${Math.round(p[i + 1])},${Math.round(p[i + 2])})`
    const Gradient = p => (
        <div
            style={{
                background: `linear-gradient(to bottom, ${c(p, 0)} 0%, ${c(p, 3)} 50%, ${c(p, 6)} 100%)`,

and morph from one svg to another:

    const m = (a, b, d) => a + (b - a) * d
    const Path = ({ delta: d }) => (
        <path
            d={`M20,${m(380, 20, d)} L${m(380, 20, d)},380 L380,380 L${m(200, 380, d)},20 L20,${m(380, 20, d)} Z`}

It doesn't feel right. There must be something i have overlooked. I searched through the issues, came across something here and there, but i found nothing in the official api.

Could `spring` perhaps take a custom interpolator so that complex stuff could be managed via clean extensions? 

    import { svgInterpolate, gradientInterpolate } from 'third-party'

    <Motion
        defaultStyle={{ path: "M20,380 L380,380 L380,380 L200,20 L20,380 Z" }}
        style={{ path: spring("M20,20  L20,380  L380,380 L380,20 L20,20 Z", { interpolate: svgInterpolate }) />

    <Motion
        defaultStyle={{ background: "linear-gradient(#242a42 0%, #242a42 50%, #1b1c2d 100%)" }}
        style={{ background: spring("linear-gradient(black 0%, white 50%, red 100%)", { interpolate: gradientInterpolate }) />

**Comment by drcmda** [comment]
Just for reference, the issue nagged me enough to give this a go. I first tried to rewrite react-motion but got stuck as it's too high level to easily embed a larger change. I looked at animated, which is low level, and found it easier to mold it into react-motion-like springs and render props: https://github.com/drcmda/react-spring

**Comment by alexeyraspopov** [comment]
I have an example of how you can use `react-motion` for SVG paths. I've been using such approach for a while now, everywhere I needed to make data viz transitions smooth. The example component has been updated to v16.3 API recently and so tested as well.

```javascript
import React, { PureComponent } from 'react';
import { Motion, spring } from 'react-motion';
import { interpolatePath } from 'd3-interpolate-path';

export default class PathMotion extends PureComponent {
  state = { direction: 0, interpolate: null, path: null };

  static getDerivedStateFromProps(nextProps, prevState) {
    if (nextProps.path === prevState.path) return null;
    let direction = 1 - prevState.direction;
    let interpolate = interpolatePath(prevState.path, nextProps.path);
    return { direction, interpolate, path: nextProps.path };
  }

  render() {
    return (
      <Motion style={{ progress: spring(this.state.direction) }}>
        {style => {
          let progress = Math.abs(1 - this.state.direction - style.progress);
          return this.props.children(this.state.interpolate(progress));
        }}
      </Motion>
    );
  }
}
```

And here is how it gets used:

```javascript
import React, { Fragment } from 'react';
import { area, line, curveCardinal } from 'd3';
import PathMotion from './PathMotion';

export default function Line({ getX, getY, data }) {
  let curve = curveCardinal.tension(0.5);
  let targetArea = area().x(getX).y1(getY).y0(() => 300).curve(curve);
  let targetLine = line().x(getX).y(getY).curve(curve);
  return (
    <Fragment>
      <PathMotion path={targetArea(data)}>
        {(d) => <path d={d} fill="url(#linear)" />}
      </PathMotion>
      <PathMotion path={targetLine(data)}>
        {(d) => <path className={Ns.line} d={d} fill="transparent" />}
      </PathMotion>
    </Fragment>
  );
}
```
