### ISSUE TITLE
How to avoid re-rendering N times the whole page ?

### ISSUE THREAD

**Issue by Fandekasp** [chenglou/react-motion#540]
We're using Motion on the top element of our page to make a smooth transition when loading the page.
The problem is that the page is huge, and after rendering all its elements, the whole thing will be rerendered 10 more times due to the opacity of interpolatingStyle slowly moving from 0 to 1.

What would be the right solution to only modify the top div element's style without re-rendering all its children ?

**Comment by Fandekasp** [comment]
I thought we could skip react-motion altogether and use instead a css3 transition `transition: opacity 2s easy; opacity: 1`, but it doesn't seem to work....

**Comment by Fandekasp** [comment]
@trusktr I already have the interpolation done in a PureComponent. Below is the decorator I came with:
```
export const withMotion = ComposedComponent =>
  /* eslint-disable-next-line react/no-multi-comp */
  class extends PureComponent {
    static displayName = `withMotion(${ComposedComponent.displayName ||
      ComposedComponent.name})`;

    render() {
      return (
        <Motion defaultStyle={{opacity: 0}} style={{opacity: spring(1)}}>
          {interpolatingStyle => (
            <div style={interpolatingStyle}>
              <ComposedComponent {...this.props} />
            </div>
          )}
        </Motion>
      );
    }
  };
```

Honestly, I'm not sure whether my stuff is really re-rendered many times or not, since react has also this dom reconciliation stuff.
Anyways, I'm out of time to try optimizing this, so I'll close the issue for now, thanks for your reply.

**Comment by nkbt** [comment]
You can add console.log to your `render` function and see if it is updated all the time.


On a side note PureComponent will not prevent re-render if you pass any callbacks similar to `onClick={() => this.setState({clicked: true})}`, since in this case *new* function is created every render. Should be ok for react motion though.

Example creates PureComponent and has Motion inside of it, that makes no difference at all. You need to wrap your *content* in pure and use it as children of Motion

Something about this
```jsx
export const withMotion = ComposedComponent => {
  class MotionContent extends PureComponent {
    render() {
      return (
        <ComposedComponent {...this.props} />
      );
    }
  }
  return class extends PureComponent {
    render() {
      return (
        <Motion defaultStyle={{opacity: 0}} style={{opacity: spring(1)}}>
          {interpolatingStyle => (
            <div style={interpolatingStyle}>
              <MotionContent {...this.props} />
            </div>
          )}
        </Motion>
      );
    }
  }
};
```

**Comment by trusktr** [comment]
Perhaps also remove `PureComponent` and use `Component` to see if that helps. Indeed, you're div's style attribute should be re-rendered many times during that animation (as @nkbt said, you should see a console.log fire many times if you put one in your render method).
