### ISSUE TITLE
Two-way animations

### ISSUE THREAD

**Issue by WebDeg-Brian** [chenglou/react-motion#560]
Is there a way to do two-way animation (e.g shaking animation)? Like this:
```
<Motion 
    defaultStyle={{
      ypos: -110
    }} 
    style={{
      ypos: spring(-110) 
      //This is definitely not correct, but I want spring to animate to a certain value
      //Then go back to -110, so the component looks like it's shaking?
    }}>
      {({ypos}) => 
        <AnimatedBox />
      }
  </Motion>
```

**Comment by nkbt** [comment]
You can keep your own state and when previous animation is finished, "flip the switch"

See https://github.com/nkbt/react-motion-loop for example

**Comment by WebDeg-Brian** [comment]
@nkbt Thank you for your quick response, will try it out!
