### ISSUE TITLE
How may I use rem solution with  function spring()

### ISSUE THREAD

**Issue by releasethecow** [chenglou/react-motion#561]
In my application I wanna use remjs for my layout.
How may I use spring() function to fix this?

**Comment by nkbt** [comment]
fix what? what is broken? what is remjs? is there any codepen/codesandbox to see what you are trying to do?

**Comment by MomoHong** [comment]
@releasethecow 
`
...
style: {
  height: spring(.84, presets.gentle)
 }
.....
<a href={url} key={j} style={{height:`${style.height}rem`}}><span>{desc}</span></a>
`

**Comment by releasethecow** [comment]
@MomoHong Thanks a lot!
