### ISSUE TITLE
Code in npm is different than github repo

### ISSUE THREAD

**Issue by shizpi** [chenglou/react-motion#567]
I got into an issue with setState in a unmounted component and tracked down the issue to this: https://github.com/chenglou/react-motion/pull/305

The 0.5.2 version in this repo has the following check in Motion, TransitionMotion and StaggeredMotion:
```
if (this.unmounting || this.animationID != null) {
  return;
}
```

I took a look at the code in my node_modules and noticed `Motion` doens't have the `this.unmounting` flag nor the code above.

I have 0.5.2 in my package.json and in `node_modules/react-motion` there's indeed 0.5.2 in package.json but there's 0.5.1 in bower.json

It looks like the code published in npm is outdated

**Comment by roderickhsiao** [comment]
yes, we have a discussion 

https://github.com/chenglou/react-motion/pull/509#issuecomment-479750876 

Will need the author or maintainer to help on this :)

**Comment by nkbt** [comment]
Latest updates were not published, please follow https://github.com/chenglou/react-motion/issues/569#issuecomment-780190833 thread for updates
