### ISSUE TITLE
can a release be tagged?

### ISSUE THREAD

**Issue by rhenwood-arm** [chenglou/react-motion#570]
@nkbt : I appreciate you have made a clear statement about how much time you can spend on this project -- but I would like to ask if you could make a release.

**Comment by rhenwood-arm** [comment]
It would be helpful for me to pick up a version that doesn't have the PhantomJS dependency removed here: https://github.com/chenglou/react-motion/pull/555

**Comment by nkbt** [comment]
closing as we already have https://github.com/chenglou/react-motion/issues/569#issuecomment-780190833 please follow that thread instead
