### ISSUE TITLE
Animating an element with a varying width 

### ISSUE THREAD

**Issue by snarkshow** [chenglou/react-motion#574]
Scanned the issues briefly and couldn't quite find anything that was relevant.  

I have a component that is set to (width: auto), because it renders at a different width based on the length of the word inside it.  I want to animate it so that it extends to 100px larger than whatever it currently is.

Right now, I'm measuring the width of the rendered component in pixels, storing it in state,  storing the desired extended width, and passing them both to the interpolated styles.  

FOR EXAMPLE

` 
//Measuring rendered width and calculating new width
this.state.width = 350px;
this.state.newWidth = 450px;

//Passing width and new width to desired styles
getStyle = () => {
    let x = this.state.width;
    let y = this.state.newWidth;
    let style = {};
    if (this.state.open) {
      style = {
        w: spring(y, springConfig),
      };
    } else {
      style = {
        w: spring(x, springConfig),
      };
    }
    return style;
  };`

I'm finding that I can animate from a variable (x) to a set number (like "400"), but I can't animate from variable x to variable y.  Is this a common thing with React Motion and (width:auto)?  Should I always be hard-coding one of the widths?

**Comment by nkbt** [comment]
You cannot animate to the unknown width or height (`auto` is effectively unknown and will be calculated by browse on the go).

For the height animation is pretty much sorted by https://github.com/nkbt/react-collapse. For the width there is a feature request https://github.com/nkbt/react-collapse/issues/213

Hope this helps

**Comment by mlacif1** [comment]
We also need this to be merged quite asap please.
