### ISSUE TITLE
Need to maintain same build file locations

### ISSUE THREAD

**Issue by nkbt** [chenglou/react-motion#577]
We used to have `lib/react-motion.js` and `build/react-motion.js`, current partially completed move to rollup puts files into a different dirs, so we cannot publish patch version. 

I will do an update asap to keep build artefacts in old spots so we do not introduce unnecessary breaking change

**Comment by jchook** [comment]
Can we possibly cherry-pick #575 commits into a patch?

**Comment by nkbt** [comment]
It's not about #575 things, it is about breaking changes that were introduced earlier but not completed and never published. I've pretty much got it all working now and will submit a PR soon. That would allow to keep rollup build but put files in the same dir as it used to be and in addition to that we will have a babel build for multi-file common-js that is compiled into `lib/`.
