### ISSUE TITLE
Release support for React 17

### ISSUE THREAD

**Issue by daveisfera** [chenglou/react-motion#605]
If appears the `react` dependency has been changed to `>= 15.5.0` but not released, so can that be released?

**Comment by nkbt** [comment]
Please see https://github.com/chenglou/react-motion/issues/569#issuecomment-780190833

**Comment by nkbt** [comment]
You can try using published fork from https://github.com/chenglou/react-motion/issues/604#issuecomment-770198710 meanwhile
