### ISSUE TITLE
Simplified wrappers for common use cases?

### ISSUE THREAD

**Issue by yamalight** [chenglou/react-motion#61]
Any plans for creation of simplified wrappers for common transitions (e.g. adding items to list)?
Would be cool to have something similar to the `<SimpleTransition />` I'd implemented in [this demo](https://jsbin.com/wowupi/edit?js,output), but better :smile:

**Comment by chenglou** [comment]
Actually, before we get to wrappers, I _might_ be able to release a simplified API for those things. Stay tuned tonight/tomorrow

**Comment by yamalight** [comment]
@chenglou oh, sounds pretty awesome! can't wait to see it :+1:

**Comment by chenglou** [comment]
Alright! @souporserious is experimenting with some simple wrappers [here](https://github.com/souporserious/react-motion-ui-pack). I personally haven't used them yet but they look neat.

As for the simple wrappers, https://github.com/chenglou/react-motion/commit/372446fc8679dcdbf4de2e983d53709ab40ce88c exposes some commonly used spring constants. With these, I think something like:
```
<Spring endValue={{val: 10, config: wobbly}}>...
```
is short enough not to warrant actual wrapper components in core lib. Might change in the future if I spot some more complex use-cases (e.g. advanced `TransitionSpring`). But for now I'll close the issue =).

**Comment by yamalight** [comment]
@chenglou looks great, thank you!
