### ISSUE TITLE
Special Hack Key

### ISSUE THREAD

**Issue by tychotatitscheff** [chenglou/react-motion#63]
May be silly but I cant find the "slowmotion", "rave the future" and other keys used in react conf ?

Is it published somewhere ??

**Comment by hzoo** [comment]
Was removed in https://github.com/chenglou/react-motion/pull/23 but 

> We'll make an actual dedicated functionality for this in the future.

**Comment by chenglou** [comment]
Not silly at all! I knew someone would be asking for this =)
Feel free to revert to that commit and try the keys! But yes, lots of potential for tooling there.
Closing!

**Comment by tychotatitscheff** [comment]
I see !
And i understand the problem raised in #23.

Did you guys  thinks we can refactore this into a "react-motion/addons"  it is quite useful to debug.
