### ISSUE TITLE
Make interpolating collection work on iterables

### ISSUE THREAD

**Issue by chenglou** [chenglou/react-motion#69]
This way you get to use libraries like Immutable-js without explicit support for them.

**Comment by nkbt** [comment]
That is a great idea.

**Comment by dozoisch** [comment]
That'd be awesome!

**Comment by maslianok** [comment]
+1

**Comment by chenglou** [comment]
Closing this =).

Will reopen in the future if I can take immediate action. But for now, since `style` is a flat object there's really not many reason to use an iterable (?). Plus, for-in loop is much faster?.
