### ISSUE TITLE
Stop allocating so much

### ISSUE THREAD

**Issue by chenglou** [chenglou/react-motion#70]
Prototyping period is done. Current API somewhat stable. This is still not high-pri (need to get a few other things in, including tests), but time to stop allocating like crazy in core. If we have to we'll turn the codebase inside out to squeeze out that last drop of frame.

**Comment by bsansouci** [comment]
I have a few optimizations locally, especially when `endValue` returns an array. I'm waiting for #57 to get merged though because I don't want to him to commit suicide after rebasing/merging so many times.

**Comment by chenglou** [comment]
Closing because too general. Will open specific issues if needed.
