### ISSUE TITLE
change the default of willLeave

### ISSUE THREAD

**Issue by bsansouci** [chenglou/react-motion#73]
After writing a couple demos with `react-motion`, and looking at other people's demos, I realized that there seems to be a pretty common use case for  `willLeave` which is different from the current default. 

The current default is `willEnter = () => null`, meaning that the `TransitionSpring` will unmount as soon as there's a missing key in the return of `endValue`. This default makes sense because it's `Spring` and `TransitionSpring` interchangeable (if you want to not throw when `endValue` returns an object of a different shape). 

I think `TransitionSpring` would be mostly used when you **do** want mounting/unmounting animation. The most common use case seems to be 

```js
defaultWillLeave = (key, endValue, currValue, currVelocity) => {
  if(eq(currValue[key], endValue[key]) && noSpeed(currVelocity[key])) { // `eq` is just deep equality
      return null;
    }
   
   return ??? // This is a problem
}
```

There are two problems here:
1. `endValue` doesn't contain `key` yet because it's called during the merging, so how to check if you've 
reached something that the function is suppose to return?
2. What do you return if you haven't reached this ghost `endValue[key]`?

One possible solution is to make `willEnter` and `willLeave` both be allowed to be data structures. If they are data structures we can trivially check if you've reached the destination (because it's the same whatever the `key`), and then the return would be that data structure.

```js
defaultWillLeave = (key, endValue, currValue, currVelocity) => {
  if(eq(currValue[key], endValue) && noSpeed(currVelocity[key])) {
      return null;
    }

   return endValue
}
```

This is how you'd use the `TransitionSpring`
```jsx
<TransitionSpring endValue={this.endValue} willEnter={{opacity: 0}} willLeave={{opacity: 0}} />
```

What do you think?

**Comment by chenglou** [comment]
Fixed by https://github.com/chenglou/react-motion/pull/105
