### ISSUE TITLE
TransitionSpring bugs on willEnter

### ISSUE THREAD

**Issue by chenglou** [chenglou/react-motion#77]
Repro: demo3, type `p`. Remove `p`. Original list doesn't come back because [this](https://github.com/chenglou/react-motion/blob/1ec99fef09a9510a643357f7e2b9c8b7f02e8e68/src/Spring.js#L361) is met.

**Comment by chenglou** [comment]
@iclanzan

**Comment by iclanzan** [comment]
Interesting, I never waited log enough for the animations to finish in my tests so I never ran into this. :)

How is it that it was working before though?

**Comment by chenglou** [comment]
Probably through some funny combination of booleans?

**Comment by iclanzan** [comment]
No, but I mean you were still checking the velocity to decide when to stop and yet it was working.

**Comment by chenglou** [comment]
Aren't we talking about how to restart here?

**Comment by iclanzan** [comment]
I guess that’s the real issue, yes.

**Comment by iclanzan** [comment]
What do you think of changing [this line](https://github.com/chenglou/react-motion/blob/master/src/Spring.js#L353) to: `mergedValue[key] = endValue[key];`?

That seems to solve it.

**Comment by chenglou** [comment]
I'll have to think about the implication of this difference for TransitionSpring. I _think_ this is fine. @bsansouci

**Comment by bsansouci** [comment]
This will make the raf stop after the first render, which was handled by [this](https://github.com/chenglou/react-motion/blob/5541cca8d569661ec7e183414ca95118faaab875/src/Spring.js#L152) previously. Preventing certain CSS transitions to work. 
Example [here](https://gist.github.com/bsansouci/c8c760339f5134c50ac5).

A possible way to fix this is to change [this line](https://github.com/chenglou/react-motion/blob/master/src/Spring.js#L361) to:
```js
if (noVelocity(currVelocity) && noVelocity(newCurrVelocity)) {
  if (this.oneMoreTime) {
    this.unsubscribeAnimation();
    this.unsubscribeAnimation = undefined;
    this.oneMoreTime = false;
  } else {
    this.oneMoreTime = true;
  }
} else {
  this.oneMoreTime = false;
}
```

and initialize `this.onMoreTime` [here](https://github.com/chenglou/react-motion/blob/master/src/Spring.js#L281).

**Comment by iclanzan** [comment]
I don’t think using a flag is a solid solution. Nor is checking velocity. Different types of simulations have different conditions that need to be met in order to stop. Decay should stop when velocity is 0. A spring should stop when both the end position has been reached and velocity is 0. You could have other types of animations that shouldn’t stop when velocity is 0. For example animations with delay.

**Comment by bsansouci** [comment]
I would disagree with that actually. I think in this case, stopping the loop is merely an optimization which shouldn't affect the rendering/interpolation. If stopping the loop causes anything to not refresh then we're doing it wrong.

**Comment by chenglou** [comment]
It's not merely an optimization. It stops to be one the moment you want to expose a `onEnd` callback (though you could argue we should not expose one).

A flag here is fine because what we're doing here doesn't correspond to anything in a physics simulation. There's no such thing as "run one more frame" in that world. We do it because the user receives the previous tick's `currentValue` in `endValue` and might decide to start a new animation. This is the pitfall of the API (but also its strength, as this way you don't need to expose the actual, more accurate current tick `currentValue`, which, again, involves creating a value binding API).

Checking the velocity might not be a solution, true. But we're only concerned with Spring here for now. A `Decay` component will have its own check for stopping.

Anyhow this is blocking a release and we gotta get it solved quickly. If we can't find a better solution, a boolean is fine for now. It's not user-facing so we'll try to find a better solution after that.

**Comment by iclanzan** [comment]
I get it. With the boolean flag I don’t think `currVelocity` needs to be checked to be zero. `newCurrVelocity` should suffice.

**Comment by chenglou** [comment]
Already fixed since forever. Tests in.
