### ISSUE TITLE
Explore transducerjs/generators for updateCurr*

### ISSUE THREAD

**Issue by chenglou** [chenglou/react-motion#80]
cc @threepointone who first mentioned generators for avoiding allocating intermediate stuff. Transducerjs can probably do the same.

Generators might give bad perf (constant overhead) though IIRC. But maybe the Regenerator transform that babel uses avoids that? Have to test the real numbers.

**Comment by threepointone** [comment]
If interested, have a look at this commit that uses a generator to merge updateCurr* - https://github.com/threepointone/react-motion/commit/69185a62253e048a7a4508c24eafb597904c36cc?diff=split (I also have a change where `stepper` is replaced with a generator, will push that in a bit.)

I haven't had the time to perf test this throughly, but chrome's perf audit shows updateCurr taking slightly higher percentage of the time(despite running it through regenerator). But it's also half the iterations, so am unclear on what that means. Do you have a stress test I can run with this?

Am now thinking transducers

**Comment by chenglou** [comment]
Eh, 1k chat heads? Lol

**Comment by chenglou** [comment]
Bah it's fine now. New API only animates a shallow object.
