### ISSUE TITLE
the case of CSS Transitions

### ISSUE THREAD

**Issue by bsansouci** [chenglou/react-motion#83]
Basically, with the current implementation of `Spring`, CSS transitions won't work reliably.

There are two reasons that I can see, maybe more, that causes them to not trigger:
### 1. Will stop rendering after the first frame
If `endValue` returns an array of `ReactElements` there will be no interpolation, only the diffing algorithm will be used. 
Start state: `{counter: 0}`
Start of the frame (one step at a time):
- `this.setState({counter: counter + 1})`
- render of the owner
- `Spring` loop
- call to `endValue`, which returns `[ReactElement with key "1"]`
- call to `mergeDiff`, which return `[ReactElement with key "0", ReactElement with key "1"]` (because "0" shouldn't leave yet)
- we check what's new in the `mergedObject` and call `willEnter`, which returns `ReactElement with key "1"` having for `className` some class used for initial position (and which needs to be transitioned)
- not interpolation because it's an array of `ReactElement`s
- Velocity is 0, so [this line](https://github.com/chenglou/react-motion/blob/master/src/Spring.js#L361) will be true and the animationLoop will stop

So `ReactElement with key "1"` had a chance to get mounted, but won't have a chance to see its `className` change (which is required for the CSS Transition to be triggered.

A possible fix is detailed [here](https://github.com/chenglou/react-motion/issues/77)

### 2. FPS too high
That's a bigger problem, which makes me wonder if we should support CSS Transitions.
Basically, if you want something to transition in using CSS transitions, you'll write a `willEnter` that will return your component with a class with a transition property (say `className1`). Then you'll rely on the fact that `willEnter` is called only once when something should be mounted, and then `endValue` is called, which would set the `className` to a default one (say `className2`). This would cause the object to switch from `className1` to `className2` and the browser would kick in and smoothly transition between the two class's properties (depending what you want to transition).
But because of the nature of how JS handles which function is allowed to run when (in the case of requestAnimationFrame), it's very likely that the Spring loop will run twice in a row, not giving enough time for the browser to see the className change and resulting in no transition.

The only reason why demo5 works right now is because of point number 1. If you comment out [this line](https://github.com/chenglou/react-motion/blob/master/src/Spring.js#L361) you'll see this:

![css-transition-bug](https://cloud.githubusercontent.com/assets/4534692/8764735/a09dcc7c-2db9-11e5-8f25-9b3013b7a25d.gif)

I want to know what you guys think, if it's worth implementing or not, and if so, what would the best way to go about this be.

My conclusion from this is that to support CSS transitions properly we'd probably need a special Spring and a special animation "loop" (which wouldn't necessarily be an actual loop). I personally think that most things can be handled by JS, and the only place where CSS Transition shine is when you need 

Issues related: #72, #77 and #38 
ping @brumm

**Comment by chenglou** [comment]
Point 2: are you sure this is the issue? This is important. It's because of the new animation loop. @iclanzan

(Assuming it _is_ because of the new animation loop) this is actually somewhat of a relief. I was afraid of cramming more stuff into TransitionSpring for the sake of playing nice with CSS transitions, which really doesn't need an animation loop. Maybe we'll simply pull out the logic into a CSSSpring (or not). I think doing this will also allows #77 to have simpler solutions?

**Comment by bsansouci** [comment]
Actually I might be wrong about point 2. It's possible that what happens is that the onScroll event is fired before willEnter is called, so `alreadyAppeared[key]` is set to true and willEnter just returns `value`, making the thing appear immediately.

**Comment by iclanzan** [comment]
@bsansouci  While I can’t repro the issue, both your scenarios for point 2 sound plausible. The animation loop can indeed run multiple steps in one frame which could cause what you are describing.

I don’t think the animation loop should be involved at all if it not for coordinating the physics simulation.

**Comment by bsansouci** [comment]
I added a bunch of `console.log`s, here is what is looks like:

![out](https://cloud.githubusercontent.com/assets/4534692/8768757/e6d5e4c8-2e58-11e5-8bfb-0f96e86783ea.gif)

Basically this shows that a render is triggered by the owner, and slide 11 was added to the scene. Then the handleScroll event fired, and set all slides up until 12 to visited. Then, because `handleScroll` does a `setState`, we see another render in the owner. Then finally `requestAnimationFrame` fires, `willEnter` is called on `"12-slide"` but as we just saw it was just set to visited. `willEnter` therefore returns the `value` it was given, which doesn't have any `className`. We also see that `"13-slide"` also enters the scene, but wasn't set to visited (because we actually render one more element [here](https://github.com/chenglou/react-motion/blob/393bf8db81a638a7234d24c3eccf81fc3c837d30/demos/demo5/Demo.jsx#L88))

So the problem isn't our Spring but the demo itself, we're setting `alreadyAppeared` in a callback of an event, not synched with any rendering logic. I'm not too sure what the best way to approach this problem is.

ps: no it's not because of the new animation loop, I tested before and after merging #57.

**Comment by bsansouci** [comment]
Ok so I was wrong, we don't set a slide visited immediately, we set the previous one (look at [this line](https://github.com/chenglou/react-motion/blob/d00efbe4252e238a500e7d36727bc61d2d6cfeaa/demos/demo5/Demo.jsx#L70), we don't set `last` to `alreadyAppeared`).

So willEnter does execute at least once for every item (though it _might_ not, if you scroll **really** quickly). What happens is that the `className` returned by `willEnter` is never rendered because we skip it! We skip it inside the `animationLoop` [here](https://github.com/chenglou/react-motion/blob/d00efbe4252e238a500e7d36727bc61d2d6cfeaa/src/animationLoop.js#L55-L58). If it happens that the tick at which we called `willEnter` took longer than one `timestep` then we'll move two steps (as described [here](https://github.com/chenglou/react-motion/pull/57#issuecomment-121924628)) and therefore will overwrite `willEnter`'s value with `endValue`'s value.

Here is some `console.log`s. `10-slide` appeared without transitioning in this case. The first line shows `this.accumulatedTime` (`25.564666...ms`) which _is_ bigger than `16ms`. We then see one step being made (and the first call to `willEnter`), immediately followed by another step over writing the `className`. It then sets the state and renders (and never renders the value of `willEnter`).
![screenshot 2015-07-22 15 47 13](https://cloud.githubusercontent.com/assets/4534692/8835538/1d15c224-3089-11e5-83ea-8898eda14425.png)


To confirm this I changed [this](https://github.com/chenglou/react-motion/blob/d00efbe4252e238a500e7d36727bc61d2d6cfeaa/src/animationLoop.js#L55-L58) to this
```js
if (this.accumulatedTime > 0) { // Only ever step once
  this.subscribers.forEach(this.step); 
  this.accumulatedTime -= timeStep;
}
while (this.accumulatedTime > 0) this.accumulatedTime -= timeStep; // make sure we're back to "usual"
```

That fixed demo5. 

_disclaimer_: after v0.2.0, support for arrays of `ReactElement`s was removed so I had to modify demo5 a little, but still had the problem before this fix.

**Comment by iclanzan** [comment]
Isn’t that what I said in my comment above?

> The animation loop can indeed run multiple steps in one frame which could cause what you are describing.

**Comment by bsansouci** [comment]
Ha! I read too quickly. Yes though it doesn't cause what I said before.

**Comment by bsansouci** [comment]
Closing this because neither `Spring`s support CSS Transitions for now.
