### ISSUE TITLE
Sample Usage code does not work as expected.

### ISSUE THREAD

**Issue by iandanforth** [chenglou/react-motion#84]
Not sure exactly what's going on but if you include react-motion.js and then try to use the Sample Usage code you get errors like:

```
Uncaught ReferenceError: TransitionSpring is not defined
```

adding in 

```
let TransitionSpring = ReactMotion.TransitionSpring;
```

Removes that error, but then there is a Syntax error in the render() return jsx, then once that's fixed you get

```
Uncaught TypeError: Cannot read property 'a' of undefined
```

**Comment by bsansouci** [comment]
How did you include `react-motion`?
This seems to work for me `import {TransitionSpring} from 'react-motion';`

**Comment by iandanforth** [comment]
@bsansouci  This is using the built react-motion.js, included with standard script tags. i.e. All client side, no build step other than having jsx transformer.

**Comment by bsansouci** [comment]
Mmh what does your render look like?

**Comment by iandanforth** [comment]
![screenshot from 2015-07-19 11 33 53](https://cloud.githubusercontent.com/assets/446062/8767218/58c26bdc-2e0a-11e5-9fdf-0ced641f514d.png)

**Comment by iandanforth** [comment]
@bsansouci The TypeError happens when clicking on the first div

**Comment by bsansouci** [comment]
I'm a little confused as to why that would happen. Can you print inside 
```js
  handleClick(key) {
    let {...newBlocks} = this.state.blocks;

    console.log(newBlocks, key); // Add this

    delete newBlocks[key];
    this.setState({blocks: newBlocks});
  },
```

**Comment by iandanforth** [comment]
Object {a: "I am a", b: "I am b", c: "I am c"} "a"

**Comment by bsansouci** [comment]
Can you try the new demo code and see if it works?
