### ISSUE TITLE
can't setState inside the Spring/TransitionSpring

### ISSUE THREAD

**Issue by bsansouci** [chenglou/react-motion#88]
If you do a call to `this.setState` inside say `componentWillReceiveProps` of the `TransitionSpring`, `animationLoop` won't see the new state. This is because `animationLoop` caches the state while it's running (see [here](https://github.com/chenglou/react-motion/blob/ba77a1a0991a501ccb3676e8bbd0a5d59338f2a0/src/animationLoop.js#L102), it uses `subscriber.value`, which is a reference to this.state and which will never any setState updates). I think it's something that should be documented somewhere, if we decide to keep the animationLoop to way it is.

The least horrible hack we found is to set a flag `this.dirty` anywhere to tell the `animationLoop` to use `this.currValue` or `this.currVelocity` instead of the state passed in as argument. I don't like this very much because then the `animationStep` isn't a pure function, and we lose a lot of the purpose of `animationLoop`. This might mean that this logic can't be extracted out, and should be inlined inside the component itself.

**Comment by iclanzan** [comment]
Having state outside of the animation loop and into the Spring is totally valid and works with the current animation loop. Having said that, `setState` should still not be called other than in the `renderAnimation` method since it triggers re-renders outside of `requestAnimationFrame`.

**Comment by chenglou** [comment]
Well this sure took a long time to close...
We've put a hook in `componentWillUpdate` to sync stable changes. The strategy can change but the tests are now there to guard against it. @bsansouci feel free to check that it meets your expectations.
