### ISSUE TITLE
Reminder: avoid triggering renders outside of the animation loop

### ISSUE THREAD

**Issue by bsansouci** [chenglou/react-motion#90]
This is just a reminder for the upcoming refactoring/release. We're currently not calling `setState` anywhere.

We should make sure that nothing is triggering renders other than the animation loop to avoid unnecessary renders. We could either never call `setState`, or add an extra property to all calls to `stateState`. Something like `this.setState({...state, shouldRender: false})`. And have `shouldComponentUpdate` return `newState.shouldRender`.

**Comment by ericf** [comment]
Won't people hit subtle bugs with this?

The function-as-child render delegate pattern provides a similar textual cue as the standard element-as-child pattern, the difference is the owner. When combined with arrow functions, I might be using `this.props` inside the render-function-passed-as-a-child to `<Spring>`, so it gives the illusion that `<Spring>` isn't the owner.

So for me, this means that anytime the function-as-child render delegate pattern is used, the component should always return `true` from its `shouldComponentUpdate()`.

**Comment by bsansouci** [comment]
You're right, re-reading this I realize it's wrong. Also after playing around with the `animationLoop` I understand why we need to cache the state. We might need a special `animation.setState` to tell the animationLoop that the state updated. This might be required if we ever add `currValue` or `currVelocity` as a prop.

**Comment by chenglou** [comment]
Fixed in v0.4.1. Feel free to (fail to) try to reproduce this! =).
